### ISSUE TITLE
[Issue] partition number in ImageSet.read and NNImageReader is not always working

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1005]
Right now the partition number is only suggestive and often is ignored by sc.binaryfiles. Shall we use coalesce internally to force the partition split?

**Comment by hhbyyh** [comment]
cc @dding3 what do you think?

**Comment by dding3** [comment]
The issue is duplicate with https://github.com/intel-analytics/zoo/issues/271. I think it's more like an spark optimization and it looks good to me.

**Comment by hhbyyh** [comment]
Thanks. Let's close this and move the discussion there.
