### ISSUE TITLE
ut failures when upgrade to pytorch 1.0.0

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#1011]
====================================================================================================== FAILURES ======================================================================================================
____________________________________________________________________________________________ TestModelLoading.test_minit _____________________________________________________________________________________________

self = <test_model_loading.TestModelLoading testMethod=test_minit>

    def test_minit(self):
        import torch.nn as nn
        import torch.nn.functional as F

        class MnistNet(nn.Module):
            def __init__(self):
                super(MnistNet, self).__init__()
                self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
                self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
                self.conv2_drop = nn.Dropout2d()
                self.fc1 = nn.Linear(320, 50)
                self.fc2 = nn.Linear(50, 10)

            def forward(self, x):
                x = F.relu(F.max_pool2d(self.conv1(x), 2))
                x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
                x = x.view(-1, 320)
                x = F.relu(self.fc1(x))
                x = F.dropout(x, training=self.training)
                x = self.fc2(x)
                return F.log_softmax(x, dim=1)

        pytorch_model = MnistNet()
        pytorch_model.train(mode=False)
>       self.compare_with_pytorch(pytorch_model, [(1, 1, 28, 28)])

../test/zoo/pipeline/onnx/test_model_loading.py:524:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../test/zoo/pipeline/utils/test_utils_onnx.py:82: in compare_with_pytorch
    self.assert_allclose(pytorch_out.detach().numpy(), zoutput, rtol, atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_model_loading.TestModelLoading testMethod=test_minit>
a = array([[-2.2302701, -2.3824017, -2.4050465, -2.337872 , -2.18691  ,
        -2.4104407, -2.3322508, -2.2063422, -2.2865396, -2.2774837]],
      dtype=float32)
b = array([[-2.2440107, -2.4308088, -2.4342618, -2.3394184, -2.1561582,
        -2.4115076, -2.3317592, -2.207847 , -2.2475662, -2.265396 ]],
      dtype=float32), rtol = 1e-06, atol = 1e-06, msg = None

    def assert_allclose(self, a, b, rtol=1e-6, atol=1e-6, msg=None):
        # from tensorflow
        self.assertEqual(a.shape, b.shape, "Shape mismatch: expected %s, got %s." %
                         (a.shape, b.shape))
        if not np.allclose(a, b, rtol=rtol, atol=atol):
            cond = np.logical_or(
                np.abs(a - b) > atol + rtol * np.abs(b), np.isnan(a) != np.isnan(b))
            if a.ndim:
                x = a[np.where(cond)]
                y = b[np.where(cond)]
                print("not close where = ", np.where(cond))
            else:
                # np.where is broken for scalars
                x, y = a, b
            print("not close lhs = ", x)
            print("not close rhs = ", y)
            print("not close dif = ", np.abs(x - y))
            print("not close tol = ", atol + rtol * np.abs(y))
            print("dtype = %s, shape = %s" % (a.dtype, a.shape))
>           np.testing.assert_allclose(a, b, rtol=rtol, atol=atol, err_msg=msg)
E           AssertionError:
E           Not equal to tolerance rtol=1e-06, atol=1e-06
E           None
E           (mismatch 100.0%)
E            x: array([[-2.23027 , -2.382402, -2.405046, -2.337872, -2.18691 , -2.410441,
E                   -2.332251, -2.206342, -2.28654 , -2.277484]], dtype=float32)
E            y: array([[-2.244011, -2.430809, -2.434262, -2.339418, -2.156158, -2.411508,
E                   -2.331759, -2.207847, -2.247566, -2.265396]], dtype=float32)

../test/zoo/pipeline/utils/test_utils.py:84: AssertionError
------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------
Creating an Onnx model: /tmp/tmptoVINb/a75f42d7f9c844dbb311f7bfeab0588e.onnx
creating: createZooKerasInput
creating: createZooKerasConvolution2D
creating: createZooKerasMaxPooling2D
creating: createZooKerasActivation
creating: createZooKerasConvolution2D
creating: createZooKerasMaxPooling2D
creating: createZooKerasActivation
creating: createRandomUniform
creating: createZooKerasParameter
creating: createZooKerasReshape
creating: createZooKerasDense
creating: createZooKerasActivation
creating: createZooKerasDropout
creating: createZooKerasDense
creating: createZooKerasActivation
creating: createZooKerasModel
not close where =  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
not close lhs =  [-2.2302701 -2.3824017 -2.4050465 -2.337872  -2.18691   -2.4104407
 -2.3322508 -2.2063422 -2.2865396 -2.2774837]
not close rhs =  [-2.2440107 -2.4308088 -2.4342618 -2.3394184 -2.1561582 -2.4115076
 -2.3317592 -2.207847  -2.2475662 -2.265396 ]
not close dif =  [0.01374054 0.04840708 0.02921534 0.00154638 0.03075171 0.00106692
 0.00049162 0.0015049  0.03897333 0.01208758]
not close tol =  [3.2440107e-06 3.4308086e-06 3.4342620e-06 3.3394185e-06 3.1561581e-06
 3.4115078e-06 3.3317592e-06 3.2078469e-06 3.2475664e-06 3.2653961e-06]
dtype = float32, shape = (1, 10)
_______________________________________________________________________________________ TestModelLoading.test_onnx_batch_norm1 _______________________________________________________________________________________

self = <test_model_loading.TestModelLoading testMethod=test_onnx_batch_norm1>

    def test_onnx_batch_norm1(self):
        pytorch_model = torch.nn.Sequential(
            torch.nn.BatchNorm2d(num_features=3, momentum=1, affine=False)
        )
        input_shape_with_batch = (1, 3, 224, 224)
>       self.compare_with_pytorch(pytorch_model, input_shape_with_batch, rtol=1e-3, atol=1e-3)

../test/zoo/pipeline/onnx/test_model_loading.py:80:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../test/zoo/pipeline/utils/test_utils_onnx.py:78: in compare_with_pytorch
    zmodel = OnnxLoader(onnx_model.graph).to_keras()
../zoo/pipeline/api/onnx/onnx_loader.py:110: in to_keras
    tensor = mapper.to_tensor()
../zoo/pipeline/api/onnx/mapper/operator_mapper.py:88: in to_tensor
    self.to_zoo_format(self.model_trainable_values))
../../zoo/target/bigdl_python/sources/bigdl/nn/layer.py:511: in set_weights
    tensors = [JTensor.from_ndarray(param, self.bigdl_type) for param in to_list(weights)]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'bigdl.util.common.JTensor'>, a_ndarray = <zoo.pipeline.api.autograd.Parameter object at 0x7fbbf028c250>, bigdl_type = 'float'

    @classmethod
    def from_ndarray(cls, a_ndarray, bigdl_type="float"):
        """
        Convert a ndarray to a DenseTensor which would be used in Java side.

        >>> import numpy as np
        >>> from bigdl.util.common import JTensor
        >>> from bigdl.util.common import callBigDlFunc
        >>> np.random.seed(123)
        >>> data = np.random.uniform(0, 1, (2, 3)).astype("float32")
        >>> result = JTensor.from_ndarray(data)
        >>> expected_storage = np.array([[0.69646919, 0.28613934, 0.22685145], [0.55131477, 0.71946895, 0.42310646]])
        >>> expected_shape = np.array([2, 3])
        >>> np.testing.assert_allclose(result.storage, expected_storage, rtol=1e-6, atol=1e-6)
        >>> np.testing.assert_allclose(result.shape, expected_shape)
        >>> data_back = result.to_ndarray()
        >>> (data == data_back).all()
        True
        >>> tensor1 = callBigDlFunc("float", "testTensor", JTensor.from_ndarray(data))  # noqa
        >>> array_from_tensor = tensor1.to_ndarray()
        >>> (array_from_tensor == data).all()
        True
        """
        if a_ndarray is None:
            return None
        assert isinstance(a_ndarray, np.ndarray), \
>           "input should be a np.ndarray, not %s" % type(a_ndarray)
E       AssertionError: input should be a np.ndarray, not <class 'zoo.pipeline.api.autograd.Parameter'>

../../zoo/target/bigdl_python/sources/bigdl/util/common.py:209: AssertionError
------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------
Creating an Onnx model: /tmp/tmpCwQXQC/b2722d7d8e84434c94d53b6be11e674e.onnx
creating: createRandomUniform
creating: createZooKerasParameter
creating: createRandomUniform
creating: createZooKerasParameter
creating: createZooKerasInput
creating: createZooKerasBatchNormalization
================================================================================================== warnings summary ==================================================================================================
test/zoo/pipeline/api/keras/test_net.py::TestLayer::test_load_keras
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/keras/models.py:150: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
    warnings.warn('No training configuration found in save file: '

test/zoo/pipeline/nnframes/test_nn_classifier.py::TestNNClassifer::test_nnEstimator_fit_nnmodel_transform
  /opt/work/spark-2.3.2/python/lib/pyspark.zip/pyspark/sql/dataframe.py:135: DeprecationWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
    "Deprecated in 2.0, use createOrReplaceTempView instead.", DeprecationWarning)

test/zoo/pipeline/nnframes/test_nn_classifier.py::TestNNClassifer::test_nnclassifier_fit_nnclassifiermodel_transform
  /opt/work/spark-2.3.2/python/lib/pyspark.zip/pyspark/sql/dataframe.py:135: DeprecationWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
    "Deprecated in 2.0, use createOrReplaceTempView instead.", DeprecationWarning)

test/zoo/pipeline/nnframes/test_nn_classifier.py::TestNNClassifer::test_nnclassifier_fit_with_Sigmoid
  /opt/work/spark-2.3.2/python/lib/pyspark.zip/pyspark/sql/dataframe.py:135: DeprecationWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
    "Deprecated in 2.0, use createOrReplaceTempView instead.", DeprecationWarning)

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_index_select_axis0
  /opt/work/analytics-zoo/pyzoo/test/zoo/pipeline/onnx/test_model_loading.py:662: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
    return torch.index_select(x, dim=self.dim, index=torch.tensor(self.index))

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_index_select
  /opt/work/analytics-zoo/pyzoo/test/zoo/pipeline/onnx/test_model_loading.py:646: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
    return torch.index_select(x, dim=self.dim, index=torch.tensor(self.index))

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_logsoftmax
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py:487: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
    result = self._slow_forward(*input, **kwargs)
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
    input = module(input)

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_softmax
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py:487: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
    result = self._slow_forward(*input, **kwargs)
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
    input = module(input)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================================================ 2 failed, 207 passed, 10 warnings in 184.67 seconds =================================================================================

**Comment by zhichao-li** [comment]
@Deliadd

**Comment by zhichao-li** [comment]
@glorysdj  would you mind providing the scripts for preparing the testing environment?

**Comment by glorysdj** [comment]
#py27
    conda create -y -n py27 python=2.7 mkdocs scipy pandas scikit-learn matplotlib seaborn jupyter && \
    conda install -y -n py27 plotly nltk twine pytest pytest-xdist h5py moviepy && \
    conda install -y -n py27 tensorflow==$TENSOR_FLOW_VERION keras==$KERAS_VERSION && \
    conda install -y -n py27 --channel https://conda.anaconda.org/menpo opencv3 && \
    conda install -y -n py27 typing protobuf numpy pyyaml mkl mkl-include setuptools cmake cffi && \
    conda install -y -n py27 -c mingfeima mkldnn && \
    conda install -y -n py27 -c conda-forge robotframework requests && \
    conda install -y -n py27 pytorch-cpu torchvision-cpu -c pytorch && \
    conda clean --all && \
    conda info --env
#ONNX
/bin/bash -c "source activate py27 && pip install onnx==1.3.0 && source deactivate"

**Comment by zhichao-li** [comment]
We need to fix the version:
```conda install -y -n py27 pytorch-cpu==1.0.0 torchvision-cpu -c pytorch 
pip install onnx==1.3.0 ```

**Comment by glorysdj** [comment]
fixed
