### ISSUE TITLE
UT failures for new Jenkins env

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#1017]
python env:
>>> import numpy
>>> numpy.__version__
'1.15.4'
>>> import onnx
>>> onnx.__version__
u'1.3.0'
>>> import torch
>>> torch.__version__
'1.0.0'
>>> import tensorflow
>>> tensorflow.__version__
'1.10.0'

errors:
link
http://10.239.47.211:18888/job/ZOO-PR-Python-Spark-1.6-py27/1523/console

=================================== FAILURES ===================================
_______________________ TestModelLoading.test_batch_norm _______________________

self = <test_model_loading.TestModelLoading testMethod=test_batch_norm>

    def test_batch_norm(self):
        x = np.array([[[[-1, 0, 1]], [[2, 3, 4]]]]).astype(np.float32).reshape((3, 2, 1, 1))
        s = np.array([1.0, 1.0]).astype(np.float32).reshape((2, 1))
        bias = np.array([0, 0]).astype(np.float32).reshape((2, 1))
        mean = np.array([0, 3]).astype(np.float32).reshape((2, 1))
        var = np.array([1, 1.5]).astype(np.float32).reshape((2, 1))
        y = self._batchnorm_test_mode(x, s, bias, mean, var).astype(np.float32)
    
        node = onnx.helper.make_node(
            'BatchNormalization',
            inputs=['x', 's', 'bias', 'mean', 'var'],
            outputs=['y'],
        )
>       output = OnnxLoader.run_node(node, [x, s, bias, mean, var])

../test/zoo/pipeline/onnx/test_model_loading.py:103: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../zoo/pipeline/api/onnx/onnx_loader.py:54: in run_node
    mapper = OperatorMapper.of(node, set(), inputs_list)
../zoo/pipeline/api/onnx/mapper/operator_mapper.py:46: in of
    return cls(node, _params, inputs)
../zoo/pipeline/api/onnx/mapper/batchnormalization.py:24: in __init__
    super(BatchNormalizationMapper, self).__init__(node, _params, _all_tensors)
../zoo/pipeline/api/onnx/mapper/operator_mapper.py:39: in __init__
    self.model_trainable_values = self._extract_trainable_values()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <zoo.pipeline.api.onnx.mapper.batchnormalization.BatchNormalizationMapper object at 0x7f30e07dfb50>

    def _extract_trainable_values(self):
        if len(self._input_list) == 5:
>           return [self._input_list[1].zvalue.get_weight(),
                    self._input_list[2].zvalue.get_weight()]
E           AttributeError: 'numpy.ndarray' object has no attribute 'get_weight'

../zoo/pipeline/api/onnx/mapper/batchnormalization.py:34: AttributeError
----------------------------- Captured stdout call -----------------------------
creating: createZooKerasInput
____________________ TestModelLoading.test_onnx_batch_norm2 ____________________

self = <test_model_loading.TestModelLoading testMethod=test_onnx_batch_norm2>

    def test_onnx_batch_norm2(self):
        pytorch_model = torch.nn.Sequential(
            torch.nn.BatchNorm2d(num_features=3, momentum=1, affine=True)
        )
        input_shape_with_batch = (1, 3, 224, 224)
>       self.compare_with_pytorch(pytorch_model, input_shape_with_batch, rtol=1e-3, atol=1e-3)

../test/zoo/pipeline/onnx/test_model_loading.py:88: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../test/zoo/pipeline/utils/test_utils_onnx.py:78: in compare_with_pytorch
    zmodel = OnnxLoader(onnx_model.graph).to_keras()
../zoo/pipeline/api/onnx/onnx_loader.py:103: in to_keras
    self.initializer, inputs)
../zoo/pipeline/api/onnx/mapper/operator_mapper.py:46: in of
    return cls(node, _params, inputs)
../zoo/pipeline/api/onnx/mapper/batchnormalization.py:24: in __init__
    super(BatchNormalizationMapper, self).__init__(node, _params, _all_tensors)
../zoo/pipeline/api/onnx/mapper/operator_mapper.py:39: in __init__
    self.model_trainable_values = self._extract_trainable_values()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <zoo.pipeline.api.onnx.mapper.batchnormalization.BatchNormalizationMapper object at 0x7f30e8480c50>

    def _extract_trainable_values(self):
        if len(self._input_list) == 5:
>           return [self._input_list[1].zvalue.get_weight(),
                    self._input_list[2].zvalue.get_weight()]
E           AttributeError: 'numpy.ndarray' object has no attribute 'get_weight'

../zoo/pipeline/api/onnx/mapper/batchnormalization.py:34: AttributeError
----------------------------- Captured stdout call -----------------------------
Creating an Onnx model: /tmp/tmpGtqR2s/0cac66b4b74f40d2a1194f231a654f57.onnx
creating: createZooKerasInput
=============================== warnings summary ===============================
test/zoo/pipeline/api/keras/test_net.py::TestLayer::test_load_keras
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/keras/models.py:150: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
    warnings.warn('No training configuration found in save file: '

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_index_select_axis0
  /opt/work/jenkins/workspace/ZOO-PR-Python-Spark-1.6-py27/pyzoo/test/zoo/pipeline/onnx/test_model_loading.py:662: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
    return torch.index_select(x, dim=self.dim, index=torch.tensor(self.index))

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_index_select
  /opt/work/jenkins/workspace/ZOO-PR-Python-Spark-1.6-py27/pyzoo/test/zoo/pipeline/onnx/test_model_loading.py:646: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
    return torch.index_select(x, dim=self.dim, index=torch.tensor(self.index))

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_logsoftmax
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py:487: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
    result = self._slow_forward(*input, **kwargs)
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
    input = module(input)

test/zoo/pipeline/onnx/test_model_loading.py::TestModelLoading::test_onnx_softmax
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py:487: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
    result = self._slow_forward(*input, **kwargs)
  /opt/work/conda/envs/py27/lib/python2.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
    input = module(input)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============== 2 failed, 207 passed, 7 warnings in 366.52 seconds ==============
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by Deliadd** [comment]
refer to PR https://github.com/intel-analytics/analytics-zoo/pull/1013

**Comment by glorysdj** [comment]
fixed
