### ISSUE TITLE
https://analytics-zoo.github.io isn't linking to the latest release

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1073]
https://analytics-zoo.github.io need to by default link to 0.3.0 now, but now it is master.

**Comment by helenlly** [comment]
done. 

update https://github.com/analytics-zoo/analytics-zoo.github.io/index.html
"
.....
 <meta http-equiv="refresh" content="0; url=./**0.3.0**" />

.....
"

**Comment by helenlly** [comment]
change " <meta http-equiv="refresh" content="0; url=./master" /> "
to         "<meta http-equiv="refresh" content="0; url=./0.3.0" />"

**Comment by helenlly** [comment]
change `<meta http-equiv="refresh" content="0; url=./master" _/>`
to `<meta http-equiv="refresh" content="0; url=./0.3.0" _/>`
