### ISSUE TITLE
cannot import name 'ConvLSTM3D'

### ISSUE THREAD

**Issue by qmiley** [intel-analytics/analytics-zoo#1163]
from zoo.pipeline.api.keras.layers.convolutional_recurrent import ConvLSTM3D

ImportError: cannot import name 'ConvLSTM3D'

**Comment by hkvision** [comment]
Hi @qmiley which analytics-zoo version are you using? ConvLSTM3D is newly added to master code not long ago, thus you may need to use the latest code instead of using pip.

**Comment by qmiley** [comment]
Thanks, I am using analytics-zoo 0.4.0. When can I install the latest code using pip?

**Comment by hkvision** [comment]
Hi @qmiley Sorry for the late reply. We will release the new pip version at the time when analytics-zoo 0.5.0 is ready. If you want to use it now I can send you a package or give you instructions to build the package by yourself. :)

**Comment by hkvision** [comment]
We will release 0.5.0 very soon and you can use the latest release to import ConvLSTM3D using pip.
Close this issue now.
