### ISSUE TITLE
Keras-style CNN input_shape not consistent with Keras

### ISSUE THREAD

**Issue by Litchilitchy** [intel-analytics/analytics-zoo#1171]
Suppose we are taking 4-d tensor as input of CNN

In Keras the order is `(sample, height, width, channel)`

Currently in zoo Keras-style code it is `(sample, channel, height, width)`

which is not consistent

**Comment by hkvision** [comment]
Keras default is dim_ordering='tf' (sample, height, width, channel), you can add this option in Conv2D to have the same format with Keras.

**Comment by Litchilitchy** [comment]
OK then I would just add a additional parameter `dim_ordering="tf"` to keep the original result without reshaping the dataset
