### ISSUE TITLE
Can we check existing file before download a 50MB file NervanaSystems/nlp-architect/v0.3.1.zip?

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#1236]
As my network is not very fast, each build need to download a 50MB zip file, this downloading will cost a lots of time.
Can we just check the zip file's checksum, rather than download a new one if the zip file exists?

```
Fetching nlp-architect 0.3.1
Running: wget https://github.com/NervanaSystems/nlp-architect/archive/v0.3.1.zip -P /home/xin/IntelAnalytics/analytics-zoo4/zoo/target/python
--2019-03-21 11:11:32--  https://github.com/NervanaSystems/nlp-architect/archive/v0.3.1.zip
Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.100
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.100|:913... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/NervanaSystems/nlp-architect/zip/v0.3.1 [following]
--2019-03-21 11:11:34--  https://codeload.github.com/NervanaSystems/nlp-architect/zip/v0.3.1
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.100|:913... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘/home/xin/IntelAnalytics/analytics-zoo4/zoo/target/python/v0.3.1.zip’
```

**Comment by qiuxin2012** [comment]
` analytics-zoo/scripts/get_python_packages` should be ` analytics-zoo/scripts/get_python_packages.sh` ?

**Comment by yangw1234** [comment]
+1 especially outside of company network

**Comment by hkvision** [comment]
Checked today that the downloaded packaged will be placed under `analytics-zoo/zoo/target`, and this folder will be removed and regenerated when `make_dist`. So currently checking checksum won't work since everything will be removed anyway.
To solve this, do you have a suggestion anywhere to put the downloaded files?

**Comment by qiuxin2012** [comment]
Download to `/tmp` folder first?
