### ISSUE TITLE
convert_variables_to_constants failing on AssignVariableOp/Switch 

### ISSUE THREAD

**Issue by eyaler** [intel-analytics/analytics-zoo#1271]
i am trying to use tf_graph_util/convert_variables_to_constants but get an error:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node import/module_apply_default/cond/AssignVariableOp was passed float from import/module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/python/biggan/issue2.py", line 19, in <module>
    tf.import_graph_def(gd)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node import/module_apply_default/cond/AssignVariableOp was passed float from import/module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.

Process finished with exit code 1
```

code to recreate
```
import tensorflow as tf
import tensorflow_hub as hub
import os
from tf_graph_util import convert_variables_to_constants

with tf.Session() as sess:
    module = hub.Module('https://tfhub.dev/deepmind/biggan-128/2')
    sess.run(tf.global_variables_initializer())
    inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k) for k, v in module.get_input_info_dict().items()}
    output = module(inputs)
    converted_graph_def = convert_variables_to_constants(sess, sess.graph_def, [output.name.replace(':0','')])
    tf.train.write_graph(converted_graph_def, 'c:/temp/saved1', 'frozen_model.pb', as_text=False)

tf.reset_default_graph()
with tf.Session() as sess:
    with tf.gfile.GFile(os.path.join('c:/temp/saved1', 'frozen_model.pb'), 'rb') as f:
        gd = sess.graph_def
        gd.ParseFromString(f.read())
        tf.import_graph_def(gd)
```

**Comment by jason-dai** [comment]
@yangw1234

**Comment by yangw1234** [comment]
Hi @eyaler AssignVariableOp in a frozen graph does not make any sense since all variables are converted to constant.

You can try the following code, which will strip all unnecessary nodes in your graph. And in my case, it generate a pic like this.

![biggan](https://user-images.githubusercontent.com/10561966/56012936-222a1d00-5d21-11e9-9795-2a0382fb48c0.jpg)

I think it is working.

```python
import tensorflow as tf
import tensorflow_hub as hub
import os
import numpy as np
from cv2 import cv2

from zoo.util.tf import export_tf

def gallery(array, ncols=4):
    nindex, height, width, intensity = array.shape
    nrows = nindex//ncols
    assert nindex == nrows*ncols
    # want result.shape = (height*nrows, width*ncols, intensity)
    result = (array.reshape(nrows, ncols, height, width, intensity)
              .swapaxes(1,2)
              .reshape(height*nrows, width*ncols, intensity))
    return result

with tf.Session() as sess:
    module = hub.Module('/tmp/biggan')
    sess.run(tf.global_variables_initializer())
    inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k) for k, v in module.get_input_info_dict().items()}
    output = module(inputs)
    output_name = output.name
    export_tf(sess, "/tmp/saved1/", inputs=[inputs["y"], inputs["z"], inputs["truncation"]], outputs=[output])


tf.reset_default_graph()
with tf.Session() as sess:
    with tf.gfile.GFile(os.path.join('/tmp/saved1/', 'frozen_inference_graph.pb'), 'rb') as f:
        gd = sess.graph_def
        gd.ParseFromString(f.read())
        tf.import_graph_def(gd, name="")
    y_idx = np.random.randint(0, 1000, size=[4])
    y = np.zeros([4, 1000])
    y[np.arange(4), y_idx] = 1
    z = np.random.randn(4, 120) * 0.5
    truncation = 0.5
    ims = sess.run("module_apply_default/G_trunc_output:0", feed_dict={"y:0":y, "z:0":z, "truncation:0": truncation})
    ims = np.clip(((ims + 1) / 2.0) * 256, 0, 255)
    ims = np.uint8(ims)

    cv2.imwrite("./biggan.jpg", gallery(ims))
```

**Comment by yangw1234** [comment]
I'll close it first. Please reopen it if this is still an issue.

**Comment by eyaler** [comment]
@yangw1234 thanks!

i tried using export_tf from your original answer and while it worked for 'https://tfhub.dev/deepmind/biggan-128/2', it fails for e.g. 'https://tfhub.dev/deepmind/biggan-deep-512/1' with error: 

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node module_apply_default/cond/AssignVariableOp/Switch was passed float from module/prev_truncation:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/python/biggan/issue2.py", line 18, in <module>
    tf.import_graph_def(gd, name='')
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node module_apply_default/cond/AssignVariableOp/Switch was passed float from module/prev_truncation:0 incompatible with expected resource.

Process finished with exit code 1


can you reopen this?

**Comment by yangw1234** [comment]
@eyaler are you using the latest master?

**Comment by eyaler** [comment]
@yangw1234 
yes. and i verifed it works for biggan-128/2, but failed for e.g. biggan-deep-512/1

**Comment by yangw1234** [comment]
The problem seems to be that you the model output depends on a AssignVariableOp, which cannot run on a frozen graph. 

I'll reopen the issue to keep track of the problem but I currently cannot think of a easy way to fix that in our code.

One possible approach to work around this is to use the `variable_names_blacklist` arguments in  `convert_variables_to_constants` to prevent freezing those variables that will be assigned. I suggest you to try that.
