### ISSUE TITLE
Model with `Parameter` cannot be correctly save/load

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#1272]
It can be reproed by 

   `val w = Parameter[Float](Shape(1, 10),
      initWeight = Tensor.ones[Float](10).view(1, 10))
    val b = Parameter[Float](Shape(1, 10),
      initWeight = Tensor[Float](10).view(1, 10))
    val x = Variable[Float](Shape(1, 10))
    val z = x * w + b
    val model = Model[Float](input = x, output = z)
    val input2 = Tensor[Float](Array(1, 10)).rand
    val tt = model.forward(input2.clone())

    model.saveModule("/tmp/test.model", overWrite = true)
    val model2 = Module.loadModule[Float]("/tmp/test.model")
    val output2 = model2.forward(input2)`

We will see `Parameter` from loaded `model2` is not right and there is exception if we run `model2.forward`. Have tried to override `doSerializeModule` and `doLoadModule` in `InternalParameter` and `Parameter`, however it doesn't work, the override method is not used.

**Comment by dding3** [comment]
cc @zhichao-li , any thoughts?

**Comment by zhichao-li** [comment]
I guess you need to register the serializer to make that work.  A reference:`Topology.scala` 
```
ModuleSerializer.registerModule(.....)
```

**Comment by dding3** [comment]
Tried that, still doesn't work

**Comment by dding3** [comment]
Fixed
