### ISSUE TITLE
Keras-style API model load/save issue for resume training

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#1277]
1. Neither of ```save``` or ```saveModel``` work with ```Net.load```
     *  ```model.save``` + ```Net.load``` will lead to NullPointerException from bigdl.utils.serializer.ModuleLoader. The error message does not make any sense to the user. 
     *  save a model using```model.saveModel``` and then load model using ```Net.load```, then call ```model.fit``` will lead to an error says "'ZooKerasLayer' object has no attribute 'fit'"

1. We should add test case and example for resume training as it's a very common request from customers.  Also, model ```save``` and ```saveModel``` has no clear documents and user don't know which they should use. It easily cause confusion. We may just keep one of them.

**Comment by shane-huang** [comment]
related to issue #1004

**Comment by zhichao-li** [comment]
Any example code for reproducing this?
I tried with the following snippet, and it works fine:
```
  input = ZLayer.Input(shape=(5,))
        output = ZLayer.Dense(10)(input)
        zmodel = ZModel(input, output, name="graph1")
        tmp_path = "/tmp/aaa" 
        # zmodel.saveModel(tmp_path, None, True)
        model_reloaded = Net.load(tmp_path)
```

**Comment by hkvision** [comment]
Probably Net.load in Python doesn't gives an instance of KerasNet and thus can't call fit?

**Comment by hkvision** [comment]
Emmm... Just checked that Net.load returns a KerasNet and should have fit method...

**Comment by zhichao-li** [comment]
fixed.
