### ISSUE TITLE
no main class set in JAR

### ISSUE THREAD

**Issue by jackhts4** [intel-analytics/analytics-zoo#1292]
I am running
`PYSPARK_PYTHON=${VENV_HOME}/venv.zip/venv/bin/python ${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=${ANALYTICS_ZOO_HOME}/venv.zip/venv/bin/python \
    --master yarn-cluster \
    --archives ${VENV_HOME}/venv.zip \
    dmeo.py`
and it appear
'Error: No main class set in JAR; please specify one with --class'

The demo.py is able to run under anaconda in python 3.7.3
and for the venv.zip file, I am following tutorial in https://analytics-zoo.github.io/master/#PythonUserGuide/install/#for-yarn-cluster

Please help, thank you
typo of spark.yarn.appMasterEnv.PYSPARK_PYTHON=${ANALYTICS_ZOO_HOME}, should be ${VENV_HOME}

**Comment by hkvision** [comment]
Hi, is the following correct?
```
--conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=${ANALYTICS_ZOO_HOME}/venv.zip/venv/bin/python 
```
since venv.zip is not under ${ANALYTICS_ZOO_HOME}

**Comment by jackhts4** [comment]
oh, sorry I am just copying the wrong code here,
even i am running
`--conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=${VENV_HOME}/venv.zip/venv/bin/python`
it is not working

**Comment by hkvision** [comment]
Can you try `--conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=venv.zip/venv/bin/python`?

**Comment by jackhts4** [comment]
I have tried this too but it is not working

**Comment by hkvision** [comment]
Hi @jackhts4 sorry for the reply. I tried and could successfully run our [text_classification](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/textclassification/text_classification.py) example using the script and commands. Could you please double check the following steps:
1. Set `SPARK_HOME`.
2. Set `ANALYTICS_ZOO_HOME` correctly. (If you download the pre-built package, it should be the dir after unzipping it.)
3. Run ${ANALYTICS_ZOO_HOME}/bin/python_package.sh to generate venv.zip. This will be placed under the current directory. Set the current dir to be `VENV_HOME`
4. Run the following command for an example:
```
PYSPARK_PYTHON=${VENV_HOME}/venv.zip/venv/bin/python ${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=venv.zip/venv/bin/python \
    --master yarn-cluster \
    --executor-memory 2g \
    --driver-memory 2g \
    --executor-cores 16 \
    --num-executors 2 \
    --archives ${VENV_HOME}/venv.zip \
    text_classification.py ...(args omitted)
```

**Comment by hkvision** [comment]
If you still have problems you can first use the script to run in local mode (master=local[*]) to have a try. Or you can provide more details so that we can help you to figure our the problem.

**Comment by hkvision** [comment]
Has this problem got resolved?

**Comment by hkvision** [comment]
Close this issue first. Feel free to reopen it if you still encounter problems. Thanks.
