### ISSUE TITLE
with pyspark getting no module named bigdl

### ISSUE THREAD

**Issue by tarunnar** [intel-analytics/analytics-zoo#1298]
I had installed analytics-zoo using pip3 install analytics-zoo 
I had unsetted the SPARK_HOME. 
in python3 console I am able to import zoo and import bigdl but while fitting the model I am getting no module named bigdl. 
Any help is appreciated
`model.fit(train_data_X_reshaped,train_data_Y,batch_size=60,nb_epoch=10)
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-82-01f6292613b4> in <module>()
----> 1 model.fit(train_data_X_reshaped,train_data_Y,batch_size=60,nb_epoch=1000)

~/anaconda3/lib/python3.6/site-packages/zoo/pipeline/api/keras/engine/topology.py in fit(self, x, y, batch_size, nb_epoch, validation_data, distributed)
    161                           batch_size,
    162                           nb_epoch,
--> 163                           validation_data)
    164         else:
    165             if validation_data:

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    586             error = e
    587             if "does not exist" not in str(e):
--> 588                 raise e
    589         else:
    590             return result

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    582         try:
    583             api = getattr(jinvoker, name)
--> 584             result = callJavaFunc(api, *args)
    585         except Exception as e:
    586             error = e

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callJavaFunc(func, *args)
    631     gateway = _get_gateway()
    632     args = [_py2java(gateway, a) for a in args]
--> 633     result = func(*args)
    634     return _java2py(gateway, result)
    635 

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o33.zooFit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 24.0 failed 1 times, most recent failure: Lost task 3.0 in stage 24.0 (TID 835, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 217, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 59, in read_command
    command = serializer._read_with_length(file)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 170, in _read_with_length
    return self.loads(obj)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 559, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'bigdl'

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:298)`

**Comment by hkvision** [comment]
Hi are you running in local mode? Can you provide more code segment for us to help reproduce and figure out the problem?
At the same time, can you try running some of our examples after pip install? For instance, this very simple one: https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/autograd#run-after-pip-install

**Comment by hkvision** [comment]
I noticed in your error log: `/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py` Seems the worker is not running `~/anaconda3/lib/python3.6`?
Probably you can do something like:
```
export PYSPARK_PYTHON=~/anaconda3/lib/python3.6
export PYSPARK_DRIVER_PYTHON=~/anaconda3/lib/python3.6
```

**Comment by tarunnar** [comment]
Hi yes I am running in local mode and I am using 
export PYSPARK_PYTHON=~/anaconda3/lib/python3.6
export PYSPARK_DRIVER_PYTHON=~/anaconda3/lib/python3.6
even after that I am getting same error  No module named 'bigdl' I had installed bigdl using pip3 
Requirement already satisfied: bigdl in ./anaconda3/lib/python3.6/site-packages (0.7.2)
Requirement already satisfied: six>=1.10.0 in ./.local/lib/python3.6/site-packages (from bigdl) (1.12.0)

**Comment by hkvision** [comment]
How are you running your code? Are you using for example `python train.py`? Or you can provide some more code/env/command info for us to repro the error.

**Comment by tarunnar** [comment]
HI I am running the code using jupyter notebook.
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PATH=$JAVA_HOME/bin:$PATH
export SPARK_HOME=/usr/local/spark
export PATH=$PATH:$SPARK_HOME/bin
export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.7-src.zip:$SPARK_HOME/python/lib/pyspark.zip:$PYTHONPATH
export PATH=$SPARK_HOME/python:$PATH
export JAVA_OPTS="-Xms128m -Xmx4000m"
export PYSPARK_PYTHON=/home/qolsys/anaconda3/bin/python3.6
export PYSPARK_DRIVER_PYTHON=/home/qolsys/anaconda3/bin/python3.6
If you need some more code part please tell me

**Comment by tarunnar** [comment]
I have checked that 
```
import sys
sys.executable
```
'~/anaconda3/bin/python'

```sys.path ```
'/usr/local/spark/python',
 '/usr/local/spark/python/lib/py4j-0.10.7-src.zip',
 '/usr/local/spark/python/lib/pyspark.zip',
 '~/Documents/jupyter_notebooks/spark_deeplearning',
 '~/anaconda3/lib/python36.zip',
 '~/anaconda3/lib/python3.6',
 '~/anaconda3/lib/python3.6/lib-dynload',
 '~/.local/lib/python3.6/site-packages',
 '~/anaconda3/lib/python3.6/site-packages',
 '~/anaconda3/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg',
 '~/anaconda3/lib/python3.6/site-packages/face_recognition-1.2.3-py3.6.egg',
 '~/anaconda3/lib/python3.6/site-packages/dlib-19.16.0-py3.6-linux-x86_64.egg',
 '~/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '~/.ipython'

seems python used in jupyter notebook is ~/anaconda3/bin/python not know how to configure python version(python path(/)) in jupyter notebook

**Comment by tarunnar** [comment]
Hi I   have replaced the directory in spark home with spark 2.4.2
Now I have installed bigdl in virtualenv and launching jupyter notebook within that env so now 
sys.executable 
'~/anaconda3/bin/python3'
sys.path
 ```''',
 '/usr/local/spark/python',
 '/usr/local/spark/python/lib/py4j-0.10.7-src.zip',
 '/usr/local/spark/python/lib/pyspark.zip',
 '~/Documents/jupyter_notebooks/spark_deeplearning/sparkdlenv/codes',
 '~/anaconda3/lib/python36.zip',
 '~/anaconda3/lib/python3.6',
 '~/anaconda3/lib/python3.6/lib-dynload',
 '~/.local/lib/python3.6/site-packages',
 '~/anaconda3/lib/python3.6/site-packages',
 '~/anaconda3/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg',
 '~/anaconda3/lib/python3.6/site-packages/face_recognition-1.2.3-py3.6.egg',
 '~/anaconda3/lib/python3.6/site-packages/dlib-19.16.0-py3.6-linux-x86_64.egg',
 '~/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '~/.ipython''```
from zoo.common.nncontext import init_nncontext
sc = init_nncontext("LSTM_sensor_life")
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-4-0453615a5aa3> in <module>()
      1 # Create a SparkContext and initialize the BigDL engine.
----> 2 sc = init_nncontext("LSTM_sensor_life")

~/anaconda3/lib/python3.6/site-packages/zoo/common/nncontext.py in init_nncontext(conf)
     37     redire_spark_logs()
     38     show_bigdl_info_logs()
---> 39     init_engine()
     40     return sc
     41 

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in init_engine(bigdl_type)
    415 
    416 def init_engine(bigdl_type="float"):
--> 417     callBigDlFunc(bigdl_type, "initEngine")
    418     # Spark context is supposed to have been created when init_engine is called
    419     get_spark_context()._jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.initialize()

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    586             error = e
    587             if "does not exist" not in str(e):
--> 588                 raise e
    589         else:
    590             return result

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    582         try:
    583             api = getattr(jinvoker, name)
--> 584             result = callJavaFunc(api, *args)
    585         except Exception as e:
    586             error = e

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in callJavaFunc(func, *args)
    631     gateway = _get_gateway()
    632     args = [_py2java(gateway, a) for a in args]
--> 633     result = func(*args)
    634     return _java2py(gateway, result)
    635 

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o31.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.intel.analytics.bigdl.utils.MklBlas$.<init>(Engine.scala:37)

**Comment by tarunnar** [comment]
Hi replaced the directory in spark home with spark 2.3.3
Now it works now I am not getting the previous issue able to fit the model

**Comment by hkvision** [comment]
Hi, @tarunnar 
`java.lang.NoClassDefFoundError: scala/Product$class` This error is caused by the incompatible spark versions. By default, if you install analytics zoo 0.4.0, it is built against spark 2.3 and now you are using 2.4.2.

**Comment by hkvision** [comment]
BTW, if you are using pip, you don't need to set anything related to `SPARK_HOME` or `PYTHONPATH`, we will prepare the python env for you automatically.
You just need to make sure you have installed `pyspark==2.3.2` and `bigdl==0.7.2` in the environment.

**Comment by tarunnar** [comment]
HI @hkvision 
where can i find in analytics-zoo my spark_home? Where I can find spark installed by analytics-zoo.
where configurations related to spark resides in analytics zoo.
I have replaced spark_home directory with spark 2.3.3 now my job is working fine. 
If I am launching my Jupiter notebook within the virtual environment in which I have installed analytics zoo without unsetting the earlier ```SPARK_HOME=/usr/local/spark``` configurations
I will try to unset the SPARK_HOME in my system then I will try if my job is working or not.
should I remove any earlier configurations related to spark

**Comment by hkvision** [comment]
If you are using pip, we use `pyspark` and thus SPARK_HOME is not needed. You can set more configurations for spark when you init spark context. You can refer to our documentation for more instructions: https://analytics-zoo.github.io/0.4.0/#PythonUserGuide/install/#install-from-pip
https://analytics-zoo.github.io/0.4.0/#PythonUserGuide/run/#run-after-pip-install
