### ISSUE TITLE
How to set the parameters for Object Detection and Image Classification to boost inference, using 8 nodes costs the same time as 1 node.

### ISSUE THREAD

**Issue by qchen119** [intel-analytics/analytics-zoo#1299]
Dear every one,

I am new to analytics-zoo. I have 8 nodes each with 64G, 2 X E5-2630v3, 1Gbps ethernet. When I test the image classification code provided by Intel, it is slower than Caffe. And also when I use 6 nodes to inference the model, the computing time is the same as one node, sometimes it is slower than 1 node. 

I downloaded 5000 images from [coco2017 val dataset](http://images.cocodataset.org/zips/val2017.zip), by using 6 nodes to inference these images with /analytics-zoo_mobilenet-v2_imagenet_0.1.0.model, it cost 5 minutes. If using 1 node, it also cost near 5 minutes.

Can anyone help me to find out what's the problem, why using spark cluster cannot accelerate the inference? Why the analytics zoo is slower than running Caffe directly on the local machine? 

Here is my command to run this task.
# spark version :2.1.1.2.6.1.0-129
#python 2.7.12

#15:10 2019/4/28 mobilenet-v2 6 nodes with 12 executor-cores each，5 min 24s
#15:28 2019/4/28 mobilenet-v2  1 node with 12 executor-core each，5 min 17s

export SPARK_MAJOR_VERSION=2
export SPARK_HOME=/usr/hdp/2.6.1.0-129/spark2
export ANALYTICS_ZOO_HOME=/home/ubuntu/analytics_zoo

export VENV_HOME=/home/ubuntu/analytics_zoo

modelPath=hdfs://HA/user/ubuntu/caffe/analytics-zoo_mobilenet-v2_imagenet_0.1.0.model
imagePath=hdfs://HA/user/ubuntu/caffe/ssd/images/
topN=5
partitionNum=1

PYSPARK_DRIVER_PYTHON=${VENV_HOME}/venv/bin/python PYSPARK_PYTHON=venv.zip/venv/bin/python ${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
     --master yarn \
    --deploy-mode client \
    --executor-memory 24g \
    --driver-memory 10g \
    --executor-cores 12 \
    --num-executors 6 \
--archives ${VENV_HOME}/venv.zip \
    predict.py -f $imagePath --model $modelPath --topN 5 --partition_num ${partitionNum}

**Comment by jason-dai** [comment]
@jenniew please take a look

**Comment by jenniew** [comment]
In Spark 2.1-2.3, the minPartitions argument of binaryFiles() is ignored. So only one executor is running. You can change "spark.files.maxPartitionBytes"  when submitting job, to get more partitions to distribute data to multiple executors.

**Comment by qchen119** [comment]
> In Spark 2.1-2.3, the minPartitions argument of binaryFiles() is ignored. So only one executor is running. You can change "spark.files.maxPartitionBytes" when submitting job, to get more partitions to distribute data to multiple executors.

Thank you for your reply.
Now I run the code as 
modelPath=hdfs://HA/user/ubuntu/caffe/analytics-zoo_mobilenet-v2_imagenet_0.1.0.model
PYSPARK_DRIVER_PYTHON=${VENV_HOME}/venv/bin/python
PYSPARK_PYTHON=venv.zip/venv/bin/python
${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=venv.zip/venv/bin/python \
    --master yarn-cluster \
    **--conf spark.default.parallelism=6 \
    --conf spark.files.maxPartitionBytes=11048576 \**
    --executor-memory 24g \
    --driver-memory 10g \
    --executor-cores 10 \
    --num-executors 6 \
    --archives ${VENV_HOME}/venv.zip \
    predict.py -f $imagePath --model $modelPath --topN 5 --partition_num ${partitionNum}

The execution time is **3 mins 48s, it is better than before**. The major change is the 
--conf spark.files.maxPartitionBytes=11048576 (~10M, the default is 128M)

When I am testing analytics-zoo_vgg-16_imagenet_0.1.0.model by using the same code and running command, **it just cost 5 mins, but if I do not change the maxPartitionBytes, it will cost 16 mins**.

So, I think change **the size of maxPartitionBytes is works for my cluster on image classification code.**

Thank you!, @jason-dai @jenniew
