### ISSUE TITLE
Release Page link in the python user guide not point release page

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/analytics-zoo#1366]
In https://analytics-zoo.github.io/master/#PythonUserGuide/install/, the "Release Page" link actually links to Analytics Zoo overview page, not the Release page.

**Comment by hkvision** [comment]
The link is correct: https://analytics-zoo.github.io/master/#release-download/
Now sure why when clicking into it, there is an extra ##release-download.

**Comment by hkvision** [comment]
Fixed, please take a look: https://analytics-zoo.github.io/master/#PythonUserGuide/install/
