### ISSUE TITLE
analytics-zoo/apps/variational-autoencoder/using_variational_autoencoder_to_generate_faces.ipynb extract too many files

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#1397]
#download the data CelebA, and may repalce with your own data path
DATA_PATH = os.getenv("ANALYTICS_ZOO_HOME") + "/apps/variational-autoencoder/img_align_celeba"

this cause no space left issue quickly.

root@Gondolin-Node-034:~# df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
udev           33002648     555 33002093    1% /dev
tmpfs          33005341     736 33004605    1% /run
/dev/sda2      30081024 1705793 28375231    6% /
none           33005341      13 33005328    1% /sys/fs/cgroup
none           33005341       1 33005340    1% /run/lock
none           33005341      22 33005319    1% /run/shm
none           33005341       3 33005338    1% /run/user
/dev/sdb1        953984  557671   396313   59% /disk1
/dev/sdc1        953984  568960   385024   60% /disk2
/dev/sdd1        953984  953984        0  100% /disk3
/dev/sde1        953984  953984        0  100% /disk4
/dev/sdf1        953984  626819   327165   66% /disk5
/dev/sdg1        953984  953984        0  100% /disk6

Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Pip-Apps-Integration-Part1/dist/apps/variational-autoencoder/using_variational_autoencoder_to_generate_faces.py", line 218, in <module>
    os.makedirs("./images")
  File "/opt/work/conda/envs/py27/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './images'

http://10.239.47.211:18888/view/ZOO-NB/job/ZOO-NB-Pip-Apps-Integration-Part1/5/console

http://10.239.47.211:18888/view/ZOO-NB/job/ZOO-NB-Pip-Apps-Integration-Part1/ws/dist/apps/variational-autoencoder/img_align_celeba/

**Comment by yangw1234** [comment]
why it works previously

**Comment by yangw1234** [comment]
is there a machnism to clean up the data in previous run?

**Comment by yangw1234** [comment]
replace it with a 30M zip

**Comment by yangw1234** [comment]
confirm file size has been reduced
