### ISSUE TITLE
pyzoo/docs/doc-gen.sh issue

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#1416]
in this sh, it requires to update Sphinx version, but the latest Sphinx requires Python '>=3.5' but the running Python is 2.7.15 because of the doc gen python is written in py27.

isSphinxInstalled=$(pip show Sphinx &>/dev/null; echo $?)
if [ ! $isSphinxInstalled -eq 0 ]; then
 pip install -U Sphinx
fi

http://10.239.47.211:18888/view/ZOO-Release/job/Zoo-Doc-Release/174/console

**Comment by helenlly** [comment]
fixed by updating Sphinx version in Jenkins job "Zoo-Doc-Release" ->Build ->execute shell :
.....
conda list
pip install mkdocs==0.16.3
pip install Sphinx==1.8.4
.....
