### ISSUE TITLE
Can callBigDlFunc in Python api be optimized?

### ISSUE THREAD

**Issue by Litchilitchy** [intel-analytics/analytics-zoo#1425]
In `callBigDlFunc` we have 

            try:
                api = getattr(jinvoker, name)
                result = callJavaFunc(api, *args)
            except Exception as e:
                error = e
                if "does not exist" not in str(e):
                    raise e
            else:
                return result

However before raise error, first we try `callJavaFunc`, which has expensive data conversion `_py2java`, specifically,

    def callJavaFunc(func, *args):
        """ Call Java Function """
        gateway = _get_gateway()
        args = [_py2java(gateway, a) for a in args] // this is expensive
        result = func(*args)
        return _java2py(gateway, result)

 (`_get_gateway()` would get a list of api, and `callBigDlFunc` tries them one by one), the specific code is

    JavaCreator.set_creator_class([])
    JavaCreator.add_creator_class("com.intel.analytics.zoo.pipeline.nnframes.python.PythonNNFrames")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.feature.python.PythonImageFeature")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.pipeline.api.keras.python.PythonAutoGrad")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.models.python.PythonZooModel")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.pipeline.api.keras.python.PythonZooKeras2")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.feature.python.PythonTextFeature")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.feature.python.PythonFeatureSet")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.pipeline.api.net.python.PythonZooNet")
    JavaCreator.add_creator_class("com.intel.analytics.zoo.pipeline.inference.PythonInferenceModel")
    for clz in creator_classes:
        JavaCreator.add_creator_class(clz)

 If the error in `callBigDlFunc` is raised, the data conversion is in vain. Could we avoid the unnecessary time cost? @zhichao-li @jason-dai 

Could kindly help to check @qiyuangong 

PS: the above 2 pieces of code is BigDl code

**Comment by qiuxin2012** [comment]
I meet the same issue.
I add a new CLASS to last of creator list(10th), the callBigDlFunc will cost 4.2s. If I put the Class to 1st place, only cost 0.4s. If 4th place,  cost about 1.8s...

**Comment by qiuxin2012** [comment]
move `args = [_py2java(gateway, a) for a in args] // this is expensive` to callBigDlFunc can solve this problem.

**Comment by yangw1234** [comment]
Is it possible to dynamically construct a map, whose key is the method name and argument types and value the corresponding object. Thus we use one call to look up the object.

**Comment by Litchilitchy** [comment]
@qiuxin2012 has killed this issue

In old code, `args = [_py2java(gateway, a) for a in args]` has to be done in one of the `try` method (the other former `try` would fail) anyway, by just moving it to the begin of those `try` methods could solve this issue
