### ISSUE TITLE
Add a script to build master python local whl

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#1447]
When customer asks for new functionalities or hot fixes for python package,  we have to let them wait till nightly build finished and send them the .whl to install locally. Why not provide a script for users to build whl (or allow them to local install) themselves after pulling down the master? 

We do have a release.sh script but it will automatically upload to PyPI. We can make it multi purpose. Also a separate "Developer Guide"  in doc site would be useful for external contributors.

**Comment by hkvision** [comment]
release.sh will not only upload to pypi, but also create a whl file locally. Users are free to build by themselves.

**Comment by shane-huang** [comment]
For most python-only users, they way they are familiar to build a
