### ISSUE TITLE
Support of fine tuning inceptionV3

### ISSUE THREAD

**Issue by YoungXueya** [intel-analytics/analytics-zoo#1513]
I tried to fine-tuning inceptionv3 on my own dataset using keras-style API, but I failed at finding the node of the inceptionV3 using the model provided by Analytics-zoo.

```
model_path="hdfs:///model/analytics-zoo_inception-v3_imagenet_0.1.0.model"
full_model = Net.load_bigdl(model_path)
    # create a new model by remove layers after pool5/drop_7x7_s1
model = full_model.new_graph([""pool_8x8_s1_drop""])
```
I found the layer name in the model, like that in the v1. But got error:```

```
py4j.protocol.Py4JJavaError: An error occurred while calling o52.newGraph.
: java.util.NoSuchElementException: Can not find node with name pool_8x8_s1_drop
        at com.intel.analytics.bigdl.nn.Graph.node(Graph.scala:137)
```

Could someone tell me is fine-tuning of inceptionV3 supported? If so, where could I find the name of layers?

Thanks a lot!

**Comment by hkvision** [comment]
Hi, I think it should be supported.
To find all the layer names, you can do something like:
```
for layer in full_model.layers:
    print (layer.name())
```
You may find in this notebook for something similar: https://github.com/intel-analytics/analytics-zoo/blob/master/apps/dogs-vs-cats/transfer-learning.ipynb
Feel free to tell us if you have further problems. Thanks.

**Comment by YoungXueya** [comment]
@hkvision I just tried your method, but only got:
```
 for layer in full_model.layers:
...     print (layer.name())
...
Inputb5080927
analytics-zoo_inception-v3_imagenet_0.1.0
```
...

**Comment by jason-dai** [comment]
@jenniew please take a look

**Comment by hkvision** [comment]
Hi @YoungXueya Sorry that there's some problem with our released inception-v3 model. We will fix it and release a new one as soon as possible. Could you first try fine-tuning on other models such as inception-v1 or resnet-50? I tried these models and you can successfully get the names of the layers and then apply transfer learning. After we update our inception-v3 model, I think it should be really easy for you to swift to fine-tuning inception-v3.

**Comment by hkvision** [comment]
Hi, @YoungXueya We have updated the inveption-v3 model, you can download it [here](https://analytics-zoo-models.s3-ap-southeast-1.amazonaws.com/analytics-zoo_inception-v3_imagenet_0.1.0.model ). Feel free to tell us if there are further problems.

**Comment by YoungXueya** [comment]
Yes! It works now. Thanks a lot for your help!

**Comment by hkvision** [comment]
@YoungXueya You are welcome :)
