### ISSUE TITLE
Error "partitionNum should be larger than 0, but get 0" when running imageclassification example

### ISSUE THREAD

**Issue by nwang2** [intel-analytics/analytics-zoo#1514]
We see below error message when running image classification example:
2019-07-15 09:34:04 INFO  Engine$:402 - Find existing spark context. Checking the spark conf...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Utils.getBatchSize: partitionNum should be larger than 0, but get 0

The script is as below:
```
spark-submit \
     --master local[44] \
     --num-executors 1 \
     --executor-cores 44 \
     --driver-memory 60g \
     --executor-memory 30g \
     --verbose \
     --driver-class-path /root/analytics-zoo-jdk8/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.6.0-SNAPSHOT-jar-with-dependencies.jar \
     --class com.intel.analytics.zoo.examples.imageclassification.Predict \
     /root/analytics-zoo-jdk8/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.6.0-SNAPSHOT-jar-with-dependencies.jar \
     --model /root/analytics-zoo_resnet-50_imagenet_0.1.0.model \
     -f file:///root/val/ --partition 44 --topN 5
```

**Comment by qiuxin2012** [comment]
Looks like your data is empty...

**Comment by nwang2** [comment]
ah... I see. The images are in sub folders in the path. If I use -f file:///root/val/n01855672, it works.
The error message is somehow misleading.

**Comment by qiuxin2012** [comment]
@nwang2 we will throw a better exception. Close this issue.
