### ISSUE TITLE
Release download with BigDL 0.9.0

### ISSUE THREAD

**Issue by jamesprinc3** [intel-analytics/analytics-zoo#1546]
Hello,

I'm currently using BigDL 0.9.0, now I'm looking to port my code over to use Analytics Zoo instead. However, I noticed that the releases page (https://analytics-zoo.github.io/master/#release-download/) does not have a version available with BigDL 0.9.0.

I guess this boils down to 2 questions:

- When will the nightly build be updated to use 0.9.0? (maybe tonight since https://github.com/intel-analytics/analytics-zoo/pull/1543 was recently merged?)
- When might Analytics Zoo 0.6.0 proper be released (presumably using BigDL 0.9.0?)

Thanks in advance!

**Comment by jason-dai** [comment]
Yes, the nightly build will use BigDL 0.9.0 going forward, and we plan to release Analytics Zoo 0.6.0 in August.

**Comment by jamesprinc3** [comment]
Awesome, thanks for the quick reply!
