### ISSUE TITLE
Problem store preprocessing object in HDFS

### ISSUE THREAD

**Issue by DVentas** [intel-analytics/analytics-zoo#1548]
When we save a model, and want to be store it in HDFS, the function FileWritter that save a PreProcessing object not support HDFS writting.

This happens in both, NNEstimator and NNModel classes.

**Comment by hhbyyh** [comment]
Thanks @DVentas 
As you've fixed, we should support HDFS path when saving the preprocessing steps. Let me know if you're interested in sending a PR. If not we'll send a fix (very similar to yours). Thanks for reporting the issue!

**Comment by engapa** [comment]
Given the commit is already in master branch, this issue should be closed, that's right?

**Comment by hhbyyh** [comment]
Yes, I created a separate issue to track the unit test.
Thanks for reporting the issue and providing the fix!
