### ISSUE TITLE
the link is broken

### ISSUE THREAD

**Issue by Light--** [intel-analytics/analytics-zoo#1569]
the link
 ```https://github.com/intel-analytics/zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala``` 

 in the sentence"```...For preprocessors for Image Classification models, please check Image Classification Config...```"

 of the file ```analytics-zoo/docs/docs/ProgrammingGuide/image-classification.md```is broken。

**Comment by hkvision** [comment]
Thanks for reporting. We will fix it asap.

**Comment by hkvision** [comment]
@jenniew The link should be to the repo `analytics-zoo` instead of `zoo`.

**Comment by hkvision** [comment]
@Light-- This issue has been fixed. Thank you so much!
