### ISSUE TITLE
No python example of training and inference model with MKLDNN

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/analytics-zoo#1571]
No python example of training and inference model with MKLDNN. Can we provide a example of CNN model and/or NLP model?

**Comment by hkvision** [comment]
Which example do you think is suitable?

**Comment by jenniew** [comment]
maybe the python counterpart of PTB model.

**Comment by jenniew** [comment]
Move to https://github.com/intel-analytics/BigDL/issues/2891
