### ISSUE TITLE
Optimzation OpenVINO Python API

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#1579]
To improve performance OpenVINO Python API (#1427 ), we need to switch to Cython API, which call C++ methods from Python directly. @aqtjin 
- [x] numpy into ctensor
- [x] Load model with Cython API
- [ ] Predict with Cython API
- [ ] Returan Ctensor and convert to numpy

**Comment by jason-dai** [comment]
Can Java/Scala call the same C++ code?

**Comment by qiyuangong** [comment]
> Can Java/Scala call the same C++ code?

Python and Java/Scala can use the same C++code. 

I'm still check Cython API. If there isn't any corner cases in current (jni) C++ code,  I think we can re-use them with Cython.

**Comment by qiyuangong** [comment]
@qiuxin2012 has merged JEP feature for performance. Do we still need this feature?

**Comment by qiyuangong** [comment]
Addressed by JEP feature. issue closed.
