### ISSUE TITLE
Duplicate PytorchModel and cpp files in zoo and zoo-core

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1602]
https://github.com/intel-analytics/analytics-zoo-core/blob/master/torchnet/src/main/java/com/intel/analytics/zoo/pipeline/api/net/PytorchModel.java
https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/java/com/intel/analytics/zoo/pipeline/api/net/PytorchModel.java

These two files are different in zoo and zoo-core. And when I view in IDE, the compiled class in zoo-core shadows the one in zoo, which is annoying.

**Comment by hhbyyh** [comment]
We can move all the native code to zoo-core.
