### ISSUE TITLE
spark-submit-python-with-zoo.sh need to give execution privilege

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/analytics-zoo#1662]
spark-submit-python-with-zoo.sh need to give execution privilege as in many readme it will be executed directly.

**Comment by hkvision** [comment]
This has been fixed in https://github.com/intel-analytics/analytics-zoo/pull/1651 Are you using the latest code?

**Comment by jenniew** [comment]
Yes, it is fixed already.

**Comment by jenniew** [comment]
In 0.6, this fix haven't back ported.

**Comment by hkvision** [comment]
backported now @jenniew
