### ISSUE TITLE
add new time related features

### ISSUE THREAD

**Issue by endymecy** [intel-analytics/analytics-zoo#1694]

**Comment by shane-huang** [comment]
A priority is to add the classical features used in Uber's methods 
Reference
* Figure 3 (a) in paper http://roseyu.com/time-series-workshop/submissions/TSW2017_paper_3.pdf
* Figure 4 in blog https://eng.uber.com/neural-networks/

**Comment by helenlly** [comment]
@shane-huang pls help to check the status.

**Comment by shane-huang** [comment]
close as it is outdated
