### ISSUE TITLE
Maven repo is a empty jar with 1K size for version 0.6.0

### ISSUE THREAD

**Issue by lizhizhou** [intel-analytics/analytics-zoo#1717]
https://mvnrepository.com/artifact/com.intel.analytics.zoo/zoo-core-dist-all/0.6.0

**Comment by glorysdj** [comment]
please use 0.8.1 instead.

<dependency>
  <groupId>com.intel.analytics.zoo</groupId>
  <artifactId>zoo-core-dist-all</artifactId>
  <version>0.8.1</version>
</dependency>
