### ISSUE TITLE
how to input multi-features?

### ISSUE THREAD

**Issue by Observer007** [intel-analytics/analytics-zoo#1724]
I'd like to use a open source keras model and its input is (1024, 1024,3), (93,), (28884, 4).
I try to use TFPredictor and TFDataset, but it's not work well. It seems the zoo regards the batch as the first dim of feature. So how to fit the data in TFDataset like [batch, [(1024, 1024,3), (93,), (261888, 4)].
The explanation of official document is not very clear.
The source code I used as follows
`inputs = [list(it) for it in list(zip(molded_images, image_metas, anchors))]`
`inputRDD = sc.parallelize(inputs)#.map(lambda x: list(x))`
`dataset = TFDataset.from_rdd(inputRDD, features=[(tf.float32, [1024,1024,3]), (tf.float32, [93]), (tf.float32, [261888, 4])], batch_per_thread=4)`
`tfpredictor = TFPredictor.from_keras(model.keras_model, dataset)`
`rdd = tfpredictor.predict()`
where molded_images, image_metas and anchors shape are [batch, 1024, 1024, 3], [batch, 93], [batch, 261888, 4]

**Comment by hkvision** [comment]
> I'd like to use a open source keras model and its input is (1024, 1024,3), (93,), (28884, 4).
> I try to use TFPredictor and TFDataset, but it's not work well. It seems the zoo regards the batch as the first dim of feature. So how to fit the data in TFDataset like [batch, [(1024, 1024,3), (93,), (261888, 4)].
> The explanation of official document is not very clear.
> The source code I used as follows
> `inputs = [list(it) for it in list(zip(molded_images, image_metas, anchors))]`
> `inputRDD = sc.parallelize(inputs)#.map(lambda x: list(x))`
> `dataset = TFDataset.from_rdd(inputRDD, features=[(tf.float32, [1024,1024,3]), (tf.float32, [93]), (tf.float32, [261888, 4])], batch_per_thread=4)`
> `tfpredictor = TFPredictor.from_keras(model.keras_model, dataset)`
> `rdd = tfpredictor.predict()`
> where molded_images, image_metas and anchors shape are [batch, 1024, 1024, 3], [batch, 93], [batch, 261888, 4]

Hi @Observer007 
What error did you get?
For multiple inputs, it is more convenient to use the following API:
```
TFDataset.from_rdd(rdd,
                                  names=["input1", "input2", "input3", "label"],
                                  shapes=[[024,1024,3], [93], [261888, 4], []],
                                  types=[tf.float32, tf.float32, tf.float32, tf.int32],
                                  batch_per_thread=4)
```
Have a try?

**Comment by helenlly** [comment]
@Observer007  could you provide the info as requested above?  or let us know if you still have questions currently. thanks.

**Comment by helenlly** [comment]
@Observer007 we 'll close the issue since no response from you. if need you can re-open at any time, thanks.
