### ISSUE TITLE
IllegalArgumentException: 'Unsupported class file major version 57' in training pipline

### ISSUE THREAD

**Issue by loewy43** [intel-analytics/analytics-zoo#1727]
hi, all,

I'm trying to learn Analytics Zoo's API via the example "cats-vs-dogs" via [https://github.com/intel-analytics/analytics-zoo/blob/master/apps/dogs-vs-cats/transfer-learning.ipynb](url).

when I ran the code "`catdogModel = pipeline.fit(trainingDF)`", 
it rised the erro:
IllegalArgumentException: 'Unsupported class file major version 57'

all the codes were running in the latest version of Analytics Zoo.

**Comment by hkvision** [comment]
Hi @loewy43 Could you provide more information when running this example? For example, you run from pip or pre-built packages? And the spark version you use, etc. Thanks.

**Comment by zhichao-li** [comment]
I guess it's more about JDK version. which version you used?

**Comment by loewy43** [comment]
thanks all. 

the error has been resloved via controlling the version of jdk by "conda install -c anaconda openjdk=8.0.152"
