### ISSUE TITLE
Add Python version of BigDL resnet50 int8

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1731]
Need a Python version of this: https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl

Requested by https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/bigdl-user-group/PLs-2-BDWSY

**Comment by hkvision** [comment]
@aqtjin

**Comment by qiyuangong** [comment]
PR merged. Issue closed
