### ISSUE TITLE
The path of news20 in text classification example doesn't exist

### ISSUE THREAD

**Issue by zjdx1998** [intel-analytics/analytics-zoo#1733]
NEWS20_URL = 'http://qwone.com/~jason/20Newsgroups/20news-18828.tar.gz' doesn't exist

**Comment by qiyuangong** [comment]
Hi @zjdx1998 

It seems that web browser cannot download this package anymore, pls use `wget`, `aria2c` , download tool to download this package. :)

**Comment by zjdx1998** [comment]
Oh, I'm stupid, I tried to `wget` the file but failed yesterday, it turns out my network had some problems.
Thanks, and I'm gonna close this :)
