### ISSUE TITLE
[automl] add random walk model

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#1764]
Random walk model (or naive model) are widely used for non-stationary data, and works remarkably well for many economic and financial time series. 

The forecasts from a random walk model are equal to the last observation, as future movements are unpredictable, and are equally likely to be up or down. 

Formula as :
`
y (t+h) = y (t)
`

**Comment by shane-huang** [comment]
references : 

- https://otexts.com/fpp2/stationarity.html
- https://people.duke.edu/~rnau/Notes_on_the_random_walk_model--Robert_Nau.pdf

**Comment by endymecy** [comment]
https://github.com/intel-analytics/analytics-zoo/pull/1835
