### ISSUE TITLE
The method 'get_predicts'  of TextSet should include uri info

### ISSUE THREAD

**Issue by endymecy** [intel-analytics/analytics-zoo#1818]
model = TextClassifier.load_model(FLAGS.model_dir + "/text_classifier.model")
 result = model.predict(test_set, batch_per_thread=int(FLAGS.partition_num))
 predicts = result.get_predicts()

The predicts should include uri info, otherwise we cannot correspond to docs and predictions

**Comment by hkvision** [comment]
Hi, @endymecy 

Thank you for your suggestion. I will add it very soon.
If you want to use it urgently, I suppose you can call `result.get_uris()` and zip with predicts RDD first?
Will notify you once it is added.

**Comment by endymecy** [comment]
ok, thanks

**Comment by hkvision** [comment]
I have raised a PR for this issue. Feel free to take a look at it. 
I would merge it very soon if no problem so that it will be included in the next release.
Thank you so much! @endymecy

**Comment by hkvision** [comment]
This issue has been fixed @endymecy
