### ISSUE TITLE
What dose this message means while using TFPark?

### ISSUE THREAD

**Issue by Zarca** [intel-analytics/analytics-zoo#1867]
Hello, I'm using Analytics zoo in my nlp projects in CentOS 7 recently.However, I found it that my bigdl program appers to be slower than Tensorflow(CPU) in deep learning stage.
So I'm not sure whether my bigdl program have take advantages of mkl library to get better performance...
What this message about mkl means while my program running?Dose it means that my CentOS already have the mkl library and it is already in use?
![zoo issue](https://user-images.githubusercontent.com/24642659/71396507-5cd8a900-2655-11ea-8168-eaac535963d7.png)

**Comment by qiyuangong** [comment]
Hi, @Zarca . MKL library has already been integrated into Analytics Zoo. So, you don't have to install or configure MKL.

**Comment by Zarca** [comment]
Hi,@qiyuangong.Thanks for kind attention.
My nlp project is maily about the known word2vec algorithm.
While I'm using Zoo's TFParK API, I noticed that  compared with Tensorflow in the same environment , my code is slower than code in TensorFlow version.
So how can I increment the number of mkl thread for a better  performance?...like set 20 mkl threads?

**Comment by qiyuangong** [comment]
Yes. You can change mkl related to setting to achieve better performance. But, in most cases, the default configuration in Analytics-Zoo will ensure best performance. @yangw1234 

Can you share your running environment? and the launch or submit command if possible?

**Comment by hkvision** [comment]
By default, in the case there are n cores, we run n TF models and each with a single thread. If the performance in this case is not good enough, you may try to use less executor cores, and use multiple threads per model? (i.e. you can specify inter/intra op parallelism thread in session_config when creating TFOptimizer: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/pipeline/api/net/tf_optimizer.py#L422)

**Comment by yangw1234** [comment]
hi @Zarca , thank you for using analytics-zoo. I notice in your log that you are using 4 executors and each with 20 cores. In default configuration, analytics-zoo will clone 20 models in each executor and each model will use one thread to run the forward and backward computation. 

You can override this by tweaking a few configurations:

- You can change the **number of model replicas** by modifying the number of cores allocated on each spark executor in spark configuration.

- You can change **the number of threads used by each model** by export OMP_NUM_THREADS environment variable on each executor. You can set spark.executorEnv.OMP_NUM_THREADS={num} in spark conf to do this.

Additional, batch size also has an impact on performance. You may want to scale up your batch size when training on multiple nodes.

If you could share more details, like your code (or some public reference repo) and other configurations, we would like to help you look into the issue.

**Comment by Zarca** [comment]
Thanks for your attention,@yangw1234 and @qiyuangong
My launch script in a CentOS 7 linux environment is listed below and
my test environment is Spark2.4.3 standalone with one master and one worker(spark.executor.instance=4)
-----------------------------------------------------------------------------------------------------------
#!/bin/bash

export SPARK_HOME=/mnt/ssd3/opt/work/spark-2.4.3-bin-hadoop2.7
export ANALYTICS_ZOO_HOME=/mnt/ssd3/opt/work/analytics-zoo-0.6.0-SNAPSHOT
export ANALYTICS_ZOO_VERSION=0.6.0
export BIGDL_VERSION=0.8.0
export SPARK_VERSION=2.4.3

${SPARK_HOME}/bin/spark-submit \
  --master spark://CentOSLinux01:7077 \
  --conf spark.executor.cores=20 \
  --conf spark.executor.instances=4 \
  --total-executor-cores 80 \
  --executor-memory 60g \
  --driver-memory 50g \
  --py-files ${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-bigdl_${BIGDL_VERSION}-spark_${SPARK_VERSION}-${ANALYTICS_ZOO_VERSION}-SNAPSHOT-python-api.zip \
  --jars ${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-bigdl_${BIGDL_VERSION}-spark_${SPARK_VERSION}-${ANALYTICS_ZOO_VERSION}-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.driver.extraClassPath=${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-bigdl_${BIGDL_VERSION}-spark_${SPARK_VERSION}-${ANALYTICS_ZOO_VERSION}-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.executor.extraClassPath=${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-bigdl_${BIGDL_VERSION}-spark_${SPARK_VERSION}-${ANALYTICS_ZOO_VERSION}-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.driver.extraJavaOptions=-Dderby.stream.error.file=/mnt/ssd3/ \
 --conf spark.sql.catalogImplementation='in-memory' /opt/work/word2vec_test.py
----------------------------------------------------------------------------------------------------------------

 So I still have some questions for this:

**1** As it showed above, I didn't built from Zoo's source code or built it from a dokcerfile,
I just copy  the analytics zoo's dependency jar and python zip files to my enviroment,  can this ensure that my program is utilizing the MKL libarary?
@qiyuangong 

**2**  I supposed that the Model RDD is a complete copy of the nural networks' weights, and it has a same partition with my training RDD via the ZipPartition action in Spark, so why that each executor will use the 20 model replica as the core number (20) it is assigned? Cause I thought the 20 models is just a little part of the complete weights of my neural network.

![fig4](https://user-images.githubusercontent.com/24642659/71430580-b3062480-2707-11ea-8d8b-fd5c183de65e.jpg)
![fig5](https://user-images.githubusercontent.com/24642659/71430713-6d962700-2708-11ea-861b-3f9cba62f614.jpg)
![fig6](https://user-images.githubusercontent.com/24642659/71430843-10e73c00-2709-11ea-9ae7-492f2f9c14e2.jpg)
@yangw1234 

Looking forward  your help(smile)

**Comment by yangw1234** [comment]
@Zarca For your second question, each executor will only have one partition of data and one partition of model. In each partition, we will use multiple instances of the same network to run on different data in parallel. With sufficient batch_size, this way can often achieve better cpu utilization on servers with many cores.

**Comment by Zarca** [comment]
Yep, so that is the point, In my environment , there are just 4 executors, each has 20 cores.
I started my program with  80 partitions, but I notice that during the stage of forward and backward computation, it will coalesec to just 4 partitions according to exactly what you mentioned. And there are just 4 tasks showing on the Spark service webpage like this:


![zoo issue3](https://user-images.githubusercontent.com/24642659/71436330-f2446d80-2727-11ea-8a79-c117a487c684.png)

I think in Spark, each task will just use one thread, but，do you mean that within each task , there are 20 parallel threads running in the same time?
(P.S. My batch_size is sufficient enough)
@yangw1234

**Comment by yangw1234** [comment]
@Zarca yes

**Comment by Zarca** [comment]
So I guess the forward and backward computation is not a RDD based action according to your answer, but why my cpu utilization is still lower than 20% when the training stages begings? 
If each tasks has 20 cores in used, then 4 executor ought to have near 100% utilization on 80 cores, but my observation is that my cpu utilization is lower than 20% during training...
@yangw1234 @hkvision

**Comment by helenlly** [comment]
@yangw1234  any updates?

**Comment by yangw1234** [comment]
@helenlly @Zarca there are many reasons to result in a low cpu utilization and the code in analytics zoo has been changed significantly during the years, so please try the latest version of analytics zoo to see if the problem still exists.

If they do, would you mind provide the code to reproduce the problem/
