### ISSUE TITLE
Question about performance between zoo and other program running on gpu

### ISSUE THREAD

**Issue by cfangplus** [intel-analytics/analytics-zoo#1875]
Hi everyone,

As we know, GPU plays an important role in DNN training so do you guys have something to say about the performance between zoo and other program running on gpu?  Can you provide some advices to enhance the performance of zoo while training a neural networks?

**Comment by qiyuangong** [comment]
Hi @cfangplus ,

Sorry for late reply. 

We know GPU play an important role in DNN training. But, it's quite hard to compare performance of CPU and GPU without specified scenario. I think you can refer [ML Perf](https://mlperf.org/training-results-0-6/) for details. 

In big data scenario, when training data is too large for GPU, or most training time are spent on pre-processing, then training with Zoo may be a better choice. In most cases, our default setting ensure best performance in given examples. If you have further question about these example, feel free to open an issue about that. :)

**Comment by cfangplus** [comment]
thanks for your replay @qiyuangong
