### ISSUE TITLE
change snakeyaml from snapshot to stable version

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#1878]
change snakeyaml to version 1.25
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.25</version>
</dependency>

and no need of below repo
 <repository>
            <id>Sonatype-public</id>
            <name>SnakeYAML repository</name>
            <url>http://oss.sonatype.org/content/groups/public/</url>
        </repository>

**Comment by Litchilitchy** [comment]
fixed
