### ISSUE TITLE
Cluster serving manual installation issues using prebuilt release package

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#1902]
I encountered several problems when I tried to install cluster serving by using prebuilt release package.

1. Getting `ModuleNotFoundError: No module named 'zoo'` run with cluster-serving-init. This error was solved by setting PYTHONPATH =.../analytics-zoo/pyzoo. However, the source code is not included in the prebuilt release package.

2. BigDL should be installed before cluster-serving-init.

3. Since I copied both the Redis server and the command line interface into `/usr/local/bin/` as recommended in [Redis Quick Start](https://redis.io/topics/quickstart), `src` dir doesn't exist in `$REDIS_HOME`. The cluster-serving-start script will failed to start Redis.

4. SPARK_HOME should be exported to start the cluster serving.

5. pyyaml and redis should be installed using pip instead of conda.

6. The cluster-serving-start script will raise an error if the downloaded spark-redis jar is broken.

**Comment by Litchilitchy** [comment]
@cyita @jason-dai I have updated the doc.

1. Add installation of Spark 2.4.3

2. Add instruction of set REDIS_HOME and SPARK_HOME in a more clear way.

3. Change the docker image address to the one we have just published.

@cyita To solve questions above, I have added those in doc, please check, anything not right could reply here,

1, 2. run `source analytics-zoo/bin/analytics-zoo-env.sh` in installation step.

3, 4, 5. Added in doc, please check if clear enough.

6. When I download it, it raises error if the jar is not right. However if you can not see the error, aka, we could not guarantee users will see this error, I will add something like checksum in latest version.

**Comment by Litchilitchy** [comment]
@cyita 5 is added in `Model Inference` section.

**Comment by cyita** [comment]
In the `Download Release` section, `cluster-serving-init` should be `python cluster-serving-init`?
Besides this, the updated doc is clear enough.

**Comment by Litchilitchy** [comment]
if the users python3 is installed in default way, `cluster-serving-init` should work. 

Otherwise they should use their own python interpreter

**Comment by cyita** [comment]
ok. Fixed.
