### ISSUE TITLE
Py4JJavaError

### ISSUE THREAD

**Issue by Gajya94** [intel-analytics/analytics-zoo#1908]
![Screenshot from 2020-01-11 14-51-43](https://user-images.githubusercontent.com/45539118/72202216-c5f85300-3482-11ea-8b05-e3bad93fd494.png)

**Comment by hkvision** [comment]
Hi @Gajya94,

Are you using the sample images we provide together with the notebook?
It will be great if you can provide more information (e.g. analytics-zoo version, spark version, whether you are using pip install, etc).

**Comment by helenlly** [comment]
@Gajya94  could you pls provide the info for our next investigation? thanks

**Comment by Gajya94** [comment]
Hello,
Sorry i could not provide the information because i am not using it anymore.
