### ISSUE TITLE
Showing 'Exception in thread "main" java.lang.IllegalStateException: Cannot find any build directories' when excecuting 'sc = init_nncontext()'

### ISSUE THREAD

**Issue by dhannya34** [intel-analytics/analytics-zoo#1965]
![Screenshot from 2020-01-21 11-55-24](https://user-images.githubusercontent.com/44765574/72780488-073bf000-3c45-11ea-83ad-633559d8bf19.png)
Could you please fix this issue as it is showing error just after calling  init_nncontext() at the very beginning of the code. As well as its showing error 'Exception: Java gateway process exited before sending its port number'. Could you please explain me what the problem is and how it can be solved?

**Comment by jason-dai** [comment]
How did you install Analytics Zoo? See the user guide at https://analytics-zoo.github.io/master/#PythonUserGuide/run/

**Comment by hkvision** [comment]
Hi @dhannya34 ,

Seems it is a problem related to spark. Have you install pyspark 2.4.3 in your python env? In this case please make sure you don't set SPARK_HOME.
BTW, we have just released 0.7.0 and you can have a try to upgrade :)

**Comment by dhannya34** [comment]
Wouldn't it be installed automatically after I run the command that's there in the document? I have unset SPARK_HOME. Which one should I upgrade to 0.7.0 that you have mentioned about?

**Comment by hkvision** [comment]
Yeah, it would be installed automatically. Just want you to make sure if there's something different in your environment as according to the error it should be a problem related to spark instead of analytics-zoo.  0.7.0 is analytics-zoo's newest release version.

**Comment by dhannya34** [comment]
Hi Kai Huang,
I have attached my environment setup code. Since SPARK_HOME has to be unset
I have commented all the lines. Is this the right way to unset SPARK_HOME?
If not can you please explain me how to?

**Comment by hkvision** [comment]
@dhannya34 Can you first try to create a sc using pyspark directly. If you cannot create an sc using pyspark, then for sure you will have problems using analytics-zoo as it is built on spark.

**Comment by dhannya34** [comment]
I have already called it at the beginning of the code and that's where it showed error. Is there any other way to create it directly?

**Comment by jason-dai** [comment]
@dhannya34 I wonder if you can elaborate on how exactly you have installed Analytics Zoo? Specifically, are you using `pip install analytics-zoo`?

**Comment by dhannya34** [comment]
Yes I have used pip install analytics-zoo.

**Comment by dhannya34** [comment]
![Screenshot from 2020-01-23 12-45-50](https://user-images.githubusercontent.com/44765574/72963862-59fcdf80-3dde-11ea-8a4a-f85f3de2312c.png)
![Screenshot from 2020-01-23 12-45-55](https://user-images.githubusercontent.com/44765574/72963864-59fcdf80-3dde-11ea-9aab-b03f8389bd65.png)
Since its not working in the latest version, I tried using 0.5.1 version. And its showing this error.

**Comment by dhannya34** [comment]
Could you please fix this as soon as possible?

**Comment by jason-dai** [comment]
@dhannya34 I think this is probably related to the environment and configurations of your local machine. To make it easy, I wonder if you can first try running the Docker image of Analytics Zoo (https://hub.docker.com/r/intelanalytics/analytics-zoo/tags)? You can find more details at https://analytics-zoo.github.io/0.7.0/#DockerUserGuide/#use-analtyics-zoo-with-docker-image

**Comment by hkvision** [comment]
@dhannya34 Hi, first of all, what I mean for creating a SparkContext directly is __NOT__ to use `init_nncontext` in Analytics Zoo, but to use the APIs in __pyspark__ directly to see if you can successfully create a SparkContext (for example, in the command line, type `pyspark` and it will create a sc).
This is to make sure your spark environment is correct.

**Comment by hkvision** [comment]
@dhannya34 Also, I notice that when you `pip install analytics-zoo==0.5.1`, you can find in the message that actually 0.6.0 is installed. This is really a strange behavior. Please make sure there is no problem with your pip environment.

You can first uninstall analytics-zoo and bigdl, and then `pip install analytics-zoo==0.7.0` to try again.

**Comment by helenlly** [comment]
@dhannya34   Does your installation work well?  pls let us know if any questions or if  we may close it. thanks.

**Comment by helenlly** [comment]
@dhannya34  we are closing the issue. pls free to re-open if you have more questions, thanks.
