### ISSUE TITLE
Printing out WARNING:root: can not find the jar for Analytics-Zoo when using spark-submit

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1991]
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo
WARNING:root:Trying to search from: /tmp/spark-dba5ec74-bf64-47e9-9c0e-96129462e4db/userFiles-edfa3976-698b-4aa6-8142-2ac45f1afafc/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.7.0-python-api.zip/zoo, but can not find the jar for Analytics-Zoo

If we use our scripts and the jar is specify when spark-submit, tons of above warning messages would be printed out, releated PR: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/engine.py#L117

**Comment by jason-dai** [comment]
Where is it called?

**Comment by hkvision** [comment]
@jason-dai It is always called when we init zoo. I suppose it is added for init_spark_on_yarn api to detect the jar, which is reasonable. But printing out this when using spark-submit may be annoying for users.

**Comment by jason-dai** [comment]
It is called from `prepare_env`, and the warning is introduced in https://github.com/intel-analytics/analytics-zoo/pull/1500

Not sure why we need the warning anyway; if `init_spark_on_yarn` cannot detect the jar, it will need to report error and exit, no?

**Comment by hkvision** [comment]
> It is called from `prepare_env`, and the warning is introduced in #1500
> 
> Not sure why we need the warning anyway; if `init_spark_on_yarn` cannot detect the jar, it will need to report error and exit, no?

Yeah, in init_spark_on_yarn there is assert statement. I don't think this warning is necessary. Remove it?

**Comment by jason-dai** [comment]
Yes, we can remove it.
