### ISSUE TITLE
A bug in Wide and Deep?

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#2045]
https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala#L207

Should be `columnInfo.indicatorDims(i - 1) + index` instead?

**Comment by hkvision** [comment]
The Python implementation is here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/models/recommendation/utils.py#L99
Python and Scala are not equivalent?
The different should be brought from modifying to keras style #1137

**Comment by hkvision** [comment]
`columnInfo.indicatorDims(i - 1) + index` is also not correct as it just consider the current index and dimension but not accumulating previous dimensions?
I think the correct one is the python one, using a for loop and an accumulator to accumulate. Just using a map is not accumulating? @jason-dai

**Comment by jason-dai** [comment]
> `columnInfo.indicatorDims(i - 1) + index` is also not correct as it just consider the current index and dimension but not accumulating previous dimensions?
> I think the correct one is the python one, using a for loop and an accumulator to accumulate. Just using a map is not accumulating? @jason-dai

Yes

**Comment by hkvision** [comment]
> > `columnInfo.indicatorDims(i - 1) + index` is also not correct as it just consider the current index and dimension but not accumulating previous dimensions?
> > I think the correct one is the python one, using a for loop and an accumulator to accumulate. Just using a map is not accumulating? @jason-dai
> 
> Yes

I will submit a PR to fix this.
