### ISSUE TITLE
Install problem -Warning message pops when use ZOO in Python(lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2050]
after config $ANALYTICS_ZOO_HOME,  
run  source ./bin/analytics-zoo-env.sh
Warning message pops when use ZOO in Python ( pic see the attachment)
[install problem 1.docx](https://github.com/intel-analytics/analytics-zoo/files/4315905/install.problem.1.docx)

**Comment by hkvision** [comment]
This is not a bug. It's their usage issue. They should only set SPARK_HOME or install pyspark but not both. Already clarified this in our documentation.
