### ISSUE TITLE
Cluster Serving: Tensorboard cannot open the problem on the web page(lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2052]
Tensorboard cannot open the problem on the web page (guessing is the tensorboard version problem)
.That can be solved by adding --bind_all in the script of cluster-serving-start.

**Comment by Litchilitchy** [comment]
fixed at #2049 

To fix this, user can also shutdown tensorboard and restart the tensorboard service by
```
tensorboard --logdir . --bind_all
```
