### ISSUE TITLE
Cluster Serving:The Cluster-serving-restart and cluster-serving-shutdown scripts will report errors when running(lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2053]
The Cluster-serving-restart and cluster-serving-shutdown scripts will report the following errors when running:
[CS2.docx](https://github.com/intel-analytics/analytics-zoo/files/4315958/CS2.docx)

**Comment by Litchilitchy** [comment]
fixed at #2048 

In old version user can just use ctrl + c to stop the Cluster Serving running in front end, or just call `cluster-serving-stop`.
