### ISSUE TITLE
Cluster Serving:Each time cluster-serving starts the service, a file is generated (lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2054]
Each time cluster-serving starts the service, a file is generated ; so many files will be generated . can it be fixed?

**Comment by Litchilitchy** [comment]
This is tensorboard log file, we can use a dir to store all of them in future.

If the older ones are deleted, past logs will not be available anymore.

**Comment by Litchilitchy** [comment]
All logs are managed in `TensorboardEventLogs` in newest  version.
