### ISSUE TITLE
Cluster Serving:some temp files are generated, can they be cleaned up? (lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2055]
After using the service, there will be a temp file generated. The content is a bit complicated. Will the file size increase all the time and will it be automatically cleaned up?

**Comment by Litchilitchy** [comment]
@glorysdj @qiyuangong zoo-core issue?

**Comment by qiyuangong** [comment]
Native libs will be deleted automatically after they are loaded. 
But, OpenVINO model-optimizer and calibration tools may not be deleted.  I will submit a PR for this problem.

**Comment by qiyuangong** [comment]
#2107

**Comment by qiyuangong** [comment]
After test with multiple scenario, I found that my PR cannot fully solve this problem.

Remain temp files are model-optimizer related files. As we are removing this feature from zoo, it will be solved automatically. :)
