### ISSUE TITLE
App problem: import function error(lc)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2057]
Import function error:
Errors when importing TFNet function in  script SimpleTraining.py:
#https: //github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/nnframes/tensorflow/SimpleTraining.py
from zoo.tfpark import TFNet

**Comment by yangw1234** [comment]
not properly setup, not an issue

**Comment by jason-dai** [comment]
How do we make sure the user can set it up properly?

**Comment by yangw1234** [comment]
@jason-dai in this particular case, the user used version 0.7.0 to run an example in master, so he ran into the import problem. 

For generally making users easy to install analytics zoo, I am thinking maybe we can open another issue to track and list the things we can do.
