### ISSUE TITLE
add anomly detector notebook for zouwu

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#2104]
We need anomaly detection notebook for zouwu. Use the API's provided in https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/model/anomaly.py. 

Refer to this pr for the changes in tests and codes https://github.com/intel-analytics/analytics-zoo/pull/2296/files. You can learn from the unit tests about how to use the API's. 

References: 
1. forcasting demo notebook in zouwu on network traffic data https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/zouwu/use-case/network_traffic
2. anomaly detection notebook without zouwu on new york taxi data https://github.com/intel-analytics/analytics-zoo/tree/master/apps/anomaly-detection

**Comment by shane-huang** [comment]
@yushan111 please submit a pr with the partial completed anomaly notebook on aiops data and refer to the pr in this issue.

**Comment by yushan111** [comment]
> @yushan111 please submit a pr with the partial completed anomaly notebook on aiops data and refer to the pr in this issue.

The initial anomaly detection notebook is in PR #2313.

**Comment by yushan111** [comment]
To do: 

- replace current anomaly detection method with anomaly detector API

- modify helper functions 

- add more docs

- better arrangement

- code refactoring

**Comment by EN1AC13** [comment]
I have submit a pr. The updated anomaly detection notebook is in PR #2356

**Comment by EN1AC13** [comment]
I have updated  notebook in zouwu and submit a new pr.
The latest anomaly detect notebook is in new PR https://github.com/intel-analytics/analytics-zoo/pull/2374

**Comment by yushan111** [comment]
related PR #2374  is merged.
