### ISSUE TITLE
anomaly-detection-nyc-taxi 'DataFrame' object has no attribute 'as_matrix' when pandas 1.0+ 

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2106]
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

**Comment by remisharoon** [comment]
as_matrix method is deprecated since 0.23.0, use to_numpy() instead

SO link : https://stackoverflow.com/questions/60164560/attributeerror-series-object-has-no-attribute-as-matrix-why-is-it-error/61031352#61031352

**Comment by jason-dai** [comment]
> as_matrix method is deprecated since 0.23.0, use to_numpy() instead
> 
> SO link : https://stackoverflow.com/questions/60164560/attributeerror-series-object-has-no-attribute-as-matrix-why-is-it-error/61031352#61031352

Thanks @remisharoon

**Comment by shane-huang** [comment]
I'll fix it.
