### ISSUE TITLE
Remove dependence on keras

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#2130]
We can use:
1) `zoo.pipeline.api.keras.datasets` instead of `keras.datasets`
2) `tf.keras.preprocessing` instead of `keras.preprocessing`

https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/attention/transformer.py

**Comment by Le-Zheng** [comment]
Alright, got it.

**Comment by Le-Zheng** [comment]
This example requires Keras-2. When I change to `zoo.pipeline.api.keras.datasets` , the dataset can not be downloaded. 
The exact error is `TypeError: load_data() got an unexpected keyword argument 'num_words' ` .  https://github.com/keras-team/keras/issues/6174   solution is updating keras.
Thus, we may keep the example unchangeable.

**Comment by jason-dai** [comment]
Then can we use `tf.keras.datasets`?

**Comment by Le-Zheng** [comment]
Yes. Ok, I will use `tf.keras.datasets`

**Comment by Le-Zheng** [comment]
This example is updated in this pull request https://github.com/intel-analytics/analytics-zoo/pull/2127

**Comment by shane-huang** [comment]
Maybe we should also remove keras dependencies in jenkins. I noticed they're installed.

**Comment by hkvision** [comment]
Can we close this issue now? @Le-Zheng

**Comment by Le-Zheng** [comment]
> Maybe we should also remove keras dependencies in jenkins. I noticed they're installed.

It  looks we still have test requires keras. https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/dev/run-pytests-keras2

**Comment by Le-Zheng** [comment]
> Can we close this issue now? @Le-Zheng

Yes.
