### ISSUE TITLE
Ray tune applications may get stuck while using RayOnSpark on single node

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/analytics-zoo#2154]
This affects both zouwu and automl fitting with ray tune. 
While running more than one trials on local, there may be one trial whose status is always `RUNNING` without updating of pid, running time or iteration information. Resource utilizations are low. Killing all ray processes and restart doesn't help. This issue happens in a random fashion. 
![image](https://user-images.githubusercontent.com/12656939/78631219-51408380-78ce-11ea-9249-d84ba9a4be81.png)

Note that this only occurs while init with `RayOnSpark`.  `ray.init()` does not trigger this issue.

**Comment by shane-huang** [comment]
Same problem happens to me. This usually happens when ray tune has more than 1 trials.  We can't see any problems with UT's now because all of them run only 1 trial (we will use more trails later). Notebooks will fail with more than 1 UT.

**Comment by shane-huang** [comment]
This happens only on single-node. Probably due to ray start not stable on single-node. We can have a shortcut to use ray.init on single-node.

**Comment by jason-dai** [comment]
A simple fix is that, in RayContext if `is_local` is true and `local_ray_node_num` is 1, we can just call `ray.init` in `RayContext.init`, and call `ray.shutdown' in `RayContext.stop`

**Comment by hkvision** [comment]
> A simple fix is that, in RayContext if `is_local` is true and `local_ray_node_num` is 1, we can just call `ray.init` in `RayContext.init`, and call `ray.shutdown' in `RayContext.stop`

What about removing `local_ray_node_num`?
Just call ray.init() and ray.shutdown().
Spark is used to restrict the resources. If spark has 4 cores, ray.init(num_cpus=4)?
@jason-dai

**Comment by jason-dai** [comment]
> > A simple fix is that, in RayContext if `is_local` is true and `local_ray_node_num` is 1, we can just call `ray.init` in `RayContext.init`, and call `ray.shutdown' in `RayContext.stop`
> 
> What about removing `local_ray_node_num`?
> Just call ray.init() and ray.shutdown().
> Spark is used to restrict the resources. If spark has 4 cores, ray.init(num_cpus=4)?
> @jason-dai

You can also do that.

**Comment by shane-huang** [comment]
fixed in #2175
