### ISSUE TITLE
tf inception's checkpoint doesn't work

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#2201]
tf inception's checkpoint doesn't work, the checkpoint dir is empty.

**Comment by yangw1234** [comment]
The checkpoint trigger is intended to trigger validation in the inception example.
Using bigdl checkpoint for resume training can be done using existing api, but it is never officially supported.

There is a bug though, and I'll address it in #2203 .

For the support of resume training will be addressed in another pr.

**Comment by yangw1234** [comment]
fixed by #2211
