### ISSUE TITLE
replace resource files to ftp in apps/run-app-tests-pip.sh and run-app-tests.sh

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2206]
like 
    wget https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/object-detection/analytics-zoo_ssd-mobilenet-300x300_PASCAL_0.1.0.model -P ${ANALYTICS_ZOO_HOME}/apps/object-detection/

wget https://s3.amazonaws.com/analytics-zoo-data/train_dog.mp4 -P ${ANALYTICS_ZOO_HOME}/apps/object-detection/

wget http://places2.csail.mit.edu/models_places365/googlenet_places365.caffemodel -P ${ANALYTICS_ZOO_HOME}/apps/image-similarity/googlenet_places365

etc.

**Comment by Le-Zheng** [comment]
fixed in merged https://github.com/intel-analytics/analytics-zoo/pull/2210
