### ISSUE TITLE
404 not found for jdk download in Dockerfiles

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2218]
Step 27 : RUN wget https://build.funtoo.org/distfiles/oracle-java/jdk-8u152-linux-x64.tar.gz &&     gunzip jdk-8u152-linux-x64.tar.gz &&     tar -xf jdk-8u152-linux-x64.tar -C /opt &&     rm jdk-8u152-linux-x64.tar &&     ln -s /opt/jdk1.8.0_152 /opt/jdk
 ---> Running in f2f72c6bd848
[91m--2020-04-15 02:01:52--  https://build.funtoo.org/distfiles/oracle-java/jdk-8u152-linux-x64.tar.gz
[0m[91mResolving proxy-chain.intel.com (proxy-chain.intel.com)... [0m[91m10.19.8.225
Connecting to proxy-chain.intel.com (proxy-chain.intel.com)|10.19.8.225|:912... [0m[91mconnected.
[0m[91mProxy request sent, awaiting response... [0m[91m404 Not Found
2020-04-15 02:01:53 ERROR 404: Not Found.

[0mThe command '/bin/sh -c wget https://build.funtoo.org/distfiles/oracle-java/jdk-8u152-linux-x64.tar.gz &&     gunzip jdk-8u152-linux-x64.tar.gz &&     tar -xf jdk-8u152-linux-x64.tar -C /opt &&     rm jdk-8u152-linux-x64.tar &&     ln -s /opt/jdk1.8.0_152 /opt/jdk' returned a non-zero code: 8
Build step 'Execute shell' marked build as failure.

Need to update the wget method

**Comment by glorysdj** [comment]
no resources at  https://build.funtoo.org/distfiles/oracle-java/jdk-8u152-linux-x64.tar.gz any more.
use option --header "Cookie: oraclelicense=accept-securebackup-cookie" to download from oracle
refer to https://gist.github.com/hgomez/9650687

**Comment by qiyuangong** [comment]
Maybe we can use `yum` or `apt-get` for JDK installation.

**Comment by glorysdj** [comment]
> Maybe we can use `yum` or `apt-get` for JDK installation.

that will install open-jdk, may other issues happen

**Comment by glorysdj** [comment]
fixed

**Comment by glorysdj** [comment]
--header "Cookie: oraclelicense=accept-securebackup-cookie" can not work anymore....

**Comment by glorysdj** [comment]
fixed again
