### ISSUE TITLE
Upgrade ray version?

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#2244]
Should we upgrade the supported ray version?

@shane-huang @hkvision

**Comment by shane-huang** [comment]
Actually I'm also thinking about it. 
Newer ray tune version contains new search algorithms which might be useful. 
But ray has breaking changes since ray 0.7.3, we need to change our implementations if upgrade higher than that? What's the specific reason to upgrade ray?

add @yushan111

**Comment by shane-huang** [comment]
merged in #2249
