### ISSUE TITLE
missing ray related notebook tests in non-pip app-tests

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#2308]
Several notebooks (mostly ray ralated, i.e. ray automl zouwu) are missing in the non-pip app-tests. https://github.com/intel-analytics/analytics-zoo/blob/master/apps/run-app-tests.sh Since we only run non-pip apptests in nightly and rarely run pip app-tests, it will be hard to discover failures in time.  

Note these tests can not be simply added using the spark-submit way since ray on spark didn't support this. We can use pythonpath and run those tests with python directly, as ray examples did. Refer to
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/run-example-test-ray.sh

**Comment by glorysdj** [comment]
we will enable http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests/ and merge it into nightly build

**Comment by Le-Zheng** [comment]
We have enabled and merged ZOO-NB-Pip-AppTests in nightly build http://10.239.47.210:18888/job/ZOO-Nightly-Build/. 
Zouwu and ray related notebooks are tested in http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-part4/, which is running successfully.
