### ISSUE TITLE
Cluster Serving String Support

### ISSUE THREAD

**Issue by respecteverything** [intel-analytics/analytics-zoo#2342]
I test cluster serving using wnd model which has following inputs:
```
{'age': <tf.Tensor  shape=(?,) dtype=int32>, 
'workclass': <tf.Tensor  shape=(?,) dtype=string>, 
'fnlwgt': <tf.Tensor  shape=(?,) dtype=int32>, 
'education': <tf.Tensor  shape=(?,) dtype=string>, 
'education_num': <tf.Tensor  shape=(?,) dtype=int32>, 
'marital_status': <tf.Tensor  shape=(?,) dtype=string>, 
'occupation': <tf.Tensor  shape=(?,) dtype=string>, 
'relationship': <tf.Tensor  shape=(?,) dtype=string>, 
'race': <tf.Tensor  shape=(?,) dtype=string>, 
'gender': <tf.Tensor  shape=(?,) dtype=string>, 
'capital_gain': <tf.Tensor  shape=(?,) dtype=int32>, 
'capital_loss': <tf.Tensor  shape=(?,) dtype=int32>, 
'hours_per_week': <tf.Tensor  shape=(?,) dtype=int32>, 
'native_country': <tf.Tensor shape=(?,) dtype=string>}
``` 
Then following error occurred when I was input the data into Redis:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/jieru/analytics-zoo/pyzoo/zoo/serving/client.py", line 124, in enqueue_tensor
    d = d.astype("float32").flatten()
```
This problem seems to appear due to we currently only support the types which can convert to float and string can't do it so the error occurred.

**Comment by jason-dai** [comment]
I believe that `TFNet` supports string tensor today? We need to expose that in `InferenceModel`?@yangw1234 @glorysdj

**Comment by yangw1234** [comment]
@jason-dai string tensor is supported now.

@glorysdj here is an example
```scala
    import com.intel.analytics.zoo.tfpark.TFTensorNumeric.NumericByteArray
    val data = Array("123.0", "456.0").map(_.getBytes("utf-8"))
    val stringTensor = Tensor[Array[Byte]](data, Array[Int](2))
    val net = TFNet(resource.getPath)
    val result = net.forward(stringTensor)
```

**Comment by jason-dai** [comment]
> @jason-dai string tensor is supported now.
> 
> @glorysdj here is an example
> 
> ```scala
>     import com.intel.analytics.zoo.tfpark.TFTensorNumeric.NumericByteArray
>     val data = Array("123.0", "456.0").map(_.getBytes("utf-8"))
>     val stringTensor = Tensor[Array[Byte]](data, Array[Int](2))
>     val net = TFNet(resource.getPath)
>     val result = net.forward(stringTensor)
> ```

Do you have a python example? the user needs to first convert array of string to array of bytes, yes?

**Comment by jason-dai** [comment]
@glorysdj @Litchilitchy I think we need to change both the `InferenceModel` and `enqueue_tensor` APIs?

**Comment by yangw1234** [comment]
@jason-dai currently python only supports inference using TFDataset api. Do we need python api for inference model?

**Comment by glorysdj** [comment]
do we support inference with Tensor[String/Array[Byte]], now frontend and python enqueue_tensor  supports string tensor.
we may need to change InferenceModel.

**Comment by Litchilitchy** [comment]
Supported.
