### ISSUE TITLE
mask rcnn Zoo+openvino output of predict() from inference_model.py

### ISSUE THREAD

**Issue by aqtjin** [intel-analytics/analytics-zoo#2367]
I have found that the output's format of Mask R-CNN model use predict() from inference_model.py might not match Openvino's converted model output.

https://github.com/opencv/open_model_zoo/blob/master/models/public/mask_rcnn_inception_resnet_v2_atrous_coco/mask_rcnn_inception_resnet_v2_atrous_coco.md
As the document introduces, the output of a converted mask_rcnn model contains two parts as below. But I only got the heatmaps result from pridict().

The array of summary detection information, name: reshape_do_2d, shape: [N, 7], where N is the number of detected bounding boxes. For each detection, the description has the format: [image_id, label, conf, x_min, y_min, x_max, y_max], where:

image_id - ID of the image in the batch
label - predicted class ID
conf - confidence for the predicted class
(x_min, y_min) - coordinates of the top left bounding box corner (coordinates stored in normalized format, in range [0, 1])
(x_max, y_max) - coordinates of the bottom right bounding box corner (coordinates stored in normalized format, in range [0, 1])

Segmentation heatmaps for all classes for every output bounding box, name: masks, shape: [N, 90, 33, 33], where N is the number of detected masks, 90 is the number of classes (the background class excluded).

**Comment by aqtjin** [comment]
@qiyuangong

**Comment by qiyuangong** [comment]
OK. I will check details ASAP. :)

**Comment by qiyuangong** [comment]
Seems that OpenVINO predict C++ API ignored `mask` output.  I will try to fix this problem. Will let you know if it is ready. :)

**Comment by helenlly** [comment]
@qiyuangong ,any update?

**Comment by qiyuangong** [comment]
@helenlly @aqtjin This issue is addressed by #4025.

Issue closed
