### ISSUE TITLE
orca read csv or json better check file existence

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2436]
Currently if I give a wrong folder name or an empty folder (I use just local) to `orca.read_csv`, then the error would only be reported when call partition.get_data, which returns None from ray.
Better do the check or give some more meaningful message beforehand.

**Comment by jenniew** [comment]
Empty folder create empty XShards. It's not reasonable. We should not create XShards. 
Fixed in https://github.com/intel-analytics/analytics-zoo/pull/2443

**Comment by hkvision** [comment]
> Empty folder create empty XShards. It's not reasonable. We should not create XShards.
> Fixed in #2443

But what if not an empty folder, but the folder has no json files or there is a mix of json files and other file types? What's the behavior?

**Comment by jenniew** [comment]
Will only read json files

**Comment by hkvision** [comment]
Okay. So if the folder only contains txt but no json files, will there be an error raised that there is no json file detected?

**Comment by jenniew** [comment]
yes
