### ISSUE TITLE
Orca test_repartition unit test is wrong

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2438]
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/orca/data/test_ray_pandas.py#L65

In this unit test, `partition_data = partitions2[0].get_data()` returns `[None, None]`, why isn't it reading the actual data? Anything wrong with the implementation?

**Comment by jenniew** [comment]
The reason is in that test case, read_json() misses required arguments: orient='columns',lines=True. So no data is read.

**Comment by jenniew** [comment]
Fixed in https://github.com/intel-analytics/analytics-zoo/pull/2443

**Comment by hkvision** [comment]
> The reason is in that test case, read_json() misses required arguments: orient='columns',lines=True. So no data is read.

So shall we add some default values for these and in case the user forgets to add?
BTW, in the doc, there is no explanation or indication for users to add these arguments, can we add some?

**Comment by jenniew** [comment]
If not arguments provided, will use default arguments of pands.read_csv/read_json.

**Comment by hkvision** [comment]
Then we'd better add some details in the documentation.

**Comment by jason-dai** [comment]
I think `read_csv` and `read_json` are supposed to have the exactly same APIs as Pandas?

**Comment by jenniew** [comment]
Yes, read_csv and read_json are supposed to have same parameters as Pandas. It's easy for Pandas users to port to Orca.
