### ISSUE TITLE
Why Orca read_json/csv for Spark and Ray behaves differently?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2440]
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/data/pandas/preprocessing.py#L218

For each ray actor, if it has more than one file, it does the concat on dataframes.
But for spark each partition, if there is more than one file, it does nothing, returns multiple dataframes.
Why are they behaving differently?
@jason-dai

**Comment by jenniew** [comment]
I think in RayXShards, each xshards contains multiple partitions, and each partition contains multiple shard. Shard is the smallest unit, and each shard contains a dataframe. In SparkXShard, each partition contains multiple elements, and every element is a dataframe.

**Comment by jason-dai** [comment]
> I think in RayXShards, each xshards contains multiple partitions, and each partition contains multiple shard. Shard is the smallest unit, and each shard contains a dataframe. In SparkXShard, each partition contains multiple elements, and every element is a dataframe.

I think the key question is whether it's good to apply the transformations to many small dataframes, or apply it to a large dataframe?

**Comment by hkvision** [comment]
Closing this issue as using Ray has been removed.
