### ISSUE TITLE
BigDL analytics-zoo downloads reports AccessDenied

### ISSUE THREAD

**Issue by lutzroeder** [intel-analytics/analytics-zoo#2447]
```
~: curl https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/imageclassification/imagenet/analytics-zoo_alexnet_imagenet_0.1.0.model 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...</RequestId><HostId>...</HostId></Error>%
```

@helenlly, @dding3, @jenniew, @hkvision

**Comment by glorysdj** [comment]
please download from
https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/zoo/zoo-resources/analytics-zoo-models/image-classification/analytics-zoo_alexnet_imagenet_0.1.0.model

**Comment by lutzroeder** [comment]
```
~: curl --head https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/zoo/zoo-resources/analytics-zoo-models/image-classification/analytics-zoo_alexnet_imagenet_0.1.0.model
HTTP/2 404 
server: awselb/2.0
date: ...
content-type: text/plain; charset=utf-8
content-length: 0
```

**Comment by glorysdj** [comment]
@lutzroeder
Sorry for late reply. We are moving models from S3. Please download models from here:
https://sourceforge.net/projects/analytics-zoo/files/analytics-zoo-models/

**Comment by jason-dai** [comment]
> @lutzroeder
> Sorry for late reply. We are moving models from S3. Please download models from here:
> https://sourceforge.net/projects/analytics-zoo/files/analytics-zoo-models/

We also need to update the links in readme and documents

**Comment by lutzroeder** [comment]
@jason-dai These paths are not working either:
https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/object-detection/analytics-zoo_ssd-mobilenet-300x300_PASCAL_0.1.0.model
https://s3-ap-southeast-1.amazonaws.com/bigdl-models/imageclassification/imagenet/bigdl_inception-v1_imagenet_0.4.0.model
https://s3-ap-southeast-1.amazonaws.com/bigdl-models/object-detection/bigdl_messi_quantize.model

**Comment by hkvision** [comment]
Yeah, all the models would be migrated to the new directory. We would update the docs. Thanks for pointing out.

**Comment by glorysdj** [comment]
> > @lutzroeder
> > Sorry for late reply. We are moving models from S3. Please download models from here:
> > https://sourceforge.net/projects/analytics-zoo/files/analytics-zoo-models/
> 
> We also need to update the links in readme and documents

We will do this.
