### ISSUE TITLE
how can I predict future unseen data?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2448]
For example, use the trained model and the currently known given length data to predict the "unseen " data in the next  Several (5 or 10) steps, what functions should be called, and how to set the parameters. Please give an example code. Of course, the "unseen " data Belong to the future， not in the training 、Validation  and  test dataset.

**Comment by qiyuangong** [comment]
Hi @2017wxyzwxyz 

In my view, your example looks quite like `Time-Series` prediction, i.e., using a range of historical data to predict future trends or values. These future trends or values are `unseen` in production. Lots of real-world applications are using Time-Series prediction, such as anomaly detection, stock prediction etc. We have a [Python](https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/anomalydetection) and [Scala](https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/anomalydetection) example about anomaly detection.

In practice, training Time-Series models still require training, validation and test dataset. These datasets all come from the past. But we can mask the answer (make them unseen) to teach/training our models, and make these models strong enough to predict future values in production.

**Comment by 2017wxyzwxyz** [comment]
think you very much ! 
My problem is really time series prediction. I forgot to explain

**Comment by qiyuangong** [comment]
Issue closed. 
Feel free to reopen it if necessary. :)
