### ISSUE TITLE
Ray tests not run for nightly build

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2450]
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/
No ray tests are included?
Why the running command is different from PR validation?

**Comment by glorysdj** [comment]
looks they are same commands?
http://10.239.47.210:18888/job/ZOO-PR-Python-Spark-2.3-py37/configure

pyzoo/dev/run-tests?

**Comment by hkvision** [comment]
No. ray tests are only run in spark 2.4.
See here: http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-Spark-2.4-py37/configure

**Comment by glorysdj** [comment]
added both py36/37 in http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON
and http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC
also started two jobs, please check the results:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/633/console
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/56/console
