### ISSUE TITLE
Remove OpenVINO Model Optimizer from Zoo

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#2458]
[OpenVINO model zoo](https://github.com/opencv/open_model_zoo) has become a default installation module during OpenVINO binary installation. It's more easy to use than previous command line tools. Besides, more and more intel optimized model and public models will be added into this model zoo.

I think we don't need to integrate and maintenance OpenVINO Model Optimizer in analytics-zoo. :)

**Comment by glorysdj** [comment]
+1, can we remove the deprecated apis like loadTFasOV which includes openvino optimize methods  in this release?

**Comment by qiyuangong** [comment]
#2457

**Comment by qiyuangong** [comment]
Already done. Issue closed. :)
