### ISSUE TITLE
Do we support collect() and transfom_shard() after converting SparkXShards to RayXShards

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/analytics-zoo#2475]
If we use SparkXShards.to_ray() to convert SparkXShards to RayXShards, in RayPartition, the shard_list is an object id. But the current implementation of collect() and transform_shard() in RayXShards is based on Ray actor not object id, so they are working on this sort of RayXShards. Do we need to support collect() and transform_shard() for this scenario? I think we may need to support collect(). For transform_shard(), do we assume users do all the pre-processing on SparkXShards, no need to transform on Ray side? If we want to support transform_shard(), still create actors to do that? @jason-dai @hkvision

**Comment by jason-dai** [comment]
The plan is to remove `RayXShards` afterwards, and so all data transformations are done on Spark.
