### ISSUE TITLE
Website style error and ugly format

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2481]
https://analytics-zoo.github.io/master/##why-use-analytics-zoo
Here the format is wrong.

https://analytics-zoo.github.io/master/#gettingstarted/
This page is really ugly. Don't need every subsection as a title; otherwise the outline on the left is messy. We can just make the subsections bold.

`4.4. Cluster Serving` should be `4.4` not `4.4.`

**Comment by helenlly** [comment]
fixed the first issue

"https://analytics-zoo.github.io/master/##why-use-analytics-zoo
Here the format is wrong."

 in https://github.com/intel-analytics/analytics-zoo/pull/2486

**Comment by Wesley-Du** [comment]
updated gettingstarted.md in #2483
