### ISSUE TITLE
check_tf_version()

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#2484]
* `zoo/pipeline/api/net/__init__.py`  imports TFNet
* `zoo/pipeline/api/net/torch_net.py`  imports zoo.tfpark.tfnet.to_sample_rd

As a result, an error is thrown if TensorFlow is not installed or is TF2 due to https://github.com/intel-analytics/analytics-zoo/pull/2459

We should:
1. move `zoo.tfpark.tfnet.to_sample_rdd` to a `util` package
2. remove "import TFNet" from `zoo/pipeline/api/net/__init__.py`  
2. move the check in https://github.com/intel-analytics/analytics-zoo/pull/2459 to where it is used (e.g., in TFNet, TFOptimizer, etc.)

**Comment by yangw1234** [comment]
@jason-dai Can we remove `TFNet` from `zoo/pipeline/api/net/__init__.py` and throw an error when users import `TFNet` from `zoo.pipeline.api.net` and tell them to use `zoo.tfpark.TFNet`?

**Comment by yangw1234** [comment]
@jason-dai `zoo/tfpark/__init__.py` will import `TFOptimizer`, `TFEstimator`, etc, and those files will import `tensorflow`. So I think an error will be thrown with or without the check, if TF is not installed.

**Comment by jason-dai** [comment]
> @jason-dai `zoo/tfpark/__init__.py` will import `TFOptimizer`, `TFEstimator`, etc, and those files will import `tensorflow`. So I think an error will be thrown with or without the check, if TF is not installed.

There are potentially other places where utilities in tfpark (e.g., to_sample_rdd) are used in Analytics Zoo, but the user does not intend to use tensorflow; I don't think it reasonable to check the user environment unless they explicitly use `TFOptimizer`, `TFEstimator`, etc.

**Comment by yangw1234** [comment]
> > @jason-dai `zoo/tfpark/__init__.py` will import `TFOptimizer`, `TFEstimator`, etc, and those files will import `tensorflow`. So I think an error will be thrown with or without the check, if TF is not installed.
> 
> There are potentially other places where utilities in tfpark (e.g., to_sample_rdd) are used in Analytics Zoo, but the user does not intend to use tensorflow; I don't think it reasonable to check the user environment unless they explicitly use `TFOptimizer`, `TFEstimator`, etc.

Hi @jason-dai , I am OK with moving the check to `TFOptimizer`, `TFEstimator`. but I do not think this alone will solve the problem, because the import error in other files will be thrown.

So we also need to remove `import tensorflow` from every file header and import it locally every time we use it. (And I not sure it is even possible because there are classes that implement TF classes.) 

Do you think it is ok if we move the utilities out of TFPark (if they are also used in other parts of AZ)? I think it is reasonable to assume TFPark as a whole depends on TF 1.15.0 and if other parts of AZ should not use TFPark if it does not want TF.

**Comment by jason-dai** [comment]
> > > @jason-dai `zoo/tfpark/__init__.py` will import `TFOptimizer`, `TFEstimator`, etc, and those files will import `tensorflow`. So I think an error will be thrown with or without the check, if TF is not installed.
> > 
> > 
> > There are potentially other places where utilities in tfpark (e.g., to_sample_rdd) are used in Analytics Zoo, but the user does not intend to use tensorflow; I don't think it reasonable to check the user environment unless they explicitly use `TFOptimizer`, `TFEstimator`, etc.
> 
> Hi @jason-dai , I am OK with moving the check to `TFOptimizer`, `TFEstimator`. but I do not think this alone will solve the problem, because the import error in other files will be thrown.
> 
> So we also need to remove `import tensorflow` from every file header and import it locally every time we use it. (And I not sure it is even possible because there are classes that implement TF classes.)
> 
> Do you think it is ok if we move the utilities out of TFPark (if they are also used in other parts of AZ)? I think it is reasonable to assume TFPark as a whole depends on TF 1.15.0 and if other parts of AZ should not use TFPark if it does not want TF.

1) I think we should move these utilities out of tfpark
2) However, sometimes tfpark is automatically imported by zoo code and the user has no control over it
3) It makes much more sense for to run `check_tf_version` only when the user explicitly uses tfpark to process tf codes, and there should be only a handful places (like `TFOptimizer`, `TFNet`, etc.)
4) And maybe we can report warning or error in `check_tf_version`, but don't actually exit the program.
