### ISSUE TITLE
How to configure node number and partition number?

### ISSUE THREAD

**Issue by hibayesian** [intel-analytics/analytics-zoo#2490]
`requirement failed: Passed in rdd partition number 400 is not equal to configured node number 4`

I don't know how to configure node number. And why are these two number equal? Actually, it's very common that rdd partition number is greater than node number. 

Does anybody knows that?

**Comment by Le-Zheng** [comment]
hi, partition number should be equal to node number. 
Spark assigns one task per partition. Each executor process one task at a time.
400 partition number looks too large. It may exceed total cores. Generally, a large partition number will cause task scheduling to take more time. I suggest setting the partition number as 4.

**Comment by jason-dai** [comment]
> `requirement failed: Passed in rdd partition number 400 is not equal to configured node number 4`
> 
> I don't know how to configure node number. And why are these two number equal? Actually, it's very common that rdd partition number is greater than node number.
> 
> Does anybody knows that?

Can you share the code to reproduce the error? BigDL should automatically repartition your data based on the node number.

**Comment by hibayesian** [comment]
@jason-dai 

I am writing the code following the example of CensusWideAndDeep.

**Comment by jason-dai** [comment]
> @jason-dai
> 
> I am writing the code following the example of CensusWideAndDeep.

Can you share which lines of codes actually cause the errors?
