### ISSUE TITLE
get_nyc_taxi.sh script should download data from original github repo

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/analytics-zoo#2494]
people won't be able to download this data as the address is internal only. 
wget http://10.239.45.10:8081/repository/raw/analytics-zoo-data/data/NAB/nyc_taxi/nyc_taxi.csv

**Comment by glorysdj** [comment]
we are moving data to sourceforge too.

**Comment by shane-huang** [comment]
https://github.com/numenta/NAB/blob/v1.0/data/realKnownCause/nyc_taxi.csv  any one fix this issue please also check whether this version is the same as the one in our own repo. If not, please find the correct revision of the nyc_taxi file

**Comment by qiyuangong** [comment]
Issue fixed by #2505
