### ISSUE TITLE
Orca read file sometimew would report path not exist if don't specify file:/// for local file

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2521]
When I run the Orca pandas read file code on Almaren node, for local file path, I must specify `file:////opt/work/...`, otherwise the error is thrown:
```
2020-07-01 16:53:32 WARN  Utils$:111 - /opt/work/client/kai/rbi_data/sample_data/train doesn't exist!
Traceback (most recent call last):
  File "pandas_backend.py", line 23, in <module>
    orient='columns', lines=True)
  File "/opt/work/client/anaconda3/envs/mxnet-0.8/lib/python3.6/site-packages/zoo/orca/data/pandas/preprocessing.py", line 57, in read_json
    return read_file_spark(context, file_path, "json", **kwargs)
  File "/opt/work/client/anaconda3/envs/mxnet-0.8/lib/python3.6/site-packages/zoo/orca/data/pandas/preprocessing.py", line 109, in read_file_spark
    raise Exception("The file path is invalid/empty or does not include csv/json files")
Exception: The file path is invalid/empty or does not include csv/json files
```
I suppose for most cases just inputting the normal local file path works.
But for the cases that need to specify file:/// to work, the error message is misleading. Shall we handle this? Or we can write some documentations for this.

**Comment by hkvision** [comment]
cc @jason-dai

**Comment by jason-dai** [comment]
The error message is misleading. And why does it need "file:///"? Is it due to pandas?

**Comment by jenniew** [comment]
On the hadoop cluster, if we don't use file:/// prefix, the path would be regards as hdfs path by default. I think we need to add the support for file:///

**Comment by jason-dai** [comment]
> On the hadoop cluster, if we don't use file:/// prefix, the path would be regards as hdfs path by default. I think we need to add the support for file:///

In `read_file_spark`, if there is no prefix, it just uses pandas to read the file, no?

**Comment by hkvision** [comment]
The root cause here is it uses Scala Hadoop FileSystem API to list the local files: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/data/utils.py#L87, which is not reasonable.
Would create a PR to fix this.
