### ISSUE TITLE
init_spark_on_yarn is broken

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2531]
https://github.com/intel-analytics/analytics-zoo/pull/2530
This PR breaks init_spark_on_yarn, 
```
        submit_args = " --driver-class-path " + os.environ["BIGDL_JARS"] + " pyspark-shell "
        print("pyspark_submit_args is: {}".format(submit_args))
        os.environ['PYSPARK_SUBMIT_ARGS'] = submit_args
```
This code will override the submit args of yarn and therefore the conda archives are not taking effect.

**Comment by hkvision** [comment]
Probably change the logic not to directly override the environment variable, but to append to it.
Remove the `--driver-class-path` from init_spark_on_yarn and put it in init_nncontext() only.

**Comment by hkvision** [comment]
Also we had better add yarn into integration to avoid such kind of overlooked errors. @glorysdj @jason-dai

**Comment by jenniew** [comment]
I think we may set submit opts only in init_spark_on_local and init_spark_on_yarn, not in init_nncontext(). If user want to run directly with python, they can use init_spark_on_local and init_spark_on_yarn. init_nncontext is for using spark-submit scripts or start notebook scripts?
