### ISSUE TITLE
Is it necessary to set both --executor-memory and spark.executor.memory?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2565]
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L184
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L169
Why are we setting driver memory in both submit args and spark conf? Is it necessary?

@jason-dai @jenniew

**Comment by hkvision** [comment]
Also why spark_conf here https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L203 is a dictionary not a SparkConf instance?
The implementation in init_spark_on_yarn is messy.

**Comment by jenniew** [comment]
> https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L184
> https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L169
> Why are we setting driver memory in both submit args and spark conf? Is it necessary?
> 
> @jason-dai @jenniew

Do you mean executor memory, executor cores, num-executors? No driver memory setting in L169. I think these executor settings are duplicate, they need to be set in either way.  I think setting "spark.driver.memory" in spark conf is not correct. For client mode, it needs to be set in submit args.

**Comment by jenniew** [comment]
> Also why spark_conf here https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L203 is a dictionary not a SparkConf instance?
> The implementation in init_spark_on_yarn is messy.

In our init_spark_conf(conf=None) implementation, we require 'conf' parameter to be dict, not SparkConf.

**Comment by hkvision** [comment]
> > Also why spark_conf here https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L203 is a dictionary not a SparkConf instance?
> > The implementation in init_spark_on_yarn is messy.
> 
> In our init_spark_conf(conf=None) implementation, we require 'conf' parameter to be dict, not SparkConf.

Then in init_spark_on_yarn, the parameter name should be changed to `conf` not `spark_conf`? Otherwise it is confusing.

**Comment by hkvision** [comment]
> > https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L184
> > https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L169
> > Why are we setting driver memory in both submit args and spark conf? Is it necessary?
> > @jason-dai @jenniew
> 
> Do you mean executor memory, executor cores, num-executors? No driver memory setting in L169. I think these executor settings are duplicate, they need to be set in either way. I think setting "spark.driver.memory" in spark conf is not correct. For client mode, it needs to be set in submit args.

Yeah, I mistyped, executor-memory. So remove them from spark conf and use submit args instead? What about driver memory, set in conf or submit args?

**Comment by jenniew** [comment]
> > > https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L184
> > > https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L169
> > > Why are we setting driver memory in both submit args and spark conf? Is it necessary?
> > > @jason-dai @jenniew
> > 
> > 
> > Do you mean executor memory, executor cores, num-executors? No driver memory setting in L169. I think these executor settings are duplicate, they need to be set in either way. I think setting "spark.driver.memory" in spark conf is not correct. For client mode, it needs to be set in submit args.
> 
> Yeah, I mistyped, executor-memory. So remove them from spark conf and use submit args instead? What about driver memory, set in conf or submit args?

OK. We can move executor settings to submit args. driver memory needs to be set in submit args.

**Comment by jenniew** [comment]
> > > Also why spark_conf here https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/util/spark.py#L203 is a dictionary not a SparkConf instance?
> > > The implementation in init_spark_on_yarn is messy.
> > 
> > 
> > In our init_spark_conf(conf=None) implementation, we require 'conf' parameter to be dict, not SparkConf.
> 
> Then in init_spark_on_yarn, the parameter name should be changed to `conf` not `spark_conf`? Otherwise it is confusing.

Yes, we'd better change to 'conf'.

**Comment by hkvision** [comment]
```
pyspark_submit_args is:  --master spark://172.168.2.180:7077 --num-executors 2 --executor-cores 4 --executor-memory 10g --driver-class-path /opt/anaconda3/envs/standalone_zoo/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-jar-with-dependencies.jar:/opt/anaconda3/envs/standalone_zoo/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.10.0-jar-with-dependencies.jar pyspark-shell

Traceback (most recent call last):
  File "/opt/kai/zoo_standalone.py", line 7, in <module>
    ray_ctx = RayContext(sc=sc, object_store_memory="1g")
  File "/opt/anaconda3/envs/standalone_zoo/lib/python3.6/site-packages/zoo/ray/raycontext.py", line 233, in __init__
    self.num_ray_nodes = int(self.sc.getConf().get("spark.executor.instances"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
For standalone mode, if I only add --num-executors in submit_args, when init RayContext, why it can't find spark.executor.instances in conf? @jenniew 

So to play safe, we still keep executor properties in both conf and submit_args?

**Comment by hkvision** [comment]
Also in standalone and k8s, need to input spark.cores.max, but this is no need in yarn?
