### ISSUE TITLE
HTTP RESTful API cannot get the expected result

### ISSUE THREAD

**Issue by cwpeng-cn** [intel-analytics/analytics-zoo#2571]
I had executed `curl http://172.168.0.109:10020/ ` and can get the result：`welcome to analytics zoo web serving frontend`.
But when using Predict API, I can't get the expected result.  My script is as follows：

**Code:**

```
with open("test_image/cat1.jpeg", "rb") as f:
    base64_data = base64.b64encode(f.read())

post = {}
image = {"image": str(base64_data, 'utf-8')}
instance = [image]
post['instance'] = instance

json_str = json.dumps(post, ensure_ascii=False)

url = 'http://172.168.0.109:10020/predict'
r = requests.post(url, data=json_str)
print(r.text)
```

**Response:**
`{ "error" : "Wrong content format"}  `

**Guide：
https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ClusterServingGuide/ProgrammingGuide.md**
```
curl -d \
'{
  "instances": [
    {
      "image": "/9j/4AAQSkZJRgABAQEASABIAAD/7RcEUGhvdG9za..."
    },
    {
      "image": "/9j/4AAQSkZJRgABAQEASABIAAD/7RcEUGhvdG9za..."
    },
    {
      "image": "/9j/4AAQSkZJRgABAQEASABIAAD/7RcEUGhvdG9za..."
    },
    {
      "image": "/9j/4AAQSkZJRgABAQEASABIAAD/7RcEUGhvdG9za..."
    },
    {
      "image": "/9j/4AAQSkZJRgABAQEASABIAAD/7RcEUGhvdG9za..."
    }
  ]
}' \
-X POST http://host:port/predict
```

**Comment by glorysdj** [comment]
please also paste the content of your json_str.

**Comment by cwpeng-cn** [comment]
> 另请粘贴您的json_str的内容。

{"instance": [{"image": "/9j/4AAQSkZJRgABAQAAAQABAAD/..."}]}

**Comment by glorysdj** [comment]
instance should be instances?

**Comment by cwpeng-cn** [comment]
> instance should be instances?

It was a typo, but something new happened：
`The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.`

Http Server Log:
```
(base) [root@aep-009 TEST]# java -jar analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-20200711.204815-42-http.jar
2020-07-15 21:18:32 INFO  FrontEndApp$:49 - starting with FrontEndAppArguments(0.0.0.0,10020,localhost,6379,serving_stream,result:,1000,0,56,false,100,100)
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - parse arguments time elapsed [0 s, 7 ms].
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - redis-putter initialized. time elapsed [0 s, 1 ms].
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - redis-getter initialized. time elapsed [0 s, 1 ms].
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - queriers initialized. time elapsed [0 s, 131 ms].
2020-07-15 21:18:32 INFO  RedisPutActor:32 - redis-putter retrieve redis connection time elapsed [0 s, 177 ms].
2020-07-15 21:18:32 INFO  RedisPutActor:32 - redis-getter retrieve redis connection time elapsed [0 s, 177 ms].
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - initialize http route time elapsed [0 s, 53 ms].
2020-07-15 21:18:32 INFO  FrontEndApp$:32 - analytics zoo web serving frontend started successfully. time elapsed [0 s, 608 ms].
```

Cluster Serving Log:
```
spark driver memory not set, using default value 4g
spark executor memory not set, using default value 1g
spark num-executors not set, using default value 1
spark executor-cores not set, using default value 4
spark executor-cores not set, using default value 4
Redis maxmemory is not set, using default value 8G
redis server started, please check log in redis.log
OK
OK
OK
redis config maxmemory set to 8G
OK
OK
Using default setting, starting Cluster Serving with Flink backend
OpenvinoNativeLoader load OpenVINO 2020_R2 succeed !
Job has been submitted with JobID bcfd0ac1e78bfdd8ab9df4f6d9a1ed30
```

**Comment by cwpeng-cn** [comment]
> instance should be instances?

Thank you very much!

**Comment by jason-dai** [comment]
Can we provide more details in the error messages? @glorysdj

**Comment by glorysdj** [comment]
in this case, the error massage is ```{ "error" : "Wrong content format"} ``` which indicates the input json is wrong.
in other cases, the http frontend will catch the error and return a 500 http response with the error message to the user.

**Comment by jason-dai** [comment]
> in this case, the error massage is `{ "error" : "Wrong content format"} ` which indicates the input json is wrong.
> in other cases, the http frontend will catch the error and return a 500 http response with the error message to the user.

It is better to provide more details on
(1) what is the expected connects
(2) any keyword that is not recognized

**Comment by glorysdj** [comment]
> (1) what is the expected connects
> (2) any keyword that is not recognized

Sorry, what does expected connects mean? Expected json example?

**Comment by glorysdj** [comment]
We will try to send more info as Jason mentioned to the web front-end user.

**Comment by jason-dai** [comment]
> > (1) what is the expected connects
> > (2) any keyword that is not recognized
> 
> Sorry, what does expected connects mean? Expected json example?

Expected content/format

**Comment by glorysdj** [comment]
> > > (1) what is the expected connects
> > > (2) any keyword that is not recognized
> > 
> > 
> > Sorry, what does expected connects mean? Expected json example?
> 
> Expected content/format

ok, get it.

**Comment by glorysdj** [comment]
fixed by https://github.com/intel-analytics/analytics-zoo/pull/2592
