### ISSUE TITLE
Exception: Java gateway process exited before sending its port number while calling `init_spark_on_local`

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2601]
I try use following address open the 'notebook on branch-0.8-nyc_taxi_dataset.ipynb'
https://nbviewer.jupyter.org/github/intel-analytics/analytics-zoo/blob/branch-0.8/apps/automl/nyc_taxi_dataset.ipynb

The create an new *.ipynb file ,copy the open content to this new one a bit bybit,then run it ,the following error occurred:

........................ code .................................
from zoo import init_spark_on_local
from zoo.ray import RayContext
sc = init_spark_on_local(cores=4)
ray_ctx = RayContext(sc=sc, object_store_memory="1g")
ray_ctx.init()

........................ run error .................................

Current pyspark location is : /home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/init.py
Start to getOrCreate SparkContext

Exception Traceback (most recent call last)
in 
1 from zoo import init_spark_on_local
2 from zoo.ray import RayContext
----> 3 sc = init_spark_on_local(cores=4)
4 ray_ctx = RayContext(sc=sc, object_store_memory="1g")
5 ray_ctx.init()

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/common/nncontext.py in init_spark_on_local(cores, conf, python_location, spark_log_level, redirect_spark_log)
37 redirect_spark_log=redirect_spark_log)
38 return sparkrunner.init_spark_on_local(cores=cores, conf=conf,
---> 39 python_location=python_location)
40
41

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/util/spark.py in init_spark_on_local(self, cores, conf, python_location)
140 master = "local[{}]".format(cores)
141 zoo_conf = init_spark_conf(conf).setMaster(master)
--> 142 sc = init_nncontext(conf=zoo_conf, redirect_spark_log=self.redirect_spark_log)
143 sc.setLogLevel(self.spark_log_level)
144 print("Successfully got a SparkContext")

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/common/nncontext.py in init_nncontext(conf, redirect_spark_log)
116 sc = getOrCreateSparkContext(conf=None, appName=conf)
117 else:
--> 118 sc = getOrCreateSparkContext(conf=conf)
119 check_version()
120 if redirect_spark_log:

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/common/nncontext.py in getOrCreateSparkContext(conf, appName)
136 if appName:
137 spark_conf.setAppName(appName)
--> 138 return SparkContext.getOrCreate(spark_conf)
139 else:
140 return SparkContext.getOrCreate()

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py in getOrCreate(cls, conf)
365 with SparkContext._lock:
366 if SparkContext._active_spark_context is None:
--> 367 SparkContext(conf=conf or SparkConf())
368 return SparkContext._active_spark_context
369

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py in init(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
131 " note this option will be removed in Spark 3.0")
132
--> 133 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
134 try:
135 self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
314 with SparkContext._lock:
315 if not SparkContext._gateway:
--> 316 SparkContext._gateway = gateway or launch_gateway(conf)
317 SparkContext._jvm = SparkContext._gateway.jvm
318

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/java_gateway.py in launch_gateway(conf)
44 :return: a JVM gateway
45 """
---> 46 return _launch_gateway(conf)
47
48

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
106
107 if not os.path.isfile(conn_info_file):
--> 108 raise Exception("Java gateway process exited before sending its port number")
109
110 with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number

**Comment by jason-dai** [comment]
@2017wxyzwxyz can you first try our docker image, as documented in https://analytics-zoo.github.io/master/#gettingstarted/?

**Comment by 2017wxyzwxyz** [comment]
I'm not sure what you mean？Do you want me to check the installed version of the Analytics Zoo ?

I install  Analytics Zoo  by  (ZooAutoml) wxy@SC-202007131929:~$ 'pip install analytics-zoo[automl] '

reference info:   
                           python : 3.6.5 
                           gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

Adding /home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-jar-with-dependencies.jar to BIGDL_JARS

**Comment by 2017wxyzwxyz** [comment]
I'm learning docker image. Thank you for your guidance

**Comment by 2017wxyzwxyz** [comment]
According to the document '8GB memory and 4 CPUs should be a good estimator for most examples'，
‘4 CPUs ’ means multiple physical CPUs or multi-core CPUs ?
My PC is thinkpad ,i5-8250u， 4 cores 8 threads ，8GB memory， can this meet the program running conditions ?

**Comment by 2017wxyzwxyz** [comment]
I don't know at all, when the Analytics Zoo Docker image is running on Windows, is Linux installed first from the Command Prompt, or does it not need，Linux  to be automatically installed in the subsequent operation, or does it not need to care at all? Now I am studying in win10 WSL Ubantu18.04.

**Comment by jason-dai** [comment]
Please run Analytics Zoo on Linux or MacOS. It is not tested on Windows or WSL.

**Comment by 2017wxyzwxyz** [comment]
Ok, let me  do that.

**Comment by yushan111** [comment]
Have your issue been solved yet? If so, I will close it.
