### ISSUE TITLE
About Python compatible packages

### ISSUE THREAD

**Issue by jonatasfreitasv** [intel-analytics/analytics-zoo#2618]
**Have doc about Python compatible packages versions?**
ray, tensorflow, sklearn, featuretools

**Comment by Le-Zheng** [comment]
Hi, we are supporting `ray: 0.8.6`, `tensorflow: 1.15.0`,  `scikit-learn: 0.22.2.post1` and `featuretools: 0.13.4`.
And thanks for asking. We will indeed add docs soon.

**Comment by jonatasfreitasv** [comment]
Thx @Le-Zheng!

**Comment by hkvision** [comment]
@jonatasfreitasv You can directly `pip install analytics-zoo[automl]` to install all these dependencies with our requirement satisfied.
