### ISSUE TITLE
When Run 'nyc_taxi_dataset.ipynb'  occurred  ‘RuntimeError’ !

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2621]
I test whether the installation is successful or not, according to the Example code:

import zoo
from zoo.common.nncontext import *
from zoo.pipeline.api.keras.models import *
from zoo.pipeline.api.keras.layers import *

# Get the current Analytics Zoo version
zoo.__version__
# Create a SparkContext and initialize the BigDL engine.
sc = init_nncontext()
# Create a Sequential model containing a Dense layer.
model = Sequential()
model.add(Dense(8, input_shape=(10, )))
   
that OK!

Then  run 'nyc_taxi_dataset.ipynb'  <github/intel-analytics/analytics-zoo/blob/branch-0.8/apps/automl/nyc_taxi_dataset.ipynb>,
......................................................................................................
Training completed.
CPU times: user 4.38 s, sys: 531 ms, total: 4.91 s
Wall time: 49.4 s
......................................................................................................
But the next step was wrong  as bellow:

# predict test_df with the best trial
pred_df = pipeline.predict(test_df)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-69c6146789aa> in <module>
      1 # predict test_df with the best trial
----> 2 pred_df = pipeline.predict(test_df)

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/automl/pipeline/time_sequence.py in predict(self, input_df)
    174         :return:
    175         """
--> 176         x, _ = self.feature_transformers.transform(input_df, is_train=False)
    177         y_pred = self.model.predict(x)
    178         y_output = self.feature_transformers.post_processing(input_df, y_pred, is_train=False)

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/automl/feature/time_sequence.py in transform(self, input_df, is_train)
    196                 output_y = None
    197         else:
--> 198             output_x, output_y = self._transform(input_df, mode)
    199         return output_x, output_y
    200 

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/automl/feature/time_sequence.py in _transform(self, input_df, mode)
    147         feature_data = self._get_features(input_df, self.config)
    148         # select and standardize data
--> 149         data_n = self._scale(feature_data)
    150         if mode == 'val':
    151             (x, y) = self._roll_train(data_n,

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/automl/feature/time_sequence.py in _scale(self, data)
    507         :return:
    508         """
--> 509         np_scaled = self.scaler.transform(data)
    510         data_s = pd.DataFrame(np_scaled)
    511         return data_s

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/sklearn/preprocessing/_data.py in transform(self, X, copy)
    792                                 accept_sparse='csr', copy=copy,
    793                                 estimator=self, dtype=FLOAT_DTYPES,
--> 794                                 force_all_finite='allow-nan')
    795 
    796         if sparse.issparse(X):

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/sklearn/base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    434 
    435         if check_params.get('ensure_2d', True):
--> 436             self._check_n_features(X, reset=reset)
    437 
    438         return out

~/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/sklearn/base.py in _check_n_features(self, X, reset)
    371             if not hasattr(self, 'n_features_in_'):
    372                 raise RuntimeError(
--> 373                     "The reset parameter is False but there is no "
    374                     "n_features_in_ attribute. Is this estimator fitted?"
    375                 )

RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?

**Comment by 2017wxyzwxyz** [comment]
>>> zoo.__version__
'0.8.1'

**Comment by 2017wxyzwxyz** [comment]
Perhaps the following results of running the example code can help diagnosis error:

>>> from zoo.common.nncontext import *
>>> from zoo.pipeline.api.keras.models import *
>>> from zoo.pipeline.api.keras.layers import *
>>> zoo.__version__
'0.8.1'
>>> sc = init_nncontext()
2020-07-26 15:12:13 WARN  Utils:66 - Your hostname, SC-202007131929 resolves to a loopback address: 127.0.1.1; using 192.168.1.6 instead (on interface wifi0)
2020-07-26 15:12:13 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2020-07-26 15:12:13 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

User settings:

   KMP_AFFINITY=granularity=fine,compact,1,0
   KMP_BLOCKTIME=0
   KMP_SETTINGS=1
   OMP_NUM_THREADS=1

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_HAND_THREAD=false
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=false
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_FORKJOIN_FRAMES=true
   KMP_FORKJOIN_FRAMES_MODE=3
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_INIT_WAIT=2048
   KMP_ITT_PREPARE_DELAY=0
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NEXT_WAIT=1024
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_PATTERN='hyper,hyper'
   KMP_REDUCTION_BARRIER='1,1'
   KMP_REDUCTION_BARRIER_PATTERN='hyper,hyper'
   KMP_SCHEDULE='static,balanced;guided,iterative'
   KMP_SETTINGS=true
   KMP_SPIN_BACKOFF_PARAMS='4096,100'
   KMP_STACKOFFSET=64
   KMP_STACKPAD=0
   KMP_STACKSIZE=4M
   KMP_STORAGE_MAP=false
   KMP_TASKING=2
   KMP_TASKLOOP_MIN_TASKS=0
   KMP_TASK_STEALING_CONSTRAINT=1
   KMP_TEAMS_THREAD_LIMIT=8
   KMP_TOPOLOGY_METHOD=all
   KMP_USER_LEVEL_MWAIT=false
   KMP_VERSION=false
   KMP_WARNINGS=true
   OMP_AFFINITY_FORMAT='OMP: pid %P tid %T thread %n bound to OS proc set {%a}'
   OMP_ALLOCATOR=omp_default_mem_alloc
   OMP_CANCELLATION=false
   OMP_DEFAULT_DEVICE=0
   OMP_DISPLAY_AFFINITY=false
   OMP_DISPLAY_ENV=false
   OMP_DYNAMIC=false
   OMP_MAX_ACTIVE_LEVELS=2147483647
   OMP_MAX_TASK_PRIORITY=0
   OMP_NESTED=false
   OMP_NUM_THREADS='1'
   OMP_PLACES: value is not defined
   OMP_PROC_BIND='intel'
   OMP_SCHEDULE='static'
   OMP_STACKSIZE=4M
   OMP_TARGET_OFFLOAD=DEFAULT
   OMP_THREAD_LIMIT=2147483647
   OMP_TOOL=enabled
   OMP_TOOL_LIBRARIES: value is not defined
   OMP_WAIT_POLICY=PASSIVE
   KMP_AFFINITY='noverbose,warnings,respect,granularity=fine,compact,1,0'

cls.getname: com.intel.analytics.bigdl.python.api.Sample
BigDLBasePickler registering: bigdl.util.common  Sample
cls.getname: com.intel.analytics.bigdl.python.api.EvaluatedResult
BigDLBasePickler registering: bigdl.util.common  EvaluatedResult
cls.getname: com.intel.analytics.bigdl.python.api.JTensor
BigDLBasePickler registering: bigdl.util.common  JTensor
cls.getname: com.intel.analytics.bigdl.python.api.JActivity
BigDLBasePickler registering: bigdl.util.common  JActivity
>>> model = Sequential()
creating: createZooKerasSequential
>>> model.add(Dense(8, input_shape=(10, )))
creating: createZooKerasDense
<zoo.pipeline.api.keras.models.Sequential object at 0x7f008d040518>
>>>

**Comment by yushan111** [comment]
what is your sklearn  version?

**Comment by 2017wxyzwxyz** [comment]
>>> import sklearn
>>> print("Sklearn verion is {}".format(sklearn.__version__))
Sklearn verion is 0.23.1
>>>

**Comment by yushan111** [comment]
You may try sklearn version <=0.22. We haven't support sklearn version of 0.23 yet. We will update docs.

**Comment by 2017wxyzwxyz** [comment]
Thinks for your help!!
The program is now running correctly ！
But it seems that the accuracy of the test is not as high as it was when I saw the introduction.
How to print out the difference (value) between the actual value and the test predicted value?
