### ISSUE TITLE
How  to  call function to calculate  difference  value  between the actual value and the test predicted value, When Run 'nyc_taxi_dataset.ipynb' 

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2634]
Is there a ready-made function to print out the absolute difference (value) between the actual value and the test predicted value?

  This is very useful In some cases.

**Comment by qiuxin2012** [comment]
Maybe you can change the function `plot_result` to plot the absolute difference between `pred_value` and `true_value`.

**Comment by 2017wxyzwxyz** [comment]
think you !
