### ISSUE TITLE
Is that correct ?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2637]
In the tutorial ''nyc_taxi_dataset.ipynb'',after Train and validation when Test, ' pred_df.head(5) ' is the five future  'virtual' predict value  of  'test_df[50:55]' ，is  this understanding   correct ?

**Comment by yushan111** [comment]
I am sorry that we failed to keep the consistency after several modifications. And we have fixed that in [notebook of master](https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb). pred_df.head(5) should correspond to test_df[look_back: look_back + 5]. We do automatically search according to the recipe passed to fit: `recipe=RandomRecipe(look_back=(2, 4)))`, and the best value is 3 as you can see in the log of tsp.fit() as `past_seq_len : 3`. You can also get the best configs searched through `pipeline.describe()`,  where "pipeline" is the return value of `tsp.fit()`. So the correct value should be test_df[3:8].
