### ISSUE TITLE
Inconsistent API for Orca PyTorch based on horovod and torch.distributed

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2645]
If we want PyTorchTrainer to have the same API as Estimator, probably we need to copy much code from RaySGD.
Doubt whether it is necessary to make the efforts.
But currently the API for these two backends are inconsistent.

**Comment by jason-dai** [comment]
> If we want PyTorchTrainer to have the same API as Estimator, probably we need to copy much code from RaySGD.
> Doubt whether it is necessary to make the efforts.
> But currently the API for these two backends are inconsistent.

Let's focus on Horovd at this moment.
