### ISSUE TITLE
Link for Databricks doc not working?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2648]
https://analytics-zoo.github.io/master/#ProgrammingGuide/AnalyticsZoo-on-Databricks/#Prerequisites

Prerequisites
Installing Analytics Zoo libraries
Setting Spark configuration
Running Analytics Zoo notebook on Databricks

The links are not working?
probably change #Prerequisites -> #prerequisites
Capitalized letters can't be recongized.

**Comment by Le-Zheng** [comment]
Got it.
