### ISSUE TITLE
Now Could automl  tutoiral  'nyc_taxi_dataset.ipynb'  run correctly ?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2652]
I  download  the latest nightly build wheels, then install it  by  'pip install analytics_zoo-*-py2.py3-none-*_x86_64.whl[automl]' ,
Could automl  tutoiral  'nyc_taxi_dataset.ipynb'  run correctly ?

**Comment by dding3** [comment]
Close the issue as it's duplicate with https://github.com/intel-analytics/analytics-zoo/issues/2654. 

Also for general questions, please ask in the user group https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/bigdl-user-group.
