### ISSUE TITLE
Run the matser tutoiral 'nyc_taxi_dataset.ipynb' error ! ?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2653]
I run  pip install analytics_zoo-0.9.0.dev0-20200731-py2.py3-none-manylinux1_x86_64.whl[automl] successfully!

But run the matser tutoiral 'nyc_taxi_dataset.ipynb' error as below:

........................................................................................................................................................
# build time sequence predictor
from zoo.automl.regression.time_sequence_predictor import *

# you need to specify the name of datetime column and target column
# The default names are "timestamp" and "value" respectively.
tsp = TimeSequencePredictor(dt_col="timestamp",
                            target_col="value",
                            extra_features_col=None)
........................................................................................................................................................

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-991f4d6078eb> in <module>
      1 # build time sequence predictor
----> 2 from zoo.automl.regression.time_sequence_predictor import *
      3 
      4 # you need to specify the name of datetime column and target column
      5 # The default names are "timestamp" and "value" respectively.

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in <module>
     25 
     26 from zoo.automl.search.abstract import *
---> 27 from zoo.automl.search.RayTuneSearchEngine import RayTuneSearchEngine
     28 from zoo.automl.common.metrics import Evaluator
     29 from zoo.automl.feature.time_sequence import TimeSequenceFeatureTransformer

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py in <module>
     19 from copy import copy, deepcopy
     20 
---> 21 from zoo.automl.model import TimeSequenceModel
     22 from zoo.automl.search.abstract import *
     23 from zoo.automl.common.util import *

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/__init__.py in <module>
     19 from .Seq2Seq import *
     20 from .time_sequence import *
---> 21 from .tcmf_model import *

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf_model.py in <module>
     15 from abc import ABCMeta, abstractmethod
     16 
---> 17 from zoo.automl.model.tcmf import DeepGLO
     18 from zoo.automl.common.metrics import Evaluator
     19 from zoo.automl.model.abstract import BaseModel

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from .DeepGLO import DeepGLO

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf/DeepGLO.py in <module>
     47 
     48 from __future__ import print_function
---> 49 import torch
     50 import numpy as np
     51 import pandas as pd

ModuleNotFoundError: No module named 'torch'

**Comment by hkvision** [comment]
The model is defined in PyTorch and thus please pip install it first.

**Comment by 2017wxyzwxyz** [comment]
thinks!
