### ISSUE TITLE
Run the matser tutoiral 'nyc_taxi_dataset.ipynb'  new error 

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2654]
I run pip install analytics_zoo-0.9.0.dev0-20200731-py2.py3-none-manylinux1_x86_64.whl[automl] successfully!

 
When I install pytorch   Successfully, run 'nyc_taxi_dataset.ipynb'  new error occur:
 
(zoo_automl) wxy@SC-202007131929:/$ pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp36-cp36m-linux_x86_64.whl
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting torch==0.1.11.post5
  Downloading http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp36-cp36m-linux_x86_64.whl (475.1 MB)
     |████████████████████████████████| 475.1 MB 4.1 MB/s
Requirement already satisfied: pyyaml in /home/wxy/anaconda3/envs/zoo_automl/lib/python3.6/site-packages (from torch==0.1.11.post5) (5.3.1)
Installing collected packages: torch
Successfully installed torch-0.1.11.post5

But run the matser tutoiral 'nyc_taxi_dataset.ipynb' error as below:

........................................................................................................................................................

# build time sequence predictor
from zoo.automl.regression.time_sequence_predictor import *

# you need to specify the name of datetime column and target column
# The default names are "timestamp" and "value" respectively.
tsp = TimeSequencePredictor(dt_col="timestamp",
                            target_col="value",
                            extra_features_col=None)

........................................................................................................................................................

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-991f4d6078eb> in <module>
      1 # build time sequence predictor
----> 2 from zoo.automl.regression.time_sequence_predictor import *
      3 
      4 # you need to specify the name of datetime column and target column
      5 # The default names are "timestamp" and "value" respectively.

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in <module>
     25 
     26 from zoo.automl.search.abstract import *
---> 27 from zoo.automl.search.RayTuneSearchEngine import RayTuneSearchEngine
     28 from zoo.automl.common.metrics import Evaluator
     29 from zoo.automl.feature.time_sequence import TimeSequenceFeatureTransformer

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py in <module>
     19 from copy import copy, deepcopy
     20 
---> 21 from zoo.automl.model import TimeSequenceModel
     22 from zoo.automl.search.abstract import *
     23 from zoo.automl.common.util import *

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/__init__.py in <module>
     19 from .Seq2Seq import *
     20 from .time_sequence import *
---> 21 from .tcmf_model import *

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf_model.py in <module>
     15 from abc import ABCMeta, abstractmethod
     16 
---> 17 from zoo.automl.model.tcmf import DeepGLO
     18 from zoo.automl.common.metrics import Evaluator
     19 from zoo.automl.model.abstract import BaseModel

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from .DeepGLO import DeepGLO

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf/DeepGLO.py in <module>
     56 
     57 from zoo.automl.model.tcmf.data_loader import DataLoader
---> 58 from zoo.automl.model.tcmf.local_model import TemporalConvNet, LocalModel
     59 from zoo.automl.model.tcmf.time import TimeCovariates
     60 

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/model/tcmf/local_model.py in <module>
     54 import torch.optim as optim
     55 from torch.autograd import Variable
---> 56 from torch.nn.utils import weight_norm
     57 
     58 from zoo.automl.model.tcmf.data_loader import DataLoader

ImportError: cannot import name 'weight_norm'

**Comment by dding3** [comment]
The error is ""ImportError: cannot import name 'weight_norm'", thrown from "from torch.nn.utils import weight_norm", suppose the installed torch version doesn't have 'weight_norm' api.

torch-0.1.11.post5 seems a bit lower version. Could you please try a higher torch version. eg. "pip install torch" to install torch. I tried installed torch-1.6.0 and can load the module successfully.

**Comment by shane-huang** [comment]
resolved in #2657

**Comment by helenlly** [comment]
@2017wxyzwxyz  thanks for your questions. since the fix is available, we'd like to close this issue. If any more questions, pls free to open it.
