### ISSUE TITLE
Run the matser tutoiral 'nyc_taxi_dataset.ipynb' error：TuneError: ('Trials did not complete', [train_func_00000, train_func_00001, train_func_00002])

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2657]
because problem #2653, I  install pytorch 0.1.11, lead to error --ImportError: cannot import name 'weight_norm' #2654
then I  install pytorch 1.5.0+cpu, after run tutoiral，Repeat error  #2621,  but  train over correctly !

Then  I   uninstall scikit-learn 0.23.0  and  install scikit-learn 0.20.0 ,after run tutoiral error as below:
---------------------------------------------------------------------------
%%time
# fit train_df and validate with val_df, return the best trial as pipeline.
# the default recipe is SmokeRecipe,which runs one epoch and one iteration with only 1 random sample.
# you can change recipe by define `recipe` in `fit`. The recipes you can choose are SmokeRecipe, RandomRecipe, LSTMGridRandomRecipe, GridRandomRecipe and BayesRecipe.
look_back_single = 5
pipeline = tsp.fit(train_df,
                   validation_df=val_df,
                   metric="mse",
                   recipe=LSTMGridRandomRecipe(
                              num_rand_samples=1,
                              epochs=2,
                              look_back=look_back_single, 
                              batch_size=[64]))
print("Training completed.")
---------------------------------------------------------------------------

Trial name | status | loc | batch_size | dropout_2 | lr | lstm_1_units | lstm_2_units | selected_features
-- | -- | -- | -- | -- | -- | -- | -- | --
train_func_00000 | ERROR |   | 64 | 0.313359 | 0.00288121 | 64 | 16 | ["HOUR(timestamp)", "MONTH(timestamp)", "WEEKDAY(timestamp)"]
train_func_00001 | ERROR |   | 64 | 0.231211 | 0.00575162 | 64 | 32 | ["IS_BUSY_HOURS(timestamp)", "IS_AWAKE(timestamp)", "HOUR(timestamp)", "MONTH(timestamp)", "WEEKDAY(timestamp)", "DAY(timestamp)"]
train_func_00002 | ERROR |   | 64 | 0.23551 | 0.00166562 | 128 | 64 | ["IS_AWAKE(timestamp)", "MONTH(timestamp)", "HOUR(timestamp)", "WEEKDAY(timestamp)"]

TuneError                                 Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in fit(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, distributed, hdfs_url)
    126             mc=mc,
    127             resources_per_trial=resources_per_trial,
--> 128             remote_dir=remote_dir)
    129         return self.pipeline
    130 

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in _hp_search(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, remote_dir)
    271                          num_samples=num_samples)
    272         # searcher.test_run()
--> 273         analysis = searcher.run()
    274 
    275         pipeline = self._make_pipeline(analysis,

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py in run(self)
    125                 resources_per_trial=self.resources_per_trail,
    126                 verbose=1,
--> 127                 reuse_actors=True
    128             )
    129         else:

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/ray/tune/tune.py in run(run_or_experiment, name, stop, config, resources_per_trial, num_samples, local_dir, upload_dir, trial_name_creator, loggers, sync_to_cloud, sync_to_driver, checkpoint_freq, checkpoint_at_end, sync_on_checkpoint, keep_checkpoints_num, checkpoint_score_attr, global_checkpoint_period, export_formats, max_failures, fail_fast, restore, search_alg, scheduler, with_server, server_port, verbose, progress_reporter, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, return_trials, ray_auto_init)
    340     if incomplete_trials:
    341         if raise_on_failed_trial:
--> 342             raise TuneError("Trials did not complete", incomplete_trials)
    343         else:
    344             logger.error("Trials did not complete: %s", incomplete_trials)

TuneError: ('Trials did not complete', [train_func_00000, train_func_00001, train_func_00002])
---------------------------------------------------------------------------

Then  I   uninstall scikit-learn 0.20.0  and  install scikit-learn 0.22.0 ,after run tutoiral error is similar !!

**Comment by 2017wxyzwxyz** [comment]
Then I uninstall torch-1.5.0 and install torch-1.6.0 ,after run tutoiral error is similar as below !!


---------------------------------------------------------------------------
TuneError                                 Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in fit(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, distributed, hdfs_url)
    126             mc=mc,
    127             resources_per_trial=resources_per_trial,
--> 128             remote_dir=remote_dir)
    129         return self.pipeline
    130 

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py in _hp_search(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, remote_dir)
    271                          num_samples=num_samples)
    272         # searcher.test_run()
--> 273         analysis = searcher.run()
    274 
    275         pipeline = self._make_pipeline(analysis,

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py in run(self)
    125                 resources_per_trial=self.resources_per_trail,
    126                 verbose=1,
--> 127                 reuse_actors=True
    128             )
    129         else:

~/anaconda3/envs/zoo_automl/lib/python3.6/site-packages/ray/tune/tune.py in run(run_or_experiment, name, stop, config, resources_per_trial, num_samples, local_dir, upload_dir, trial_name_creator, loggers, sync_to_cloud, sync_to_driver, checkpoint_freq, checkpoint_at_end, sync_on_checkpoint, keep_checkpoints_num, checkpoint_score_attr, global_checkpoint_period, export_formats, max_failures, fail_fast, restore, search_alg, scheduler, with_server, server_port, verbose, progress_reporter, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, return_trials, ray_auto_init)
    340     if incomplete_trials:
    341         if raise_on_failed_trial:
--> 342             raise TuneError("Trials did not complete", incomplete_trials)
    343         else:
    344             logger.error("Trials did not complete: %s", incomplete_trials)

TuneError: ('Trials did not complete', [train_func_00000, train_func_00001, train_func_00002])

.................................................................................
pred_df = pipeline.predict(test_df)
.................................................................................
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-69c6146789aa> in <module>
      1 # predict test_df with the best trial
----> 2 pred_df = pipeline.predict(test_df)

NameError: name 'pipeline' is not defined

**Comment by 2017wxyzwxyz** [comment]
I create a new clean virtual environment, then install all the necessary packages in turn, and then run the matser tutoiral 'nyc_taxi_dataset.ipynb', and it runs correctly ！！

**Comment by shane-huang** [comment]
Seems there's no issues right now.

**Comment by helenlly** [comment]
@2017wxyzwxyz  thanks for your questions. since the fix is available, we'd like to close this issue. If any more questions, pls free to re-open it.
