### ISSUE TITLE
add support page in doc website with support info

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2673]
e.g. support  Colab  or not?  which pytorch/ ray/..... version  does AZ support? 

refer to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/bigdl-user-group/jiahaoyu04@gmail.com%7Csort:date/bigdl-user-group/b5yCGWIBjpk/PhCF56d-BAAJ

**Comment by helenlly** [comment]
@Le-Zheng , can we close the issue?

**Comment by Le-Zheng** [comment]
> @Le-Zheng , can we close the issue?

Sure
