### ISSUE TITLE
update python doc with " train_on_batch is not distributed ...."

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2674]
refer to [Is train_on_batch() from KerasModel designed for distributed training?](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/bigdl-user-group/jiahaoyu04@gmail.com%7Csort:date/bigdl-user-group/SrahK4mJmLM/hMm3wBQ8AgAJ)

**Comment by helenlly** [comment]
@yangw1234 any updates?

**Comment by yangw1234** [comment]
api is deprecated
