### ISSUE TITLE
I want to study and apply automl's time series module in depth. Please give some suggestions on how to adjust the parameters to improve the accuracy？

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2688]
I want to study and apply automl's time series module in depth. Please give some suggestions on how to adjust the parameters to improve the accuracy？

Because the prediction error after running with my actual data is twice as large as that of tutorial   'nyc_taxi_dataset.ipynb'.

**Comment by dding3** [comment]
We support ray tune search engine in our automl support which will search the best hyperparameters for you. Please refer the nyc_taxi notebook. Also you can refer https://analytics-zoo.github.io/master/#ProgrammingGuide/AutoML/forecasting/ for details about automl time series. And you may want to take a look at our talk of 'automl time series for forcasting using Ray and Analytics Zoo' in Spark summit. https://www.youtube.com/watch?v=seSKYss7T7M

**Comment by helenlly** [comment]
@2017wxyzwxyz   thanks for your question. we will close this issue since no updates for a few days. If  you have any questions on this issue, free to re-open it, thanks.
