### ISSUE TITLE
LeakyReLU

### ISSUE THREAD

**Issue by m-developer96** [intel-analytics/analytics-zoo#2695]
Hi
I'm using Analytics-zoo `Keras style API` and I want to add a `LeakyRelu` with `alpah=0.3`. I read the documentation and checked the available activation function but I can't find what I want.
In `RReLU`'s doc it said that `If l == u, a RReLU essentially becomes a LeakyReLU` but when I put the same number for them I got this error:
```
An error occurred while calling o498.add.
: java.lang.IllegalArgumentException: requirement failed
```
And I can't find alpha argument in `PReLU`.

How can I implement a `LeakyRelu` layer with alpha=0.3?

**Comment by qiuxin2012** [comment]
Please try LeakyRelu,
Python API:
https://github.com/intel-analytics/analytics-zoo/blob/e5b81233f5862c4007f5e099eba82a6632c8ea13/pyzoo/zoo/pipeline/api/keras/layers/advanced_activations.py#L26

Scala API: 
https://github.com/intel-analytics/analytics-zoo/blob/e5b81233f5862c4007f5e099eba82a6632c8ea13/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/LeakyReLU.scala#L39

**Comment by m-developer96** [comment]
@qiuxin2012 
Thank you so much :)

**Comment by m-developer96** [comment]
@qiuxin2012
I just have one question and appreciate you helping me.
It isn't possible to define a method for initializing our layer's parameter in Analytics-zoo(Keras style API)?

**Comment by hkvision** [comment]
@m-developer96 
You have the option to choose the init method of a layer for most of the layers. For example, see here for the convolution layers: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/pipeline/api/keras/layers/convolutional.py#L38
The parameter is the same as keras.

**Comment by m-developer96** [comment]
@hkvision 
Thank you :)

**Comment by hkvision** [comment]
You are welcome. I'll close this issue first. Feel free to tell us if you have other problems.
