### ISSUE TITLE
RNN model based on dataframe in Analytics-zoo

### ISSUE THREAD

**Issue by m-developer96** [intel-analytics/analytics-zoo#2723]
Hi!

Is it possible to create a RNN model based on dataframe (and not on rdd)  for text classification in Analytics-zoo ?
Something like [this](https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/nnframes/imageTransferLearning)

**Comment by hkvision** [comment]
I think you can pass any Analytics Zoo model to NNClassifier to have a try.

**Comment by helenlly** [comment]
@m-developer96 thanks for your question.  pls let us know if any more questions. If no question, we will close it.
