### ISSUE TITLE
deploy hyperzoo dockerfile filename not matched

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2725]
filename not matched:  zoo/serving/quick_start.py

jenkins liink:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Deploy-Docker/580/console

dockerfile link:
https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/Dockerfile

**Comment by glorysdj** [comment]
I think @Litchilitchy has refactored the cluster serving part scripts, please modify the hyper zoo dockerfile for that.
