### ISSUE TITLE
UT: Scala test failed on MAC

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2726]
com.intel.analytics.zoo.pipeline.nnframes.XgboostTrainSpec.XGBRegressor train should work
Error Message:
the nthread configuration (4) must be no larger than spark.task.cpus (1)

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-SCALA-MAC/140/console

**Comment by glorysdj** [comment]
@pinggao187 please verify it on MAC
