### ISSUE TITLE
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Wercurial** [intel-analytics/analytics-zoo#2727]
Hello, when I use tf2.0, prompt if the question error, by looking to find tf.contrib in version 2.0 has been removed, please ask "slim = tf.contrib.slim" do you have an alternative?

**Comment by yangw1234** [comment]
Hi @Wercurial , TensorFlow 2.0 is not supported right now. Could you try TF 1.15? We are currently looking into options to support TF 2.0.

**Comment by Wercurial** [comment]
hi @yangw1234 ,thanks for your answer,By using tf_slim this package, I've solved this problem in tf2.0, but when I use tf1.5 there's a new problem and I don't know if you can help me.The questions are as follows.
```
......
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/miniconda3/envs/azoo/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o78.estimatorTrainMiniBatch.
: java.lang.VerifyError: (class: org/tensorflow/util/Event$Builder, method: getLogMessageFieldBuilder signature: ()Lcom/intel/analytics/bigdl/shaded/protobuf/SingleFieldBuilderV3;) Incompatible argument to function
        at org.tensorflow.util.Event.toBuilder(Event.java:694)
        at org.tensorflow.util.Event.newBuilder(Event.java:688)
......
```
