### ISSUE TITLE
UT test failed on MAC

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2741]
com.intel.analytics.zoo.pipeline.inference.EncryptSpec.plain text should be encrypted
Error Message:
Illegal key size

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.1-SCALA-MAC/103/console

**Comment by glorysdj** [comment]
before Java 8 u162, we need download security policy jar to ${java.home}/jre/lib/security/

please refer to
https://blog.csdn.net/wangjunjun2008/article/details/50847426
https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

@pinggao187 please scp related jars to mac.
