### ISSUE TITLE
Pytorch version: 1.1.0 torchvision: 2.2.0 doens't existis

### ISSUE THREAD

**Issue by magic20191** [intel-analytics/analytics-zoo#2750]
i cant find  torchvision: 2.2.0 ,Is it torchvision 0.2.2  ?
![image](https://user-images.githubusercontent.com/50441790/90519829-24b14800-e19b-11ea-82d9-bba954af7050.png)

**Comment by hkvision** [comment]
The documentation is wrong. We will update is ASAP. Thank you so much for pointing out.

**Comment by hkvision** [comment]
You may try torch 1.5.0; torchvision 0.6.0 or a bit lower versions first.

**Comment by magic20191** [comment]
Can you tell me the latest version of PyTorch that passed the test?thank you very much
