### ISSUE TITLE
Is SparkML available in Analytics Zoo?

### ISSUE THREAD

**Issue by WangHeguan** [intel-analytics/analytics-zoo#2756]

**Comment by qiuxin2012** [comment]
See https://analytics-zoo.github.io/master/#ProgrammingGuide/nnframes/ for details.

**Comment by WangHeguan** [comment]
@qiuxin2012 xiexie

**Comment by helenlly** [comment]
@WangHeguan thanks for your question. Do you have any more questions on this issue?  If no, we will close this issue.
