### ISSUE TITLE
Call the models generated by Keras, PyTorch, and MXNet training for inference

### ISSUE THREAD

**Issue by WangHeguan** [intel-analytics/analytics-zoo#2767]
Analytics zoo currently only supports inferences using the Analytics Zoo, Caffe, Tensorflow and OpenVINO models, but now I want to call the models generated by Keras, PyTorch, and MXNet training for inference. Is there any way?

**Comment by glorysdj** [comment]
Model inference for PyTorch models are in development progress, we will support this soon.
MXNet models can be converted to OpenVINO IR, so you can load them as OpenVINO for now.
Keras models may also be saved as TF format, and use analytics zoo InferenceModel to load them for now.

**Comment by helenlly** [comment]
@WangHeguan  thanks for your question.  Do you have more question on this issue? if yes, pls let us know;  if no, we will go ahead to close it.

**Comment by WangHeguan** [comment]
@helenlly ok
