### ISSUE TITLE
How to perform a distributed training model on CentOS?

### ISSUE THREAD

**Issue by WangHeguan** [intel-analytics/analytics-zoo#2781]

**Comment by WangHeguan** [comment]
Analytics-Zoo provides a set APIs for running TensorFlow model on Spark in a distributed fashion.

Remarks:

You need to install tensorflow==1.15.0 on your driver node.
Your operating system (OS) is required to be one of the following 64-bit systems: Ubuntu 16.04 or later and macOS 10.12.6 or later.
To run on other systems, you need to manually compile the TensorFlow source code. Instructions can be found here.

**Comment by yangw1234** [comment]
@WangHeguan 
This is the official support statement of TensorFlow, (see the install page on TensorFlow website).
You can try it on CentOS，it probably works out of box, but we cannot guarantee it and neither TensorFlow itself.
