### ISSUE TITLE
Jenkins test: Python ExampleTests  failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2785]
[ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala:32: value CacheV1 is not a member of object com.intel.analytics.bigdl.optim.DistriOptimizer
[ERROR] import com.intel.analytics.bigdl.optim.DistriOptimizer.{Cache, CacheV1}

[ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/CaffeLoader.scala:25: object shaded is not a member of package com.intel.analytics
[ERROR] import com.intel.analytics.shaded.protobuf_v_3_5_1.TextFormat.ParseException

[ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/CaffeLoader.scala:41: not found: type GeneratedMessage
[ERROR]   def convertor(layer: GeneratedMessage): Seq[ModuleNode[T]]

jenkins link: 
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-py36/117/console

**Comment by Le-Zheng** [comment]
> [ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala:32: value CacheV1 is not a member of object com.intel.analytics.bigdl.optim.DistriOptimizer
> [ERROR] import com.intel.analytics.bigdl.optim.DistriOptimizer.{Cache, CacheV1}
> 
> [ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/CaffeLoader.scala:25: object shaded is not a member of package com.intel.analytics
> [ERROR] import com.intel.analytics.shaded.protobuf_v_3_5_1.TextFormat.ParseException
> 
> [ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/CaffeLoader.scala:41: not found: type GeneratedMessage
> [ERROR] def convertor(layer: GeneratedMessage): Seq[ModuleNode[T]]
> 
> jenkins link:
> http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-py36/117/console

This is because the job is not switched to the new BigDL version. Wait for the results of re-running in several minutes.

**Comment by Le-Zheng** [comment]
Jenkins passed http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-py36/118/
