### ISSUE TITLE
Add init_spark_on_yarn tests on Jenkins

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2789]
An old issue. Better get this planned to test on yarn. @glorysdj @pinggao18

**Comment by glorysdj** [comment]
need to add to integration tests?

**Comment by hkvision** [comment]
Yeah. Currently init_spark_on_yarn is only tested manually, no guarantee it always works.

**Comment by glorysdj** [comment]
ok, you can add a test in Yarn Test Suite in below file
https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/test/integration-test.robot

we will prepare the integration env to test it.

**Comment by hkvision** [comment]
Can this script work with Python?

**Comment by glorysdj** [comment]
no... @Le-Zheng what's the status of python integration tests?

**Comment by Le-Zheng** [comment]
> no... @Le-Zheng what's the status of python integration tests?

We already have an ubuntu 18 yarn cluster. It supports to run `.sh`  test script.  Let me confirm again.

**Comment by Le-Zheng** [comment]
> > no... @Le-Zheng what's the status of python integration tests?
> 
> We already have an ubuntu 18 yarn cluster. It supports to run `.sh` test script. Let me confirm again.

Let me work with @pinggao18 to enable this Jenkins test.

**Comment by Le-Zheng** [comment]
@hkvision We are going to prepare a test script. Could you give us a list of which tests need to be added?

**Comment by hkvision** [comment]
What about choosing one or two examples in orca first? https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/orca/learn

**Comment by Le-Zheng** [comment]
PR https://github.com/intel-analytics/analytics-zoo/pull/3199 opened
