### ISSUE TITLE
Module size will be larger than 1 when loading the TextClassifier model

### ISSUE THREAD

**Issue by edieYoung** [intel-analytics/analytics-zoo#279]
When loading a textClaasifier model locally and do text prediction, usually we just call the method loadModel and predict like this: 
`val textClassificationModel =  TextClassifier.loadModel[Float]("file:///home/yidiyang/workspace/model/text.bigdl") 
val results = textClassificationModel.predict(sampleRDD).collect()(0)`

However it will throw an error :  module size should be 1 instead of 2

Only when adding these codes  before loading can it works (can the module size be 1):
`val model = TextClassifier(classNum, tokenLength, sequenceLength,
          param.encoder, param.encoderOutputDim)
      `

**Comment by hkvision** [comment]
Loading a KerasNet Sequential or Graph will both have this problem.
