### ISSUE TITLE
Can SparkSession object be used for RayOnSpark instead of SparkContext?

### ISSUE THREAD

**Issue by ericbugin** [intel-analytics/analytics-zoo#2818]
Hello I am looking to use analytics-zoo to launch Ray on an existing Spark cluster that uses SparkSession. I figured I would use this code but wondered if there was someway to use my SparkSession object to pass to RayContext. 

from zoo.ray.util.raycontext import RayContext
ray_ctx = RayContext(sc=sc, object_store_memory="2g")
ray_ctx.init()

**Comment by hkvision** [comment]
Hi @ericbugin 

Currently we expect a SparkContext to launch Ray. You can get the SparkContext from SparkSession and pass to RayContext.

**Comment by ericbugin** [comment]
```py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.```

When I use pass spark.sparkContext to RayContext I get this error.

**Comment by hkvision** [comment]
Can you paste the full error log here so that I can try to reproduce it?

**Comment by ericbugin** [comment]
[rayonspark_EMR_logs.txt](https://github.com/intel-analytics/analytics-zoo/files/5183284/rayonspark_EMR_logs.txt)

**Comment by hkvision** [comment]
Hi @ericbugin 

I'm really sorry for my late reply.
We are using Spark barrier mode for starting ray. The error is `org.apache.spark.scheduler.BarrierJobRunWithDynamicAllocationException: [SPARK-24942]: Barrier execution mode does not support dynamic resource allocation for now. You can disable dynamic resource allocation by setting Spark conf "spark.dynamicAllocation.enabled" to "false".`

I find you have set `spark.conf.set("spark.dynamicAllocation.enabled", "false")` but still got this error. So I doubt if this config has taken effect, or probably spark has already initiated and this config is not set. Can you try `spark.sparkContext.getConf().getAll()` to take a look at the configurations? Thanks.

**Comment by ericbugin** [comment]
@hkvision, no worries. So you were right, the config change did not take place. I tried in various ways to no avail. Once I figure out a way to change it I am sure it'll work. Thanks for your help!

**Comment by hkvision** [comment]
Hi @ericbugin 
No problem! I suppose you need to set these configurations before you start your Spark cluster and SparkSession to make them take effect. You are using EMR and there's somewhere to add conf file when you start the cluster?

**Comment by helenlly** [comment]
@ericbugin any more questions on this issue? if no, we  will close it in a week. thanks

**Comment by ericbugin** [comment]
My question was answered. good to close

**Comment by hkvision** [comment]
Thanks. Feel free to raise a new issue if you encounter further questions. :) @ericbugin
