### ISSUE TITLE
Duplicate and conflict OMP_NUM_THREADS in hyperzoo Dockerfile

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2842]
https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/Dockerfile#L15
https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/Dockerfile#L143

**Comment by hkvision** [comment]
Better not set it to `all`?
When I run pytorch it would cause the warning:
```
libgomp: Invalid value for environment variable OMP_NUM_THREADS
```
When I run mxnet it would cause core dump:
```
libgomp: Invalid value for environment variable OMP_NUM_THREADS
terminate called after throwing an instance of 'dmlc::ParamError'
  what():  Invalid Parameter format for OMP_NUM_THREADS expect int but value='all'
Aborted (core dumped)
```

**Comment by Le-Zheng** [comment]
So better remove `ENV OMP_NUM_THREADS     all`? Set default cores as 4.

**Comment by hkvision** [comment]
Or do we need to set this in the environment? By default Zoo would set this automatically?

**Comment by Le-Zheng** [comment]
It has been updated in this PR: https://github.com/intel-analytics/analytics-zoo/pull/2894
