### ISSUE TITLE
Python only option in make-dist.sh and pyzoo/dev/release.sh

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#2852]
scala/java code is changed much less frequently than python in development. However, we need to compile scala/java code every time we change something even if only in python. This is a relatively long time.

It would be nice to have a python only building options to shorten build time and only compile scala/java code when necessary.

**Comment by hkvision** [comment]
I will first add the `quick` option back.

**Comment by hkvision** [comment]
I think the quick option should be added to build.sh; release.sh is supposed to be run at release time and it makes sense to rebuild the jar always.
