### ISSUE TITLE
TimeSequencePredictor: 'ExperimentAnalysis' object is not iterable

### ISSUE THREAD

**Issue by MrStrannix** [intel-analytics/analytics-zoo#2855]
After having set up my environment I TimeSequencePredictor consistently fails with the error: "ExperimentAnalysis' object is not iterable"

My code:
`from zoo import init_spark_on_local
from zoo.ray import RayContext
sc = init_spark_on_local(cores=4)
ray_ctx = RayContext(sc=sc)
ray_ctx.init()

import pandas as pd
import numpy as np
ind = pd.date_range(start='2019-01-01', end='2020-01-01', name='index')
data = np.random.randint(0, 100, size=ind.shape[0])
df = pd.DataFrame(index=ind, data={'value':data}).reset_index()

from zoo.automl.regression.time_sequence_predictor import TimeSequencePredictor
tsp = TimeSequencePredictor(dt_col="index", target_col="value", extra_features_col=None, future_seq_len=1)

from zoo.automl.regression.time_sequence_predictor import SmokeRecipe, RandomRecipe
pipeline = tsp.fit(df, metric="mse", recipe=SmokeRecipe(), distributed=False)`

The error message:
`== Status ==
Memory usage on this node: 5.5/251.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/4 GPUs, 0.0/164.89 GiB heap, 0.0/51.51 GiB objects
Result logdir: /home/andreas.schindler/ray_results/automl
Number of trials: 1 (1 TERMINATED)
Trial name 	status 	loc 	dropout_1	dropout_2	lstm_1_units	lstm_2_units	iter	total time (s)
train_func_00000	TERMINATED		0.286128	0.327391	32	64	1	2.49687

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-6b838441541d> in <module>
     15 
     16 from zoo.automl.regression.time_sequence_predictor import SmokeRecipe, RandomRecipe
---> 17 pipeline = tsp.fit(df, metric="mse", recipe=SmokeRecipe(), distributed=False)

~/academy/automl/azoo/lib/python3.7/site-packages/zoo/automl/regression/time_sequence_predictor.py in fit(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, distributed, hdfs_url)
    126             mc=mc,
    127             resources_per_trial=resources_per_trial,
--> 128             remote_dir=remote_dir)
    129         return self.pipeline
    130 

~/academy/automl/azoo/lib/python3.7/site-packages/zoo/automl/regression/time_sequence_predictor.py in _hp_search(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, remote_dir)
    262 
    263         # get the best one trial, later could be n
--> 264         best = searcher.get_best_trials(k=1)[0]
    265         pipeline = self._make_pipeline(best,
    266                                        feature_transformers=ft,

~/academy/automl/azoo/lib/python3.7/site-packages/zoo/automl/search/RayTuneSearchEngine.py in get_best_trials(self, k)
    199 
    200     def get_best_trials(self, k=1):
--> 201         sorted_trials = RayTuneSearchEngine._get_sorted_trials(self.trials, metric="reward_metric")
    202         best_trials = sorted_trials[:k]
    203         return [self._make_trial_output(t) for t in best_trials]

~/academy/automl/azoo/lib/python3.7/site-packages/zoo/automl/search/RayTuneSearchEngine.py in _get_sorted_trials(trial_list, metric)
    217             trial_list,
    218             key=lambda trial: trial.last_result.get(metric, 0),
--> 219             reverse=True)
    220 
    221     @staticmethod

TypeError: 'ExperimentAnalysis' object is not iterable

`

My environment (pip list)

`Package              Version
-------------------- ---------
absl-py              0.10.0
aiohttp              3.6.2
analytics-zoo        0.8.1
astor                0.8.1
async-timeout        3.0.1
attrs                20.2.0
backcall             0.2.0
beautifulsoup4       4.9.1
BigDL                0.10.0
cachier              1.4.3
certifi              2020.6.20
chardet              3.0.4
click                7.1.2
cloudpickle          1.6.0
colorama             0.4.3
conda-pack           0.3.1
dask                 2.25.0
decorator            4.4.2
distributed          2.25.0
featuretools         0.19.0
filelock             3.0.12
fsspec               0.8.1
gast                 0.2.2
google               3.0.0
google-pasta         0.2.0
grpcio               1.32.0
h5py                 2.10.0
HeapDict             1.0.1
idna                 2.10
importlib-metadata   1.7.0
ipykernel            5.3.4
ipython              7.18.1
ipython-genutils     0.2.0
jedi                 0.17.2
joblib               0.16.0
jsonschema           3.2.0
jupyter-client       6.1.7
jupyter-core         4.6.3
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
locket               0.2.0
Markdown             3.2.2
msgpack              1.0.0
multidict            4.7.6
numpy                1.19.1
opt-einsum           3.3.0
pandas               1.1.2
parso                0.7.1
partd                1.1.0
pathtools            0.1.2
pexpect              4.8.0
pickleshare          0.7.5
pip                  20.2.3
portalocker          2.0.0
prompt-toolkit       3.0.7
protobuf             3.13.0
psutil               5.7.2
ptyprocess           0.6.0
py-spy               0.3.3
py4j                 0.10.7
pyasn1               0.4.8
pyexasol             0.14.1
Pygments             2.6.1
pyrsistent           0.16.0
pyspark              2.4.3
python-dateutil      2.8.1
pytz                 2020.1
PyYAML               5.3.1
pyzmq                19.0.2
ray                  0.8.4
redis                3.5.3
requests             2.24.0
rsa                  4.6
scikit-learn         0.23.2
scipy                1.5.2
setuptools           41.2.0
six                  1.15.0
sklearn              0.0
sortedcontainers     2.2.2
soupsieve            2.0.1
tabulate             0.8.7
tblib                1.7.0
tensorboard          1.15.0
tensorboardX         2.1
tensorflow           1.15.3
tensorflow-estimator 1.15.1
termcolor            1.1.0
threadpoolctl        2.1.0
toolz                0.10.0
tornado              6.0.4
tqdm                 4.48.2
traitlets            5.0.4
typing-extensions    3.7.4.3
urllib3              1.25.10
watchdog             0.10.3
wcwidth              0.2.5
websocket-client     0.57.0
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
yarl                 1.5.1
zict                 2.0.0
zipp                 3.1.0`

Any help is very much appreciated!
I am running a jupyter notebook on a single linux server with multiple cores using python 3.7 (no cluster)

Many thanks!

Best

Andreas

**Comment by yushan111** [comment]
Hi Andreas, analytics-zoo 0.8.1 only supports ray 0.7.2.

**Comment by MrStrannix** [comment]
Thank you! That solved it!

BTW: On top of that I also had to downgrade my scikit-learn installation to: scikit-learn==0.22.2
Related to this issue:
https://github.com/hyperopt/hyperopt/issues/668

Many thanks again

Best

Andreas

**Comment by yushan111** [comment]
@MrStrannix 
Thank you for your work!
I should also mention that we only support scikit-learn < 0.23.0 for now.
Sorry for the inconvenience caused.

Best
Shan
