### ISSUE TITLE
Pyspark connect to hive failed in CDH cluster.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#2867]
Reported by SPDB.
```
sc = init_spark_on_local(cores=4, conf={"spark.driver.memory"="2g"})
spark = SparkSession.builder.enableHiveSupport().getOrCreate()
spark.sql("select * from ...").show()
```
ANTLR tool version 4.5.3 used for code genenration does not match the current runtime version 4.7.2 ANTLR.

**Comment by jason-dai** [comment]
which Spark version is used to build Analytics Zoo?

**Comment by qiuxin2012** [comment]
> which Spark version is used to build Analytics Zoo?

spark 2.4.3

**Comment by GavinGu07** [comment]
It can be solved by adding `hive.metastore.uris`
`spark = SparkSession.builder.config("hive.metastore.uris","thrift://cdh1:9083").enableHiveSupport().getOrCreate()`

**Comment by qiuxin2012** [comment]
By default, pyspark(installed by pip) doesn't know where hive metastore is. So we should tell pyspark "hive.metasotre.uris" manually.
