### ISSUE TITLE
can't download example data for Session recommender

### ISSUE THREAD

**Issue by lordk911** [intel-analytics/analytics-zoo#2868]
examples in :
`https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation`

The website ( www.officedepot.com ) which could offer sample data for Session recommender can't be access from some country, so could you offer the data schema or some litte sample data in the document.

**Comment by hkvision** [comment]
Hi @lordk911 

Thanks for pointing out.
You can refer to this post https://groups.google.com/g/bigdl-user-group/c/WrxONIfEuhk to generate some sample data. Feel free to tell us if there are questions.

**Comment by lordk911** [comment]
ok,thanks. I will try it.

**Comment by lordk911** [comment]
I'm using analytics-zoo 0.8.1 for testing , my sample data is something like : 
```
{"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
{"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
{"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
{"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
...
```
and then I run the example code with : 
```
bin/spark-shell-with-zoo.sh \
   --master yarn \
   --deploy-mode client \
   --driver-memory 4g \
   --executor-memory 4g \
   --executor-cores 1 \
   --num-executors 2 \
   --class com.intel.analytics.zoo.examples.recommendation.SessionRecExp \
   --batchSize 512 \
   --input /tmp/ecommerce/ \
   --outputDir /tmp/ecommerce/output/
```

I got error : 
```
2020-09-21 17:39:54 INFO  Engine$:413 - Find existing spark context. Checking the spark conf...
56                                                                              
1
2020-09-21 17:40:09 INFO  DistriOptimizer$:798 - caching training rdd ...
2020-09-21 17:40:12 INFO  DistriOptimizer$:636 - Cache thread models...         
2020-09-21 17:40:13 INFO  DistriOptimizer$:638 - Cache thread models... done
2020-09-21 17:40:13 INFO  DistriOptimizer$:148 - Count dataset
2020-09-21 17:40:13 INFO  DistriOptimizer$:152 - Count dataset complete. Time elapsed: 0.100815158s
2020-09-21 17:40:13 INFO  DistriOptimizer$:160 - config  {
	computeThresholdbatchSize: 100
	maxDropPercentage: 0.0
	warmupIterationNum: 200
	isLayerwiseScaled: false
	dropPercentage: 0.0
 }
2020-09-21 17:40:13 INFO  DistriOptimizer$:164 - Shuffle data
2020-09-21 17:40:13 INFO  DistriOptimizer$:167 - Shuffle data complete. Takes 0.033851223s
2020-09-21 17:40:13 ERROR TaskSetManager:70 - Task 1 in stage 16.0 failed 4 times; aborting job
2020-09-21 17:40:13 ERROR DistriOptimizer$:914 - Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 16.0 failed 4 times, most recent failure: Lost task 1.3 in stage 16.0 (TID 23, bdp-hdfs-06-10-8-33-35, executor 1): java.lang.IllegalArgumentException: requirement failed: setValue: samples's size doesn't match mini batch size, excepted 31 got 256
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:182)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:111)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:348)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:215)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:205)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by qiuxin2012** [comment]
> I'm using analytics-zoo 0.8.1 for testing , my sample data is something like :
> 
> ```
> {"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
> {"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
> {"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
> {"ATC_SEQ":[1.0,2.0,3.0,4.0,56.0], "PURCH_HIST":[9.0,7.0,6.0,5.0,3.0,1.0]}
> ...
> ```
> 
> and then I run the example code with :
> 
> ```
> bin/spark-shell-with-zoo.sh \
>    --master yarn \
>    --deploy-mode client \
>    --driver-memory 4g \
>    --executor-memory 4g \
>    --executor-cores 1 \
>    --num-executors 2 \
>    --class com.intel.analytics.zoo.examples.recommendation.SessionRecExp \
>    --batchSize 512 \
>    --input /tmp/ecommerce/ \
>    --outputDir /tmp/ecommerce/output/
> ```
> 
> I got error :
> 
> ```
> 2020-09-21 17:39:54 INFO  Engine$:413 - Find existing spark context. Checking the spark conf...
> 56                                                                              
> 1
> 2020-09-21 17:40:09 INFO  DistriOptimizer$:798 - caching training rdd ...
> 2020-09-21 17:40:12 INFO  DistriOptimizer$:636 - Cache thread models...         
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:638 - Cache thread models... done
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:148 - Count dataset
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:152 - Count dataset complete. Time elapsed: 0.100815158s
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:160 - config  {
> 	computeThresholdbatchSize: 100
> 	maxDropPercentage: 0.0
> 	warmupIterationNum: 200
> 	isLayerwiseScaled: false
> 	dropPercentage: 0.0
>  }
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:164 - Shuffle data
> 2020-09-21 17:40:13 INFO  DistriOptimizer$:167 - Shuffle data complete. Takes 0.033851223s
> 2020-09-21 17:40:13 ERROR TaskSetManager:70 - Task 1 in stage 16.0 failed 4 times; aborting job
> 2020-09-21 17:40:13 ERROR DistriOptimizer$:914 - Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 16.0 failed 4 times, most recent failure: Lost task 1.3 in stage 16.0 (TID 23, bdp-hdfs-06-10-8-33-35, executor 1): java.lang.IllegalArgumentException: requirement failed: setValue: samples's size doesn't match mini batch size, excepted 31 got 256
> 	at scala.Predef$.require(Predef.scala:224)
> 	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:182)
> 	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:111)
> 	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:348)
> 	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
> 	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:215)
> 	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:205)
> 	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:121)
> 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Driver stacktrace:
> 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
> 	at scala.Option.foreach(Option.scala:257)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
> 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
> 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
> 	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1035)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
> 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
> 	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1017)
> 	at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:340)
> 	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:888)
> 	at com.intel.analytics.zoo.pipeline.api.keras.models.KerasNet.fit(Topology.scala:372)
> 	at com.intel.analytics.zoo.pipeline.api.keras.models.KerasNet.fit(Topology.scala:430)
> 	at com.intel.analytics.zoo.models.common.KerasZooModel.fit(KerasZooModel.scala:120)
> 	at com.intel.analytics.zoo.examples.recommendation.SessionRecExp$.run(SessionRecExp.scala:108)
> 	at com.intel.analytics.zoo.examples.recommendation.SessionRecExp$$anonfun$main$2.apply(SessionRecExp.scala:70)
> 	at com.intel.analytics.zoo.examples.recommendation.SessionRecExp$$anonfun$main$2.apply(SessionRecExp.scala:69)
> 	at scala.Option.map(Option.scala:146)
> 	at com.intel.analytics.zoo.examples.recommendation.SessionRecExp$.main(SessionRecExp.scala:68)
> 	at com.intel.analytics.zoo.examples.recommendation.SessionRecExp.main(SessionRecExp.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
> 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
> 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
> 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
> 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
> 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> ```

How many samples do you have? 62? Maybe you need to reduce the batchsize.

**Comment by lordk911** [comment]
@qiuxin2012 thank you, after reduce the batchsize, problem is gone.

**Comment by hkvision** [comment]
@lordk911 Do you have other problems when running this example? If not, I'm going to close this issue. You can definitely raise further issues later.

**Comment by qiuxin2012** [comment]
Or reopen this one, if the issue is related with session recommender.
