### ISSUE TITLE
NNModel not MLWritable in Spark Pipeline

### ISSUE THREAD

**Issue by next-gonzalomellizo-soto** [intel-analytics/analytics-zoo#2909]
Hi!

We are using the NNEstimator functionalities in order to add a estimator to a Spark Pipeline. The model is a multi-input model and the other stage is a simple VectorAssembler. The pipeline will be:

`['VectorAssembler', 'zoo_estimator']`

Even though the pipeline fits successfully whenever we try to save the pipeline the following error occurs:

`ValueError: ('Pipeline write will fail on this pipeline because stage %s of type %s is not MLWritable', 'NNModel_57750efc8254', <class 'zoo.pipeline.nnframes.nn_classifier.NNModel'>)`

As for now we are using AnalyticsZoo 0.7.0, Spark 2.4.3, BigDl 0.10.0 and python 3.6.5.

If the NNEstimator purpose is to integrate into Spark Pipelines, it should be able to be saved within a pipeline, doesn't it?

Thanks in advance!

**Comment by jason-dai** [comment]
@jenniew please take a look; I do see NNModel extends MLWritable: https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala#L639

**Comment by jenniew** [comment]
Hi @next-gonzalomellizo-soto , NNEstimator already supports saving trained NNModel to spark pipeline. You can check https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearning.scala. In this example, we create spark pipeline :[featurizer, classifier]. And after fit()(L73), you can call pipelineModel.save("some_directory") to save the pipeline. 
I've tested on Analytics Zoo 0.7.0,  Spark 2.4.3, BigDl 0.10.0, and it's working.

If you don't mind, can you put some sample code so we can try to reproduce this issue?

**Comment by jenniew** [comment]
We did NNModel extends MLWritable on Scala side,  but didn't do that on Python side. @next-gonzalomellizo-soto , we'll fix this issue soon and let you know.

**Comment by next-gonzalomellizo-soto** [comment]
Hello!

Thanks @jenniew for the quick response.

In order to continue with my work I've temporally patched the NNModel object to be JavaWritable:

`type( 'NNModel', (JavaMLWritable, JavaTransformer, HasFeaturesCol, HasPredictionCol, HasBatchSize,       HasSamplePreprocessing, JavaValue), dict(NNModel.__dict__))`

Patching it like this allows me to save the Pipeline with the desired stages but I run into another problem while trying to load the `PipelineModel`. 

```python
/opt/spark24/dist/python/pyspark/ml/wrapper.py in __get_class(clazz)
    219             parts = clazz.split('.')
    220             module = ".".join(parts[:-1])
--> 221             m = __import__(module)
    222             for comp in parts[1:]:
    223                 m = getattr(m, comp)

ModuleNotFoundError: No module named 'com'
```

Could this be a similar case but with MLReadable?

Trying to find a solution I have checked the script in spark and I see that in https://github.com/apache/spark/blob/branch-2.4/python/pyspark/ml/wrapper.py#L225 the scala package name is  replaced from "org.apache.spark"  to "pyspark" could that function be trying to get the python module name but gets "com.intel.analytics.zoo.pipeline.nnframes.NNModel" class from the stage metadata instead of "zoo.pipeline.nnframes"?

Thanks in advance!

**Comment by jenniew** [comment]
@next-gonzalomellizo-soto Please try this fix: https://github.com/intel-analytics/analytics-zoo/pull/2933 to see if it is still has problem.

**Comment by next-gonzalomellizo-soto** [comment]
Hello @jenniew !

I've tried the fix but I wasn't able to make it work. I get the following error:

```python
    self.criterion = BCECriterion()
  File "/Users/gonzalo.mellizo-soto/src/misc/analytics-zoo/.venv/lib/python3.6/site-packages/bigdl/nn/criterion.py", line 693, in __init__
    size_average)
  File "/Users/gonzalo.mellizo-soto/src/misc/analytics-zoo/.venv/lib/python3.6/site-packages/bigdl/nn/criterion.py", line 38, in __init__
    bigdl_type, JavaValue.jvm_class_constructor(self), *args)
  File "/Users/gonzalo.mellizo-soto/src/misc/analytics-zoo/.venv/lib/python3.6/site-packages/bigdl/util/common.py", line 590, in callBigDlFunc
    args = [_py2java(gateway, a) for a in args]
  File "/Users/gonzalo.mellizo-soto/src/misc/analytics-zoo/.venv/lib/python3.6/site-packages/bigdl/util/common.py", line 590, in <listcomp>
    args = [_py2java(gateway, a) for a in args]
  File "/Users/gonzalo.mellizo-soto/src/misc/analytics-zoo/.venv/lib/python3.6/site-packages/bigdl/util/common.py", line 686, in _py2java
    obj = gateway.jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.loads(data)
TypeError: 'JavaPackage' object is not callable
```

I've followed this steps:

* Git clone and checkout to `jenniew:nnframe_pipeline_save_load`
* `bash analytics-zoo/pyzoo/dev/build.sh mac default` ([docs](https://analytics-zoo.github.io/master/#DeveloperGuide/python/)) 
* Install wheel and dependencies
* Execute my code

I've done this using a virtualenv for the python dependencies.

```
BigDL==0.11.1
AnalyticsZoo==0.9.0.dev (current fix)
pyspark==2.4.3
```

Maybe I'm doing something wrong while generating the Analytics Zoo wheel and jar.

**Comment by jenniew** [comment]
Hi, the PR has been merged. You can get latest Analytics Zoo build to try.

**Comment by jenniew** [comment]
The save/load pipeline support only work on Spark 2.3+.  In Spark 2.1, 2.2,   The spark pipeline uses JavaMLWriter/ JavaMLReader to write/load pipeline which cannot get python NNModel module from com.intel.analytics.zoo.pipeline.nnframes.NNModel" class from the stage metadata.
