### ISSUE TITLE
UT: scala and python test failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2910]
Cause: java.io.FileNotFoundException: File /lib/libxgboost4j.dylib was not found inside JAR.[0m
[31m  at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:126)[0m
[31m  at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:69)[0m
[31m  at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)[0m
[31m  at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)[0m
[31m  at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:691)[0m
[31m  at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:51)[0m
[31m  at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:65)[0m
[31m  at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:45)[0m
[31m  at ml.dmlc.xgboost4j.scala.XGBoost$.loadModel(XGBoost.scala:142)[0m
[31m  at ml.dmlc.xgboost4j.scala.spark.XGBoostHelper$.load(XGBoostHelper.scala:22)[0m

Jenkins link：
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.1-SCALA-MAC/142/console

**Comment by dding3** [comment]
Seems xgboost 1.2 package doesn't contains .dylib file. Per https://discuss.xgboost.ai/t/cant-run-the-xgboost4j-spark-tutorial/1735, the build only works on Linux. Can we disable this ut on mac.

**Comment by qiyuangong** [comment]
Yes, we can disable XGBoost UT on mac. But as Linux and mac are using the same script, I think you can add OS check in Unit test.

```scala
 val moTarInputStream = scala.util.Properties.isMac match {
      case true => OpenvinoNativeLoaderClass
        .getResourceAsStream("/darwin-x86_64" + moTarPath)
      case false => OpenvinoNativeLoaderClass
        .getResourceAsStream(moTarPath)
    }
```

**Comment by jason-dai** [comment]
I think we should check with the community on MacOS support.

**Comment by dding3** [comment]
> I think we should check with the community on MacOS support.

Per https://discuss.xgboost.ai/t/cant-run-the-xgboost4j-spark-tutorial/1735, seems like xgboost doesn't support mac. And I have submitted an issue(https://github.com/dmlc/xgboost/issues/6196) on xgboost git to double confirm.
