### ISSUE TITLE
from bert import modeling failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2912]
package: zoo.tfpark.text   

from bert import modeling
cannot import name 'modeling' from 'bert'

**Comment by hkvision** [comment]
https://analytics-zoo-doc.readthedocs.io/en/master/zoo.tfpark.text.estimator.html#module-zoo.tfpark.text.estimator.bert_ner
Fixed by installing bert-tensorflow 1.0.0.
