### ISSUE TITLE
TimeSequencePredictor with ID column

### ISSUE THREAD

**Issue by orydatadudes** [intel-analytics/analytics-zoo#2924]
can i pass ID column to TimeSequencePredictor
so my data will look like that:

ID|datetime | value
1|2019-06-06 | 1.2
1|2019-06-07 | 2.3
2|2019-06-06 | 2.2
2|2019-06-07 | 3.3

so after training the pipeline and passing test_df (pipeline.predict(test_df)) i will get
ID|datetime | value
1|2019-06-08 | 3.2
2|2019-06-08 | 4.3
thanks

**Comment by yushan111** [comment]
I'm sorry that we haven't support that yet.
Currently our TimeSequencePredictor mainly supports time series forecasting for single entity. We are working on multivariate as well as high-dimension time series forecasting support and will update soon.

**Comment by orydatadudes** [comment]
thank you for your answer
