### ISSUE TITLE
python exampletests failed on MAC

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2928]
A fatal error has been detected by the Java Runtime Environment:
SIGBUS (0xa) at pc=0x0000000e1dda4bf5, pid=55664, tid=0x0000000000011e03
 JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 )
Problematic frame:
 C  [dlNativeLoader6913792356201299098libcaffe2.dylib+0x1d45bf5]  _ZZN6mkldnn4impl3cpu19simple_reorder_implIL18mkldnn_data_type_t1EL22mkldnn_memory_format_t1ELS3_1ELS4_35ELb1EvE7executeEPKNS1_16cpu_reorder_pd_tEPKfPfENKUlSA_SB_iE_clESA_SB_i+0xb5
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
 An error report file with more information is saved as:
 /private/var/jenkins_home/workspace/ZOO-NB-Python-ExampleTests-MAC/hs_err_pid55664.log
If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
/var/jenkins_home/workspace/ZOO-NB-Python-ExampleTests-MAC/dist/bin/analytics-zoo-base.sh: line 29: 55664 Abort trap: 6           ${SPARK_HOME}/bin/${SPARK_CMD} --properties-file ${ANALYTICS_ZOO_CONF} --jars ${ANALYTICS_ZOO_JAR} --conf spark.driver.extraClassPath=${ANALYTICS_ZOO_JAR} --conf spark.executor.extraClassPath=${ANALYTICS_ZOO_JAR} "$@"
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Python-ExampleTests-MAC/147/console

example: #10 start example test for pytorch

**Comment by qiuxin2012** [comment]
It seems a random fail. Please rerun. The example will be removed in the future.

**Comment by pinggao187** [comment]
rerun success.
