### ISSUE TITLE
UT: scala and python test failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2941]
Failed
com.intel.analytics.zoo.pipeline.nnframes.XgboostTrainSpec.XGBRegressor train should work

Error Message
XGBoostModel training failed

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-SCALA-MAC/190/console

**Comment by glorysdj** [comment]
java.io.FileNotFoundException: File /lib/libxgboost4j.dylib was not found inside JAR.

**Comment by pinggao187** [comment]
python test has the same error.
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.1-PYTHON-MAC/122/console
