### ISSUE TITLE
UT: scala stylecheck failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2964]
ZOO-NB-SCALA-StyleCheck

error file=/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/scala/com/intel/analytics/zoo/examples/serving/ClusterServingInferenceBlockOthersExample.scala message=File must end with newline character
error file=/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/PreprocessingBaseline.scala message=File line length exceeds 100 characters line=96

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-SCALA-StyleCheck/1249/console

ZOO-NB-Python-AppTests-part1
[ERROR] /opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala:25: object serving is not a member of package com.intel.analytics.zoo
[ERROR] import com.intel.analytics.zoo.serving.engine.ModelHolder

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Python-AppTests-part1/675/console

**Comment by glorysdj** [comment]
https://github.com/intel-analytics/analytics-zoo/pull/2961
