### ISSUE TITLE
Python inference model (tensorflow) predict core dump

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#2969]
I loaded tf BERT saved model with InferenceModel on the python side and core dump happened when calling predict(dataset).

**Comment by yangw1234** [comment]
it seems it will core dump only when the batch size is very large and memory consumption is larger than available memory.

**Comment by yangw1234** [comment]
This is because we feed all data in one batch to tensorflow. The process consumed too much memory and got killed by the OS. Breaking the data into batches will fix this problem. 

I do not think this is an issue and I am closing it. @jason-dai

**Comment by jason-dai** [comment]
> This is because we feed all data in one batch to tensorflow. The process consumed too much memory and got killed by the OS. Breaking the data into batches will fix this problem.
> 
> I do not think this is an issue and I am closing it. @jason-dai

Instead of core dump, can we report more meaningful error messages?

**Comment by yangw1234** [comment]
> > This is because we feed all data in one batch to tensorflow. The process consumed too much memory and got killed by the OS. Breaking the data into batches will fix this problem.
> > I do not think this is an issue and I am closing it. @jason-dai
> 
> Instead of core dump, can we report more meaningful error messages?

I think it not very easy to do that. Because it is hard to anticipate whether a certain input on a certain model will fail or not, and once we call into the tensorflow land, we have no control over whether the process will core dump or not.
