### ISSUE TITLE
Orca tf estimator predict function returns wrong order results when input is a tf.data.TFRecordDataset

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#2970]
Orca tf estimator `predict` function returns wrong order results when input is a tf.data.TFRecordDataset.

**Comment by yangw1234** [comment]
@jason-dai I think predicting on directly on tf.data.Dataset does not work in a distributed setting, because the Dataset object is inherently sequential. Maybe we should disable it?

**Comment by yangw1234** [comment]
disable this feature by #3008
