### ISSUE TITLE
UT: python test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#2987]
TestPyTorchTrainer.test_linear

 ray.exceptions.RayTaskError(AttributeError): [36mray::TorchRunner.setup_torch_distribute()[39m (pid=79290, ip=10.239.33.1)
E                         File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
E                         File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
E                         File "/private/var/jenkins_home/workspace/ZOO-NB-UnitTests-2.4-PYTHON-MAC/pyzoo/zoo/orca/learn/pytorch/torch_runner.py", line 129, in setup_torch_distribute
E                           dist.init_process_group(
E                       AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/ray/worker.py:1515: RayTaskError(AttributeError)

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/159/console

**Comment by pinggao187** [comment]
ray.tune.error.TuneError: ('Trials did not complete', [train_func_00000])

ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node Gondolin-Node-071 is used (48.64 / 48.83 GB)

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/781/console

**Comment by hkvision** [comment]
There is no memory on the node to start ray. You need to clear the node disk storage @glorysdj @pinggao187

**Comment by jason-dai** [comment]
We should clean the temp files automatically, e.g., using cron.

**Comment by glorysdj** [comment]
this is a memory issue. I dont think it is caused by disk storage.

**Comment by pinggao187** [comment]
@qiuxin2012 

The memory issue has been fixed, the current issue is

TestPyTorchTrainer.test_linear

ray.exceptions.RayTaskError(AttributeError): �[36mray::TorchRunner.setup_torch_distribute()�[39m (pid=79290, ip=10.239.33.1)
E File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
E File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
E File "/private/var/jenkins_home/workspace/ZOO-NB-UnitTests-2.4-PYTHON-MAC/pyzoo/zoo/orca/learn/pytorch/torch_runner.py", line 129, in setup_torch_distribute
E dist.init_process_group(
E AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/ray/worker.py:1515: RayTaskError(AttributeError)

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/161/console

**Comment by yangw1234** [comment]
the OSX binary of PyTorch does not ship with distributed support. maybe we should disable this test.

> @qiuxin2012
> 
> The memory issue has been fixed, the current issue is
> 
> TestPyTorchTrainer.test_linear
> 
> ray.exceptions.RayTaskError(AttributeError): �[36mray::TorchRunner.setup_torch_distribute()�[39m (pid=79290, ip=10.239.33.1)
> E File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
> E File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
> E File "/private/var/jenkins_home/workspace/ZOO-NB-UnitTests-2.4-PYTHON-MAC/pyzoo/zoo/orca/learn/pytorch/torch_runner.py", line 129, in setup_torch_distribute
> E dist.init_process_group(
> E AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
> 
> /Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/ray/worker.py:1515: RayTaskError(AttributeError)
> 
> jenkins link:
> http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/161/console

**Comment by qiuxin2012** [comment]
@yangw1234 it seems only throw error on OSX?

**Comment by pinggao187** [comment]
fixed

http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/167/console
