### ISSUE TITLE
Integrate TCMF time feature to Automl TimeSequenceFeature 

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#3023]
There is no need to use featuretools in automl TimeSequenceFeature and the TCMF time feature needs to be Integrate into the TimeSequenceFeature.

This issue will be divided into 2 PRs:

1. Deprecate `featuretools` and use `pandas` method in `TimeSequenceFeature `. Integrate TCMF time features(in `time.py`) into the method.
2. Change to use `TimeSequenceFeature ` in TCMF.

**Comment by yushan111** [comment]
FYI. fast.ai [make_datepart](https://github.com/fastai/fastai/blob/master/fastai/tabular/core.py#L25-L36) implementation.
