### ISSUE TITLE
support numpy input in automl searcher 

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/analytics-zoo#3026]
Currently, searcher only support input dataframe. We should add numpy ndarray support which can be suitable for more general cases.

Therefore we should support below cases input for searching and model training.
1. dataframe for xgboost or recommendation. Input needed: (`df`, `feature_cols`, `target_cols`)
2. dataframe for time series analysis. Input needed: (`df`, `dt_col`, `target_cols`, `extra_feature_cols`)
3. ndarray for general. Input needed: ('x', 'y') 

For dataframe input,  we have built-in feature transformers to convert to ndarray and feed into model.
For ndarray input, we default not to use any feature transformers and directly feed into model.

**Comment by TheaperDeng** [comment]
Here is the API design.
```python
#ray_tune_search_engine.py
...
def compile(self,
            input_df, 
            # if input_feature and input_target is provided then input_df will be ignored
            input_feature=None, # new arg 1
            input_target=None, # new arg 2
            model_create_func,
            recipe,
            feature_cols=None, # ["x"]
            target_col=None, # "y"
            search_space=None,
            feature_transformers=None,
            validation_df=None, 
            # if validation_feature and validation_target is provided then validation_df will be ignored
            validation_feature=None, # new arg 3
            validation_target=None, # new arg 4
            mc=False,
            metric="mse"):
    if input_feature and input_target:
        input_df = gen_input_df(input_feature, input_target, feature_cols, target_col)
    if validation_feature and validation_target:
        validation_df = gen_input_df(validation_feature, validation_target, feature_cols, target_col)
    ...
```

**Comment by yushan111** [comment]
```python
def compile(self,
            data, 
            model_create_func,
            recipe,
            df_schema=None,
            validation_data=None, 
            feature_transformers=None,
            ):
```
where data/validation data can be a tuple of numpy ndarray like (x, y) or a data frame.

or 
```python
def compile(self,
            data, 
            model_create_func,
            recipe,
            validation_data=None, 
            feature_transformers=None,
            ):
```
where data should be a dict. 
For data frame, it should be something like {"df": df, "feature_cols": [], "target_col": "value"} or  {"df": df, "dt_col": "datatime", "target_cols": ["value"], "feature_cols": []}; 
For ndarray, it should be {"x": array1, "y": array2}

You should not convert ndarray to a df.

if input ndarray or later maybe DataLoader/data_creator, feature_transformer is not necessary.
if input data frame,  feature transfromer defaults to `Identity feature transformer`, but `df_schema` requires to contain `feature_cols` and `target_col`

**Comment by shane-huang** [comment]
Design 2 looks good to me.
