### ISSUE TITLE
need add a clarify "SpatialBatchNorm  only support 4D tensor(including batch as first dimension). " in doc website

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#3034]
refer to question in
https://groups.google.com/g/bigdl-user-group/c/EfFxVOucRpo
https://groups.google.com/g/bigdl-user-group/c/8frz63Vn9SI

need add a clarify "SpatialBatchNorm  only support 4D tensor(including batch as first dimension). " in doc website
----------------------------
SpatialBatchNorm  only support 4D tensor(including batch as first dimension).  You can do reshape before SpatialBatchNorm. For your input, you need to reshape as  the input of VolumetricConv  needs to be 4D tensor(not including batch).

**Comment by helenlly** [comment]
@jenniew  any updates?

**Comment by jenniew** [comment]
This is BigDL issue. And fixed in https://github.com/intel-analytics/BigDL/pull/3104
