### ISSUE TITLE
OpenVINOInt8Suite's equal method between two JTensors should be improved.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#3036]
We can use the equal method in BigDL's Tensor to do the equal.
Jtensor could be convert to Tensor like this:
```scala
val input1 = new JTensor(data, resnet_v1_50_shape
Tensor[Float](input1.getData, input1.getShape)
```

**Comment by qiyuangong** [comment]
Good idea! 👍 

I think we can clean up that unit test with Tensor.

@ClawSeven will refactor code

**Comment by qiyuangong** [comment]
Issue fixed by @3044.
