### ISSUE TITLE
doc update: clarity to add "BIGDL_CLASSPATH" in  pycharm Environment variables. 

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#3039]
doc update is needed. refer to https://groups.google.com/g/bigdl-user-group/c/mY-p363KxWc
_________________________________________________________

ding ding<dingding.bupt@gmail.com>
Oct 8, 2020, 2:39:00 AM
to User Group for BigDL and Analytics Zoo
I tried the same version with you. It works for me. I think the " 'JavaPackage' object is not callable " error is caused by BigDL_PATH is not set in pycharm env variables. 

Could you please add "BIGDL_CLASSPATH" in  pycharm Environment variables. "Run"  ->  "Run/Debug Configurations"  ->  "Configuration"  -> "Environment variables", and set the value to the bigdl jar path.

**Comment by helenlly** [comment]
@dding3 any updates?

**Comment by dding3** [comment]
> @dding3 any updates?

Fixed in https://github.com/intel-analytics/BigDL/pull/3106

**Comment by helenlly** [comment]
close it since it is fixed in  intel-analytics/BigDL#3106
