### ISSUE TITLE
init_spark_on_yarn failed to use conda envs distributed from driver but use local env.

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3063]
when use init_spark_on_yarn run AutoML application,the dependencies installed from Cluster slave nodes impact the dependencies installed of the master's conda envs Packaging environment ,result in  the application can not  execute successfully

**Comment by yushan111** [comment]
Could you attach your error message and your environment configuration?

**Comment by helenlly** [comment]
@hkvision any updates?

**Comment by hkvision** [comment]
This should be resolved, due to the issue in user's environment.
