### ISSUE TITLE
[Question] How analytics-zoo run model inference inside Flink or Spark?

### ISSUE THREAD

**Issue by PerkzZheng** [intel-analytics/analytics-zoo#3069]
Hi, 
I have a question about how analytics-zoo run model inference inside Flink or Spark?
Thanks.

**Comment by glorysdj** [comment]
Hi We have a pojo-style InferenceModel(scala)/AbstractInferenceModel(java), this can be used in Flink or Spark or any other Java programs.
In analytics-zoo, InferenceModel leverages openvino/tfnet/pytorch implementation in analytics-zoo to do the actual forward/prediction work.

**Comment by PerkzZheng** [comment]
@glorysdj Thanks. So it is running in JVM,  not a python environment (JEP) ?

**Comment by glorysdj** [comment]
yes, most are running in jvm via jni, while pytorch is using JEP.

**Comment by PerkzZheng** [comment]
understood. libtensorflow_jni.so was applied.
