### ISSUE TITLE
Tensorflow-GPU on Flink

### ISSUE THREAD

**Issue by PerkzZheng** [intel-analytics/analytics-zoo#3073]
Recently, Flink supports [GPU awareness.](https://flink.apache.org/news/2020/08/06/external-resource.html)
Will analytics-zoo on Flink support gpu accelerated tensorflow training and inference in the future ?
Just for better integrating gpu training with flink or spark.

**Comment by glorysdj** [comment]
Currently we are focusing on inference with CPU.

**Comment by PerkzZheng** [comment]
Thanks.
