### ISSUE TITLE
Loading keras .h5 weights to Orca TF Estimator

### ISSUE THREAD

**Issue by ottermegazord** [intel-analytics/analytics-zoo#3080]
Loading a pre-trained Keras .h5 model on TFPark Keras Model API is pretty straightforward

`model.load_weights("/tmp/model.h5")`

Is there any way to do the same .h5 Keras with an Orca TF Keras Estimator?

**Comment by jenniew** [comment]
We'll add this function soon.

As a workaround, you can do:
model = your_tf_keras_model
def load_func(file_path):
        model.load_weights(file_path, by_name=False)
load_from_file(load_func, model_path)
est = Estimator.from_keras(model)

Then do prediction or evaluation with est.

**Comment by jenniew** [comment]
Created PR to fix it:https://github.com/intel-analytics/analytics-zoo/pull/3082
See example here:  https://github.com/jenniew/analytics-zoo/blob/orca_tf_estimator_save_load/pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py#L474
