### ISSUE TITLE
scala stylecheck failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3084]
[ERROR] /opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala:32: object PytorchModel is not a member of package com.intel.analytics.zoo.pipeline.api.net
[ERROR] import com.intel.analytics.zoo.pipeline.api.net.{PytorchModel, PytorchModelWrapper}

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-SCALA-StyleCheck/1283/console

**Comment by glorysdj** [comment]
fixed by https://github.com/intel-analytics/analytics-zoo/pull/3083
