### ISSUE TITLE
UT: python test failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3123]
TestEstimatorForOpenVINO.test_openvino

 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgkq6b936/openvino2020_resnet50/resnet_v1_50.xml'

: Can't set user=998/group=998 for openvino2020_resnet50
x openvino2020_resnet50/resnet_v1_50.mapping: Failed to create dir 'openvino2020_resnet50'
x openvino2020_resnet50/resnet_v1_50.xml: Failed to create dir 'openvino2020_resnet50'
x openvino2020_resnet50/resnet_v1_50.bin: Failed to create dir 'openvino2020_resnet50'

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/197/console

**Comment by qiyuangong** [comment]
NB passed after clean up tmp
