### ISSUE TITLE
Unable to initialize main class com.intel.analytics.zoo.serving.http.FrontEndApp

### ISSUE THREAD

**Issue by ManfeiBai** [intel-analytics/analytics-zoo#3128]
在graphe下面跑下述的java命令的时候，有报错提示：
[报错提示]
Error: Unable to initialize main class com.intel.analytics.zoo.serving.http.FrontEndApp
Caused by: java.lang.NoClassDefFoundError: scala/collection/Seq 

[Java命令]java \
    -Xms1g \
    -Xmx2g \
    -Dcom.intel.analytics.zoo.shaded.io.netty.tryReflectionSetAccessible=true \
    -Dakka.actor.default-dispatcher.fork-join-executor.parallelism-factor=2 \
    -jar ./scripts/analytics-zoo/zoo/target/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-http.jar \
    --redisHost '172.168.10.103' \
    --httpsEnabled true \
    --httpsKeyStorePath '/home/sdp/test5/narwhal/Trusted_ML/Trusted_Cluster_Serving/bin/keys/keystore.pkcs12' \
    --httpsKeyStorePassword '1234qwer' \
    --redisSecureEnabled false \
    --redissTrustStorePath '/home/sdp/test5/narwhal/Trusted_ML/Trusted_Cluster_Serving/bin/keys/keystore.jks' \
    --redissTrustStorePassword '1234qwer'

似乎与az的jar包和scala的path有关

**Comment by Litchilitchy** [comment]
@qiuxin2012 scala changed to provided in default jar thus http jar has no scala dependency now and this error is raised.

**Comment by Litchilitchy** [comment]
akka related issue:
https://stackoverflow.com/questions/48904881/could-not-resolve-substitution-to-a-value-akka-stream-materializer-in-aws-la

**Comment by qiuxin2012** [comment]
@ManfeiBai Please try again.

**Comment by ManfeiBai** [comment]
> @ManfeiBai Please try again.

Tks! try now~
