### ISSUE TITLE
Use init_spark_on_yarn running automl example get FileNotFoundError

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3152]
when use init_spark_on_yarn running automl example ,get error as follow:

> FileNotFoundError:[Errno 2] No such file or directory: '/home/yarn/zoo_automl_logs/automl/train_func_0_batch_size=64,dropout_2=0.28694,lr=0.0028079,lstm_1_units=64,lstm_2_units=16,selected_features=["HOUR(timestamp)", "W_2020-12-01_15-14-514wrkdwv1/best.ckpt'

**Comment by hkvision** [comment]
@yushan111 Take a look.

**Comment by yushan111** [comment]
@mamba-8-24 
Which automl example did you try?

**Comment by mamba-8-24** [comment]
The automl example is https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb
and use init_spark_on_yarn instead of init_spark_on_local

**Comment by mamba-8-24** [comment]
> The automl example is https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb
> and use init_spark_on_yarn instead of init_spark_on_local



> @mamba-8-24
> Which automl example did you try?
The example is https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb
and use init_spark_on_yarn instead of init_spark_on_local

**Comment by yushan111** [comment]
You need to set `distributed=True` in `tsp.fit()` while using yarn. 
I will explain more clearly in our doc.

**Comment by mamba-8-24** [comment]
@yushan111 
> You need to set `distributed=True` in `tsp.fit()` while using yarn.
> I will explain more clearly in our doc.
when I set 'distributed=True' ,I get another error as fllow:

hdfs errors: b"get: `/ray_results/automl/2020-12-02_17-17-15htil890l/best.ckpt': No such file or directory\n"
/home/yarn/anaconda3/lib/python3.6/site-packages/dask/dataframe/utils.py:14: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-1ac85a4aa4eb> in <module>()
     10                               look_back=look_back_single,
     11                              # batch_size=[batch_size]))
---> 12                               batch_size=[64]))
     13 print("Training completed.")

~/anaconda3/lib/python3.6/site-packages/zoo/automl/regression/base_predictor.py in fit(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, distributed, hdfs_url)
    114             mc=mc,
    115             resources_per_trial=resources_per_trial,
--> 116             remote_dir=remote_dir)
    117         return self.pipeline
    118 

~/anaconda3/lib/python3.6/site-packages/zoo/automl/regression/base_predictor.py in _hp_search(self, input_df, validation_df, metric, recipe, mc, resources_per_trial, remote_dir)
    191                                        feature_transformers=ft,
    192                                        model_create_fn=model_fn,
--> 193                                        remote_dir=remote_dir)
    194         return pipeline
    195 

~/anaconda3/lib/python3.6/site-packages/zoo/automl/regression/base_predictor.py in _make_pipeline(self, analysis, feature_transformers, model_create_fn, remote_dir)
    215                                       remote_dir,
    216                                       feature_transformers,
--> 217                                       model,
    218                                       # config)
    219                                       )

~/anaconda3/lib/python3.6/site-packages/zoo/automl/common/util.py in restore_hdfs(model_path, remote_dir, feature_transformers, model, config)
    223         # print("get hdfs cmd is:", cmd)
    224         process(cmd)
--> 225         with zipfile.ZipFile(os.path.join(tmp_dir, model_name)) as zf:
    226             zf.extractall(tmp_dir)
    227             # print(os.listdir(tmp_dir))

~/anaconda3/lib/python3.6/zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1088             while True:
   1089                 try:
-> 1090                     self.fp = io.open(file, filemode)
   1091                 except OSError:
   1092                     if filemode in modeDict:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/automl_save_9g3nkatw/best.ckpt'

**Comment by mamba-8-24** [comment]
> @yushan111 

It looks like that it does not make dir and file on  hdfs

**Comment by yushan111** [comment]
Is there any other hdfs error messages?

**Comment by mamba-8-24** [comment]
> @yushan111 
There is no other hdfs error messages except above described in the training result,but I capture the error in the traing process as follow :
![1606974211(1)](https://user-images.githubusercontent.com/74291551/100969634-598cb380-356e-11eb-8703-b2f45e72e4ec.jpg)
![1606974265(1)](https://user-images.githubusercontent.com/74291551/100969637-5b567700-356e-11eb-9b63-baa6875ce893.jpg)

**Comment by yushan111** [comment]
It seems the best checkpoint hasn't been written to hdfs successfully.  You can try specify `upload_dir` with your own hdfs path and be sure user has write permission to the path.
```
tsp = TimeSequencePredictor()
tsp.fit(upload_dir="your_hdfs_path_with_write_permission")
```

We will handle hdfs error better and make sure the write fail error can be raised correctly.
