### ISSUE TITLE
Example Test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3172]
#17 start test for orca tf imagesegmentation
--2020-12-03 16:44:47--  ftp://zoo:*password*@10.239.47.210/analytics-zoo-data/data/carvana/train.zip
           => ‘analytics-zoo-data/data/carvana/train.zip’
Connecting to 10.239.47.210:21... connected.
Logging in as zoo ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /analytics-zoo-data/data/carvana ... 
No such directory ‘analytics-zoo-data/data/carvana’.

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Pip-ExampleTests-py36/207/console

path: ftp://zoo:*password*@10.239.47.210/analytics-zoo-data/carvana/train.zip

**Comment by glorysdj** [comment]
No such directory ‘analytics-zoo-data/data/carvana’.

caused by https://github.com/intel-analytics/analytics-zoo/pull/3161
@cyita 
please make sure carvana is updated to ftp/http server

**Comment by cyita** [comment]
> No such directory ‘analytics-zoo-data/data/carvana’.
> 
> caused by #3161
> @cyita
> please make sure carvana is updated to ftp/http server

Updated
