### ISSUE TITLE
Install zoo with 'analytics_zoo-0.9.0.dev0-20201202-py2.py3-none-manylinux1_x86_64.whl' and run init_spark_on_yarn  to be stuck in spark job 

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3180]
Install nightly build zoo with  ''analytics_zoo-0.9.0.dev0-20201202-py2.py3-none-manylinux1_x86_64.whl' and run init_spark_on_yarn,it is stuck in spark job and can't execute the following program! as fllow,it has waited two hour,but still so.
![1607060801(1)](https://user-images.githubusercontent.com/74291551/101126847-44c82280-3637-11eb-80f4-37abc20aab6c.jpg)

**Comment by mamba-8-24** [comment]
![1607060801(1)](https://user-images.githubusercontent.com/74291551/101126993-8c4eae80-3637-11eb-805d-d71e73665ef9.jpg)

**Comment by hkvision** [comment]
More details: run the 1202 nightly version got crash while run the pypi version (1123) is ok.

**Comment by hkvision** [comment]
Hi @mamba-8-24 

I can't reproduce your issue on our environment.
I download the whl from https://sourceforge.net/projects/analytics-zoo/files/zoo-py/analytics_zoo-0.9.0.dev0-20201202-py2.py3-none-manylinux1_x86_64.whl/download 
Run a setup example with following code:
```
import ray
from zoo import init_spark_on_yarn
from zoo.ray import RayContext

sc = init_spark_on_yarn(hadoop_conf="/opt/work/hadoop-2.7.2/etc/hadoop",
                        conda_name="inspur-kai",
                        num_executors=2,
                        executor_cores=4)

@ray.remote(num_cpus=4)
class TestRay:
    def hostname(self):
        import socket
        from zoo.util.utils import get_node_ip
        print(get_node_ip())
        return socket.gethostname()

ray_ctx = RayContext(sc=sc, object_store_memory="1g")
ray_ctx.init()
actors = [TestRay.remote() for i in range(0, 2)]
print(ray.get([actor.hostname.remote() for actor in actors]))
ray_ctx.stop()
sc.stop()
```
Also run a training example: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py

Both can run successfully with the wheel released on 1202.
So you can try these two examples first to spot whether the stuck takes place in RayOnSpark.

**Comment by hkvision** [comment]
@mamba-8-24 If the stuck comes from automl, you can contact @yushan111 for help.

**Comment by mamba-8-24** [comment]
@hkvision 
Thanks a lot,I set up a new cluster and the issus has gone away .
The reason I have not got, but it can run successfully.thank you 
I will continue to try the automl example.
