### ISSUE TITLE
There is no spark history for  Image Classification Example predict.py on Spark 2.1

### ISSUE THREAD

**Issue by anyuecq25** [intel-analytics/analytics-zoo#3223]
Hi, I am  running Image Classification Example predict.py on YARN cluster, when the program is running,I can monitor it by Spark UI, but when the program is done, there is no spark history for it.

I also tested other spark programs(not Intel analytics zoo program) which are submited by  **spark-submit** command, all the other programs have spark historys.

I wonder is there any parameter to disable spark hostory recording on Intel analytics zoo, so that I cannot get the spark history? If so ,how can I get the spark history for Intel analytics zoo program?

**analytics-zoo-bigdl_0.7.2-spark_2.1.1-0.5.0-20190327.182106-53-dist-all
spark 2.1.1
scala 2.1.1
python 2.7**

Here is my script:

export SPARK_MAJOR_VERSION=2
export SPARK_HOME=/usr/hdp/2.6.1.0-129/spark2
export ANALYTICS_ZOO_HOME=/home/ubuntu/analytics_zoo
export VENV_HOME=/home/ubuntu/analytics_zoo
modelPath=hdfs://HA/user/ubuntu/caffe/analytics-zoo_mobilenet-v2_imagenet_0.1.0.model

topN=5
partitionNum=1
imagePath=hdfs://HA/user/ubuntu/chenq/images/train/*/*.jpg

PYSPARK_DRIVER_PYTHON=${VENV_HOME}/venv/bin/python 
PYSPARK_PYTHON=venv.zip/venv/bin/python 
**${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=venv.zip/venv/bin/python \
    --master yarn \
    --deploy-mode client \
    --driver-memory 16g \
    --executor-memory 32g \
    --executor-cores 16 \
    --num-executors 8 \
    --archives ${VENV_HOME}/venv.zip \
    --conf spark.files.maxPartitionBytes=1048576 \
    predict.py -f $imagePath --model $modelPath --topN 5 --partition_num ${partitionNum}**

Here is the content of predict.py

import time
from optparse import OptionParser
from zoo.common.nncontext import init_nncontext
from zoo.models.image.imageclassification import *

def predict(model_path, img_path, topN, partition_num):
    print("ImageClassification prediction")
    print("Model Path %s" % model_path)
    print("Image Path %s" % img_path)
    print("Top N : %d" % topN)
    
    print time.strftime('%Y.%m.%d %H:%M:%S',time.localtime(time.time()))

    imc = ImageClassifier.load_model(model_path)
    print("model loaded!")

    print time.strftime('%Y.%m.%d %H:%M:%S',time.localtime(time.time())) 

    image_set = ImageSet.read(img_path, sc, partition_num)
    print("images loaded!")
    print time.strftime('%Y.%m.%d %H:%M:%S',time.localtime(time.time()))
    
    output = imc.predict_image_set(image_set)

    print time.strftime('predict %Y.%m.%d %H:%M:%S',time.localtime(time.time()))
    
    labelMap = imc.get_config().label_map()
    predicts = output.get_predict().collect()
    print time.strftime('collect  %Y.%m.%d %H:%M:%S',time.localtime(time.time()))
    print('total file is: '+str(len(predicts)))
    n=0
    for predict in predicts:
        (uri, probs) = predict
        sortedProbs = [(prob, index) for index, prob in enumerate(probs[0])]
        sortedProbs.sort()
        print("Image : %s, top %d prediction result" % (uri, topN))
        print time.strftime('Image per time  %Y.%m.%d %H:%M:%S',time.localtime(time.time()))

        for i in range(topN):
            print("\t%s, %f" % (labelMap[sortedProbs[999 - i][1]], sortedProbs[999 - i][0]))
        n=n+1
        if(n>10):
            break

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-f", "--folder", type=str, dest="img_path", default=".",
                      help="Path where the images are stored")
    parser.add_option("--model", type=str, dest="model_path", default="",
                      help="Path where the model is stored")
    parser.add_option("--topN", type=int, dest="topN", default=1, help="top N number")
    parser.add_option("--partition_num", type=int, dest="partition_num", default=4,
                      help="The number of partitions")
    (options, args) = parser.parse_args(sys.argv)

    sc = init_nncontext("Image Classification Example")
    sc.setLogLevel('INFO')
    predict(options.model_path, options.img_path, options.topN, options.partition_num)

**Comment by qiuxin2012** [comment]
Do you means spark history server?
Have you set ```spark.eventLog.enabled, spark.eventLog.dir```?

**Comment by anyuecq25** [comment]
> Do you means spark history server?
> Have you set `spark.eventLog.enabled, spark.eventLog.dir`?

Thanks for your reply.
![spark](https://user-images.githubusercontent.com/20838222/101855399-4e550b80-3b9e-11eb-95fe-88b49978c260.png)

spark.eventLog.enabled is true,  spark.eventLog.dir=hdfs:///spark2-history/.  

The spark history server works well. Because when I submit a simple spark program such as word count, I can get the history when the program is done.

**Comment by qiuxin2012** [comment]
Could you check these two configrations on Spark UI's Enviroment page, when you run AZ's job?

**Comment by anyuecq25** [comment]
> Could you check these two configrations on Spark UI's Enviroment page, when you run AZ's job?

Thank you. There is no configuration for these two properties on Spark UI's Enviroment page when running AZ's job.

So I re-run the program like this, it works now.  I can get the spark history now. Thank you very much.

modelPath=hdfs://HA/user/ubuntu/caffe/analytics-zoo_mobilenet-v2_imagenet_0.1.0.model

topN=5
partitionNum=1
imagePath=hdfs://HA/user/ubuntu/chenq/images/train/*/*.jpg


PYSPARK_DRIVER_PYTHON=${VENV_HOME}/venv/bin/python 
PYSPARK_PYTHON=venv.zip/venv/bin/python 
${ANALYTICS_ZOO_HOME}/bin/spark-submit-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=venv.zip/venv/bin/python \
    --master yarn \
    --deploy-mode client \
    --driver-memory 16g \
    --executor-memory 32g \
    --executor-cores 16 \
    --num-executors 8 \
    --archives ${VENV_HOME}/venv.zip \
    --conf spark.files.maxPartitionBytes=1048576 \
    **--conf spark.eventLog.enabled=true \
    --conf spark.eventLog.dir=hdfs:///spark2-history/ \
    --conf spark.history.fs.logDirectory=hdfs:///spark2-history/ \**
    predict.py -f $imagePath --model $modelPath --topN 5 --partition_num ${partitionNum}

**Comment by anyuecq25** [comment]
When submiting adds these configurations

   --conf spark.eventLog.enabled=true \
    --conf spark.eventLog.dir=hdfs:///spark2-history/ \
    --conf spark.history.fs.logDirectory=hdfs:///spark2-history/ \

it works now, I can get the spark history now.
