### ISSUE TITLE
jenkins: pytorch test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3227]
../test/zoo/orca/learn/ray/pytorch/test_estimator_horovod_backend.py::TestPyTorchEstimator::test_train FAILED [100%]

        assert train_loss2 <= train_loss1, (train_loss2, train_loss1)
>       assert validation_loss2 <= validation_loss1, (validation_loss2,
                                                      validation_loss1)
E       AssertionError: (3.122904405593872, 3.1229036235809327)
E       assert 3.122904405593872 <= 3.1229036235809327

../test/zoo/orca/learn/ray/pytorch/test_estimator_horovod_backend.py:62: AssertionError

jenkins link
http://10.239.47.210:18888/job/ZOO-NB-Python-Spark-2.4-py37-Horovod/86/console

**Comment by helenlly** [comment]
@yangw1234   this error happened again, pls have a look.
 http://10.239.47.210:18888/job/ZOO-NB-Python-Spark-3.0-py37-Horovod/45/

**Comment by pinggao187** [comment]
fix
