### ISSUE TITLE
image-similarity random killed on jenkins

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3281]
#6 start app test for image-similarity

Accuracy = 0.970771 
creating: createRowToImageFeature
creating: createImageResize
creating: createImageCenterCrop
creating: createImageChannelNormalize
creating: createImageMatToTensor
creating: createImageFeatureToTensor
creating: createChainedPreprocessing
2020-12-23 13:54:58 WARN  CaffeLoader:174 - layer prob if type Softmax does not exist in weight file
Killed

Jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Python-AppTests-part1/760/consoleFull

**Comment by glorysdj** [comment]
We can deploy several jenkins slaves with bigger memory limit and try to run apptests job in it to check if it can run successfully. @pinggao18

**Comment by pinggao187** [comment]
Add  new jenkins slave and set the memory limit to 100G.

**Comment by pinggao187** [comment]
fix
