### ISSUE TITLE
TestZouwuModelTCMFForecaster failed for torch1.7.1

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3284]
TestZouwuModelTCMFForecaster.test_forecast_tcmf_xshards

self = <test_tcmf_forecaster.TestZouwuModelTCMFForecaster testMethod=test_forecast_tcmf_xshards>

    def test_forecast_tcmf_xshards(self):
        from zoo.orca import OrcaContext
        import zoo.orca.data.pandas
        import pandas as pd
        OrcaContext.pandas_read_backend = "pandas"
    
        def preprocessing(df, id_name, y_name):
            id = df.index
            data = df.to_numpy()
            result = dict({id_name: id, y_name: data})
            return result
    
        def postprocessing(pred_results, output_dt_col_name):
            id_arr = pred_results["id"]
            pred_results = pred_results["prediction"]
            pred_results = np.concatenate((np.expand_dims(id_arr, axis=1), pred_results), axis=1)
            final_df = pd.DataFrame(pred_results, columns=["id"] + output_dt_col_name)
            final_df.id = final_df.id.astype("int")
            final_df = final_df.set_index("id")
            final_df.columns.name = "datetime"
            final_df = final_df.unstack().reset_index().rename({0: "prediction"}, axis=1)
            return final_df
    
        def get_pred(d):
            return d["prediction"]
    
        with tempfile.NamedTemporaryFile() as temp:
            data = np.random.rand(300, 480)
            df = pd.DataFrame(data)
            df.to_csv(temp.name)
            shard = zoo.orca.data.pandas.read_csv(temp.name)
        shard.cache()
        shard_train = shard.transform_shard(preprocessing, 'id', 'data')
        with self.assertRaises(Exception) as context:
            self.model.fit(shard_train)
>       self.assertTrue("key `y` doesn't exist in x" in str(context.exception))
E       AssertionError: False is not true

../test/zoo/zouwu/model/forecast/test_tcmf_forecaster.py:229: AssertionError

jenkins link:
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-Spark-2.4-py36-ray/1056/console

**Comment by cyita** [comment]
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/work/conda/envs/py36/lib/python3.6/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-36m-x86_64-linux-gnu.so)

Try to update the glibcxx version using:
`
apt-get install software-properties-common
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install gcc-4.9
apt-get install --only-upgrade libstdc++6
`

**Comment by pinggao187** [comment]
pass 
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-Spark-2.4-py36-ray/1080/
