### ISSUE TITLE
Use InenerceModel().Load_tensorflow() load tensorflow pretrained model for inference get error:"TypeError: can't pickle _thread.RLock objects "

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3292]
> Use InenerceModel().Load_tensorflow() load tensorflow pretrained model for inference get error:"TypeError: can't pickle _thread.RLock objects ."The pretrained model is download from
 https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models/inception_v1_2016_08_28.tar.gz 
and export the graph as a frozen inference graph as follow:

import tensorflow as tf
from nets import inception_v1
slim = tf.contrib.slim
images = tf.placeholder(dtype=tf.float32, shape=(None, 224, 224, 3))
with slim.arg_scope(inception_v1.inception_v1_arg_scope()):
    logits, end_points = inception_v1.inception_v1(images, num_classes=1001, is_training=False)
sess = tf.Session()
saver = tf.train.Saver()
saver.restore(sess, "/home/hadoop/wangxk/zoo/new/inception/model/inception-v1/inception_v1.ckpt")
from zoo.util.tf import export_tf
export_tf(sess, "./models/tfnet/", inputs=[images], outputs=[logits])

> Load tensorflow frozenModel as follow:

from zoo.pipeline.inference import InferenceModel
model_path = './model/tfnet/'
model = InferenceModel()
#model.load_tensorflow(model_path)
model.load_tensorflow(model_path,model_type = 'frozenModel',inputs = [images],outputs=[logits])

> get error as follow:

TypeError: can't pickle _thread.RLock objects

**Comment by yangw1234** [comment]
Hi, could you provide the complete output and error message?

**Comment by mamba-8-24** [comment]
the complete output and error message as follow:

creating: createInferenceModel
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-e68f80b5f5e2> in <module>()
      4 model = InferenceModel()
      5 #model.load_tensorflow(model_path)
----> 6 model.load_tensorflow(model_path,model_type = 'frozenModel',inputs = [images],outputs=[logits])

~/anaconda3/lib/python3.6/site-packages/zoo/pipeline/inference/inference_model.py in load_tensorflow(self, model_path, model_type, inputs, outputs, intra_op_parallelism_threads, inter_op_parallelism_threads, use_per_session_threads)
    115                     self.value, model_path, model_type,
    116                     inputs, outputs, intra_op_parallelism_threads,
--> 117                     inter_op_parallelism_threads, use_per_session_threads)
    118 
    119     def load_torch(self, model_path):

~/anaconda3/lib/python3.6/site-packages/zoo/common/utils.py in callZooFunc(bigdl_type, name, *args)
    118     """ Call API in PythonBigDL """
    119     gateway = _get_gateway()
--> 120     args = [_py2java(gateway, a) for a in args]
    121     error = Exception("Cannot find function: %s" % name)
    122     for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:

~/anaconda3/lib/python3.6/site-packages/zoo/common/utils.py in <listcomp>(.0)
    118     """ Call API in PythonBigDL """
    119     gateway = _get_gateway()
--> 120     args = [_py2java(gateway, a) for a in args]
    121     error = Exception("Cannot find function: %s" % name)
    122     for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in _py2java(gateway, obj)
    669         obj = obj._jsc
    670     elif isinstance(obj, (list, tuple)):
--> 671         obj = ListConverter().convert([_py2java(gateway, x) for x in obj],
    672                                       gateway._gateway_client)
    673     elif isinstance(obj, dict):

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in <listcomp>(.0)
    669         obj = obj._jsc
    670     elif isinstance(obj, (list, tuple)):
--> 671         obj = ListConverter().convert([_py2java(gateway, x) for x in obj],
    672                                       gateway._gateway_client)
    673     elif isinstance(obj, dict):

~/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py in _py2java(gateway, obj)
    683         pass
    684     else:
--> 685         data = bytearray(PickleSerializer().dumps(obj))
    686         obj = gateway.jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.loads(data)
    687     return obj

~/anaconda3/lib/python3.6/site-packages/pyspark/serializers.py in dumps(self, obj)
    452 
    453     def dumps(self, obj):
--> 454         return pickle.dumps(obj, pickle_protocol)
    455 
    456     if sys.version >= '3':

TypeError: can't pickle _thread.RLock objects

**Comment by yangw1234** [comment]
```python
model.load_tensorflow(model_path,model_type = 'frozenModel',inputs = [images],outputs=[logits])
```
For the `inputs` and `outputs` arguments, I think you should use string name of the tensor, instead of the tensor object. In a real case, there will be no tensor object (images, logits) before you load your tensorflow model.

**Comment by mamba-8-24** [comment]
`model.load_tensorflow(model_path,model_type = 'frozenModel',inputs = ["Placeholder:0"],outputs=["InceptionV1/Logits/SpatialSqueeze:0"], intra_op_parallelism_threads=2)`
I set inputs and outputs using use string name of the tensor as above ,there are no errors,thank you so much!
