### ISSUE TITLE
init_spark_on_yarn() got an unexpected keyword argument 'num_executor'

### ISSUE THREAD

**Issue by wo823479193** [intel-analytics/analytics-zoo#3305]
### envs：
      analytics_zoo-0.9.0.dev0-20200814-py2.py3-none-manylinux1_x86_64.whl
      BigDL-0.12.1-py2.py3-none-manylinux1_x86_64.whl
      CDH6.3.2
### **Expected to achieve**
   I deployed a CDH cluster and then expected to implement Yarn-Client mode with JUPyter on one of the CDH cluster nodes.

### **I use it as shown below:** 
![image](https://user-images.githubusercontent.com/15995988/103399733-6ad0dc00-4b7d-11eb-83c4-583f5720f364.png)

### **conda list in analytics_zoo env**
![image](https://user-images.githubusercontent.com/15995988/103400305-9654c600-4b7f-11eb-871a-2407e37c3de4.png)

### **error**
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoo import init_spark_on_yarn
Prepending /opt/cloudera/parcels/Anaconda/envs/zoo/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /opt/cloudera/parcels/Anaconda/envs/zoo/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar to BIGDL_JARS
Prepending /opt/cloudera/parcels/Anaconda/envs/zoo/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
>>> sc = init_spark_on_yarn(
...     hadoop_conf="/etc/hadoop/conf",
...     conda_name="zoo", # The name of the created conda-env
...     num_executor=1,
...     executor_cores=4,
...     executor_memory="8g",
...     driver_memory="2g",
...     driver_cores=4,
...     extra_executor_memory_for_ray="10g")
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
TypeError: init_spark_on_yarn() got an unexpected keyword argument 'num_executor'

why?

**Comment by hkvision** [comment]
Hi @wo823479193 

Sorry that this is a typo in our documentation. It should be `num_executors`.
Thanks for pointing it out.

**Comment by hkvision** [comment]
Hi @wo823479193 This issue has been fixed. Sorry for the inconvenience caused. Feel free to tell us if you encounter further problems.

**Comment by hkvision** [comment]
https://analytics-zoo.github.io/master/#ProgrammingGuide/rayonspark/ The updated documentation page.
