### ISSUE TITLE
Zoo CLuster-Servering  CPU isolation doesn't work , and the CPU utilization is full ,  all CPU resources will be used 

### ISSUE THREAD

**Issue by qinkaixin365** [intel-analytics/analytics-zoo#3315]
The flink   parameters yarn.containers.vcores has been set,  also yarn can display the number of cores which is used ，but  the actual number of cores used will exceed the number of cores set， all CPU resources will be used !

**Comment by glorysdj** [comment]
looks like an issue of flink deployment on yarn, we are trying to reproduce this on yarn cluster.

**Comment by Litchilitchy** [comment]
Hi @qinkaixin365 , after checking flink source code and our flink ui on yarn, we found:

1. Flink set `vcores` config to task slot, which is Flink thread control.
2. Beyond task slot, the cpu cores you can access is still get by `java.lang.Runtime.availableProcessors()`.

To summarize, to our reproduce so far

1. Yarn does not have strong isolation, JVM will read cpu info regardless of Yarn vcores
2. Flink use JVM to read the cpu core outside its taskmanager container. If you do not want this read, you could submit an issue to Flink
3. Flink use Yarn `vcores` to control task slot number. Cluster Serving uses OMP cpu acceleration, which could bypass the task slot number restriction. If you want to limit it, you can use `numactl` to start taskmanager and Flink could read only cpu cores set by `numactl`, this is proved to work well.
4. Through OMP could bypass task slot, I am not sure if Flink read cores from vcores, could OMP still bypass it.

**Comment by Litchilitchy** [comment]
for 4,  request confirm from  @qiyuangong

**Comment by qinkaixin365** [comment]
thanks ，have any recommended settings ? I just want to CPU isolation .shoud I refer to method three?

**Comment by Litchilitchy** [comment]
@qinkaixin365 yes, you can `numactl` the cpu cores you want to isolate in one taskmanager. `numactl` is the core technique here, you could look it up.

**Comment by qinkaixin365** [comment]
need every job to be operated manually ? I think  it is  not suitable production environment method ，Can it be automatic setting ?

**Comment by Litchilitchy** [comment]
@qinkaixin365 you could use write a script to call `numactl`, and `numactl` seems to only work in standalone but not yarn, sorry for wrong advice above..

By the way there is a much easier way you could try. set yarn config `containerized.taskmanager.env.OMP_NUM_THREADS=number_of_core_you_want_to_use` to simply config the OMP parallelism here. You could try this to see if it works.

Also, ignore what the Flink UI shows about the core number. It just reads from JVM.

**Comment by qinkaixin365** [comment]
I will try this method , If hava any idea ，please let me konw!

**Comment by helenlly** [comment]
@qinkaixin365 any update on the issue?
