### ISSUE TITLE
XShards.partition doesn't support OrcaContext.log_output = True

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/analytics-zoo#3331]
We recommended to set `OrcaContext.log_output` to True to display stdout and stderr output on Jupyter Notebook. `XShards.partition` doesn't support `OrcaContext.log_output = True`

```
OrcaContext.log_output = True 
init_orca_context(cluster_mode="local", cores=4, memory="3g")

from zoo.orca.data import XShards
train_shards = XShards.partition({"x": train_images, "y": train_label_images})
val_shards = XShards.partition({"x": val_images, "y": val_label_images})
```

/usr/local/lib/python3.6/dist-packages/zoo/common/nncontext.py in init_nncontext(conf, spark_log_level, redirect_spark_log)
    369 
    370     if ZooContext.log_output:
--> 371         if spark_jvm_proc.stdout is not None:
    372             stdout_reader = threading.Thread(target=_read_stream,
    373                                              daemon=True,

AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by jason-dai** [comment]
@yangw1234 please take a look.

**Comment by yangw1234** [comment]
I'm looking into it

**Comment by yangw1234** [comment]
It seems `init_nncontext` cannot be called twice when setting `OrcaContext.log_output` to True
