### ISSUE TITLE
add integration test for autots

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/analytics-zoo#3343]
We can change [zouwu quickstart notebook](https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/colab-notebook/zouwu/zouwu_autots_nyc_taxi.ipynb) to an example and add in [integration test](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/run-example-tests-yarn-integration.sh).

**Comment by shane-huang** [comment]
You can add the new example to https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/zouwu/examples/quickstart.

**Comment by shane-huang** [comment]
Move the original files in the exmaple folder (README and run_electricity.sh) to https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/zouwu/examples/tcmf. Search the repo for run_electricity.sh and fix the references to this file including docs and tests scripts.

**Comment by PeterQiu0516** [comment]
> Move the original files in the exmaple folder (README and run_electricity.sh) to https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/zouwu/examples/tcmf. Search the repo for run_electricity.sh and fix the references to this file including docs and tests scripts.

See #3774.
