### ISSUE TITLE
Use init_spark_on_yarn runing zouwu example get PermissionError: [Errno 13] Permission denied: '/root/zoo_automl_logs'

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3354]
Use init_spark_on_yarn runing zouwu example get PermissionError: [Errno 13] Permission denied: '/root/zoo_automl_logs'
analytics-zoo version is  analytics_zoo-0.10.0.dev0-20210108-py2.py3-none-manylinux1_x86_64.whl ：

> 

> from zoo import init_spark_on_local
> from zoo import init_spark_on_yarn
> from zoo.ray import RayContext
> #sc = init_spark_on_local(cores=4, spark_log_level="INFO")
> num_exe = 3
> core_exe = 2
> #batch_size = num_exe * core_exe 
> sc = init_spark_on_yarn(
>     hadoop_conf="/etc/hadoop/3.0.1.0-187/0/",
>     hadoop_user_name='hdfs',
>     conda_name="zoo-tf1.15", # The name of the created conda-env
>     num_executors=num_exe,
>     executor_cores=core_exe,
>     executor_memory="4g",
>     driver_memory="4g",
>     driver_cores=2,
>     extra_executor_memory_for_ray="2g")
> ray_ctx = RayContext(sc=sc, object_store_memory="2g")
> ray_ctx.init()

AutoTSTrainer is defined as follow：

> from zoo.zouwu.autots.forecast import AutoTSTrainer
> trainer = AutoTSTrainer(dt_col="datetime",
>                         target_col="AvgRate",
>                         horizon=1,
>                         extra_features_col=None)

and  train as follow：

> ts_pipeline = trainer.fit(train_df, val_df, 
>                           #distributed=True,
>                           recipe=LSTMGridRandomRecipe(
>                               num_rand_samples=1,
>                               look_back=look_back, 
>                               batch_size=[64]),
>                           metric="mse")

the error is as follows：

> ray.exceptions.RayTaskError(PermissionError): ^[[36mray::WrappedTrackFunc.__init__()^[[39m (pid=16255, ip=10.180.210.62)
>   File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
>"/hadoop/yarn/local/usercache/hdfs/appcache/application_1609312782049_0038/container_e08_1609312782049_0038_01_000003/python_env/lib/python3.6/site-packages/ray/tune/trainable.py", line 153, in __init__
>     self._result_logger = logger_creator(self.config)
>   File "/root/anaconda3/envs/zoo-tf1.15/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 113, in logger_creator
>   File "python_env/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "python_env/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "python_env/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/root/zoo_automl_logs'
>

**Comment by yushan111** [comment]
We have exposed `logs_dir` in `AutoTSTrainer` for user configuration in PR #3355 .
We will also change the default `logs_dir` to tmp to avoid permission issues. I have opened an issue (issue #3352 ) for that.
