### ISSUE TITLE
Colab notebook (tf_lenet_mnist.ipynb)

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#3359]
https://colab.research.google.com/github/intel-analytics/analytics-zoo/blob/master/docs/docs/colab-notebook/orca/quickstart/tf_lenet_mnist.ipynb

1) Change `Set jdk environment path which enables you to run Pyspark in your Colab environment` to `Set environment variable JAVA_HOME`

2) Change epho number from 5 to 1 (with 98% accuracy)

**Comment by Le-Zheng** [comment]
@jason-dai  It still seems using 1 core when setting 2 cores.  In the log, thread pool and op thread(in evaluation) are the same for setting 1 core and 2 cores.  Monitoring cpu usage (some online methods) on colab also seems not very clear to get a conclusion.

**Comment by jason-dai** [comment]
> @jason-dai It still seems using 1 core when setting 2 cores. In the log, thread pool and op thread(in evaluation) are the same for setting 1 core and 2 cores. Monitoring cpu usage (some online methods) on colab also seems not very clear to get a conclusion.

Run `!cat /proc/cpuinfo`, I see two processors (maybe one core and two threads)
