### ISSUE TITLE
Pytorch mode: Method createFeatureSetFromPytorch does not exist

### ISSUE THREAD

**Issue by longmingg** [intel-analytics/analytics-zoo#3367]
when I make a pytorch test on yarn, it print following exception:
    Py4JException: Method createFeatureSetFromPytorch([class [B, class java.lang.Boolean, class java.lang.String, class java.lang.String]]) does not exist

And after seconds，it stop and throws exception:
    java.util.concurrent.TimeoutException: Future timed out after [100 seconds]

The code is very simple for test:
    test = TensorDataset(torch.Tensor([[1], [2], [3], [4]), torch.Tensor([[1], [2], [3], [4]))
    test = DataLoader(test, batch_size=1)
    test = FeatureSet.pytorch_dataloader(test, "", "")

thx, expect for your replay

**Comment by cyita** [comment]
Could you please provide the version of analytics-zoo, PyTorch, and python you used?

**Comment by longmingg** [comment]
> Could you please provide the version of analytics-zoo, PyTorch, and python you used?

thx for your replay, I have solved this problem, I guess it because I manually set the 'penv_archive' and 'spark.yarn.jars' or python version, I delete two params and  change python version from 3.6.5 to 3.7, it works
