### ISSUE TITLE
tf1 quick-start is much slower than tf2 quick-start

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#3395]

**Comment by yangw1234** [comment]
@jason-dai 
There are several reasons for why tf1 quick start is much slower than tf2's quick start:

1. the model we are using in tf1 notebook is slightly larger than tf2's model
2. for our model (after fixing 1), for intel-tensorflow 1.15.0 **each iteration takes twice times** as the official tensorflow 1.15.0
3. after setting "TF_DISABLE_MKL" to "1", for intel-tensorflow **each iteration takes 1.3 times** as the official tensorflow
4. Using "TF_DISABLE_MKL" on analytics zoo takes little effect on this particular model, because bigdl will first load MKL 2019 UPDATE 3 , but TensorFlow use MKL 2019 UPDATE 5.

**Comment by jason-dai** [comment]
> @jason-dai
> There are several reasons for why tf1 quick start is much slower than tf2's quick start:
> 
> 1. the model we are using in tf1 notebook is slightly larger than tf2's model
> 2. for our model (after fixing 1), for intel-tensorflow 1.15.0 **each iteration takes twice times** as the official tensorflow 1.15.0
> 3. after setting "TF_DISABLE_MKL" to "1", for intel-tensorflow **each iteration takes 1.3 times** as the official tensorflow
> 4. Using "TF_DISABLE_MKL" on analytics zoo takes little effect on this particular model, because **the wrong version of MKL got used** in analytics zoo by tensorflow.  (Bigdl will first load MKL 2019 UPDATE 3 , but TensorFlow requires MKL 2019 UPDATE 5)

Shall we switch to MKL 2019 UPDATE 5 in BigDL?

**Comment by yangw1234** [comment]
opened an issue in bigdl https://github.com/intel-analytics/BigDL/issues/3107
closing this
