### ISSUE TITLE
How to dependency  it in  scala sbt project with spark 3.0

### ISSUE THREAD

**Issue by mullerhai** [intel-analytics/analytics-zoo#3409]
HI,  
    now I want to use analytics-zoo some defined layer  like Transformer or model   BERT , so I want to import analytics-zoo in my scala proeject with spark 3.0,  do we  have  jar pakage in maven repo ? I find some  user use it like 
      "com.intel.analytics.zoo" % "analytics-zoo-bigdl_0.10.0-spark_2.4.3" % "0.8.1" , but  not find  now in maven repo.
and  do we upgrade  this project to support scala 2.12 and spark 3.0?
thanks
muller

**Comment by jason-dai** [comment]
See https://analytics-zoo.github.io/master/#ScalaUserGuide/install/; the latest Analytics Zoo release (v0.9.0) does support Spark 3.0 and Scala 2.12 (see https://search.maven.org/search?q=analytics-zoo-bigdl).

**Comment by helenlly** [comment]
@mullerhai  any more questions? if no, we may close the issue soon.

**Comment by helenlly** [comment]
close due to no response for a long time.
