### ISSUE TITLE
Chronos user-case notebook should be refactor to use TSDataset

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#3417]
Some functions and customized code is used in Zouwu user-case notebook. Including
Those can be easily changed to built-in codes in zouwu: metrics
Those need to be included in zouwu: isolated rolling and plot functions

This issue is related to or part of issue #3103

**Comment by yushan111** [comment]
For [network_traffic_model_forecasting notebook](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_model_forecasting.ipynb),

- [ ] Replace `gen_dataset_matrix` with zouwu API. Note that you need to modify [the roll data function](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/feature/time_sequence.py#L431) in zouwu feature for better support. 
- [ ] Replace the scaling code and `unscale` with zouwu API.  You need to modify the [scale](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/feature/time_sequence.py#L509) and [uncale](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/feature/time_sequence.py#L431)  function in zouwu feature for better support.
- [ ] replace the data fill code (ffill) with [zouwu impute API](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/zouwu/preprocessing/impute/impute.py).
- [ ] replace `sMAPE` with automl metric. You can find the definition of smape [here](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/automl/common/metrics.py#L74)
