### ISSUE TITLE
When I use the  model  to inference in cluster serving, the error is occured

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3433]
When I use the face-detection-0200 model of openvino download from openvino official website to inference in cluster serving, the error is occured.
[face_detection_log.zip](https://github.com/intel-analytics/analytics-zoo/files/5877143/face_detection_log.zip)

**Comment by gtfaiwxm** [comment]
this is model files
[face_detection.zip](https://github.com/intel-analytics/analytics-zoo/files/5877185/face_detection.zip)

**Comment by Litchilitchy** [comment]
Please just post the log here for others to refer, and share the model link if you just download it from OpenVINO official.
