### ISSUE TITLE
textclassification example test failed

### ISSUE THREAD

**Issue by torymac1** [intel-analytics/analytics-zoo#344]
1. If using --model=local[*] as required in readme, 
Error: Caused by: java.lang.IllegalArgumentException: requirement failed: total batch size: 128 should be divided by total core number: 28

2. If using correct command, eg --model=local[16], nothing outputted while running.

Script:
export ANALYTICS_ZOO_JAR=${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-0.1.0-SNAPSHOT-jar-with-dependencies.jar
export BASE_DIR=/home/sangtian/zoo_test/textclassification/

spark-submit \
    --master=local[16] \
    --driver-memory 20g \
    --executor-memory 20g \
    --class com.intel.analytics.zoo.examples.textclassification.TextClassification \
    ${ANALYTICS_ZOO_JAR} \
    --baseDir ${BASE_DIR}

**Comment by hkvision** [comment]
Synced offline and the problem got resolved.
Probably due to spark2.2 configurations, after setting log level to INFO, training results can be printed out.
