### ISSUE TITLE
the result of cluster serving inferences is base64 mode using output_api.dequeue() function

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3440]
When I use cluster serving to inference the model of object detection, the result of output_api.dequeue() is base64 mode. While I use the output_api.query(image_name) function, the result is normal.

**Comment by Litchilitchy** [comment]
hi @gtfaiwxm 

This issue is fixed at PR

https://github.com/intel-analytics/analytics-zoo/pull/3441

You could use nightly-builit version to check
