### ISSUE TITLE
在analytics-zoo环境中创建sparksession对象连接hive报错 

### ISSUE THREAD

**Issue by zous694** [intel-analytics/analytics-zoo#3462]

**Comment by zous694** [comment]
sc = init_spark_on local()
spark = sparksession.builder.config("hive.metastore.uris","thrift：//bdpmaster.spdbbiz.com:9083").enableHivesupport().getorcreat()
data = spark.sql("select * from tbl").toPandas()

大致报错如下：
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.2ANTLR....................
uncaught error in thred spark-listener-group-eventlog
stopping sparkcontext:
java.lang.no such method error.org.json4s.jackson xxxxxxxxxxxxxx
xxxxxxxxxxx
py4jtavaerror :An error occured while calling 0111.showstring
:java.lang.IllegalstateException:sparkcontext has been shut down

**Comment by helenlly** [comment]
xin, pls have a look

**Comment by qiuxin2012** [comment]
related issue https://github.com/intel-analytics/analytics-zoo/issues/2867

**Comment by qiuxin2012** [comment]
User will get this ANTLR Tool version missmatch error, if user have both `SPARK_HOME` environment(Cloudera CDH 2.2.0) and `pyspark 2.4.3` installed in python, unset Cloudera's SPARK related environments will solve this issue.
