### ISSUE TITLE
the dequeue method of cluster serving occured error

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3468]
When I use the dequeue() of cluster serving, the error is occured. 
Error: Incorrect padding

**Comment by Litchilitchy** [comment]
@gtfaiwxm  please post more details of error

**Comment by gtfaiwxm** [comment]
Error                                     Traceback (most recent call last)
<ipython-input-5-10e450cdaa6e> in <module>
      2 
      3 output_api = OutputQueue(host = 'xx.xx.xx.xx',port = '6379')
----> 4 result = output_api.dequeue()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/serving/client.py in dequeue(self)
    213             res_id = res.decode('utf-8').split(":")[1]
    214             res_value = res_dict[b'value'].decode('utf-8')
--> 215             decoded[res_id] = self.get_ndarray_from_b64(res_value)
    216             self.db.delete(res)
    217         return decoded

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/serving/client.py in get_ndarray_from_b64(self, b64str)
    233 
    234     def get_ndarray_from_b64(self, b64str):
--> 235         b = base64.b64decode(b64str)
    236         a = pa.BufferReader(b)
    237         c = a.read_buffer()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/base64.py in b64decode(s, altchars, validate)
     85     if validate and not re.match(b'^[A-Za-z0-9+/]*={0,2}$', s):
     86         raise binascii.Error('Non-base64 digit found')
---> 87     return binascii.a2b_base64(s)
     88 
     89 

Error: Incorrect padding

**Comment by gtfaiwxm** [comment]
Input: 
resized_img = cv2.imread('image/path')
resized_img = resized_img/255.
input_api.enqueue(img_file, t=resized_img)

**Comment by Litchilitchy** [comment]
@gtfaiwxm could you use following commands in terminal
```
$REDIS_HOME/src/redis-cli
keys *
```
find your output result, it should be sth like `cluster-serving_.....img_file`. and still in Redis cli terminal,
```
hgetall $the_key_shown_just_now
```
and post the result here

**Comment by gtfaiwxm** [comment]
The result after executing the above command is that (empty list or set)

**Comment by Litchilitchy** [comment]
@gtfaiwxm when there is no result, it should be `[]` instead of decoding base64

not sure what's happened, could you share the full code piece here?

**Comment by gtfaiwxm** [comment]
Ok.
`import os
import cv2
import time
import numpy as np
import matplotlib.pyplot as plt
from zoo.serving.client import InputQueue, OutputQueue
img_path = 'images'
img_files = os.listdir(img_path)
input_api = InputQueue(host = 'xx.xx.xx.xx',port = '6379')
resize_shape = (480,480)
def letterbox_image(img, inp_dim):
    img_w,img_h = img.shape[1],img.shape[0]
    w, h = inp_dim
    scale = min(w / img_w, h / img_h)
    new_w = int(img_w * scale)
    new_h = int(img_h * scale)
    resized_img = cv2.resize(img,(new_w,new_h))
    padd_img = np.full((h,w,3),0)
    padd_img[(h-new_h)//2:(h-new_h)//2+new_h,(w-new_w)//2:(w-new_w)//2+new_w] = resized_img
    return padd_img
for i in range(100):
    for img_file in img_files:
        if not img_file.endswith('.jpg'):
            continue
        img = cv2.imread(os.path.join(img_path, img_file))
        resized_img = letterbox_image(img, resize_shape)
        resized_img = resized_img/255.
        input_api.enqueue(img_file, t=resized_img)
output_api = OutputQueue(host = 'xx.xx.xx.xx',port = '6379')
result = output_api.dequeue()
`

**Comment by Litchilitchy** [comment]
@gtfaiwxm This is a bug when there is no result, will fix soon and update here.

**Comment by gtfaiwxm** [comment]
Hello, what results do you need? the output of redis-cli?

**Comment by Litchilitchy** [comment]
> Hello, what results do you need? the output of redis-cli?

yes, just copy the terminal here

**Comment by gtfaiwxm** [comment]
When the memory of redis is filled with image data, the error is occured.

**Comment by Litchilitchy** [comment]
Does this issue still exist?

**Comment by helenlly** [comment]
@gtfaiwxm  any update on the issue? or Does this issue still exist?

**Comment by helenlly** [comment]
close since no response.
