### ISSUE TITLE
sc = init_spark_on_local(cores=4) is failed

### ISSUE THREAD

**Issue by Matrix-World** [intel-analytics/analytics-zoo#3483]
I set up RayOnSpark according to the document（https://analytics-zoo.github.io/master/#ProgrammingGuide/rayonspark/）, 
but when I execute：sc = init_spark_on_local(cores=4), the following error occurs:
py4j.protocol.Py4JavaError:An error occured while calling None.org.apche.spark.api.java.JavaSparkContext.
I checked the installation package, the version is as follows:
analytics-zoo-0.0.9
pyarrow-0.17.0
ray-0.8.4
These versions are consistent with the requirements of the document without errors, which troubles me.

**Comment by hkvision** [comment]
Hi @Matrix-World 

Seems there's error initializing spark. Can you check your pyspark installation (we've tested on 2.4.3). Note that if you use pyspark you are recommended to unset SPARK_HOME in your environment).

If your pyspark is installed, can you just type `pyspark` in the command line to verify whether the sc can be created successfully?

**Comment by helenlly** [comment]
@Matrix-World any update on the issue? if no more questions, we will close the issue soon.

**Comment by helenlly** [comment]
close due to no response for a long time.
