### ISSUE TITLE
Does the cluster serving support simultaneous inference of multiple different models?

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3484]
What should I do when I want to use the cluster serving for multiple different model inferences?

**Comment by Litchilitchy** [comment]
You could set in `config.yaml` file with param `model: name:`

the default is `serving_stream`, if you do not config this, it is not allowed to start two `serving_stream` serving

you can set it e.g. `serving2` and start, then there are two serving jobs named `serving_stream` and `serving2`.

**Comment by gtfaiwxm** [comment]
hi, can you give me an example to set the config?

**Comment by gtfaiwxm** [comment]
In addition， I want to know how to put the image data into different models when I use the cluster serving for multiple different model inferences

**Comment by gtfaiwxm** [comment]
Hi. Can you give me an example to use the cluster-serving for simultaneous inferencing the different models? I set the configuration in the way you said, and the result is empty during inference.

**Comment by glorysdj** [comment]
you should also deploy another http front end for the second model with different conf for redis, especially the redisInputQueue and redisOutputQueue
please refer to https://analytics-zoo.github.io/master/#ClusterServingGuide/ProgrammingGuide/

**Comment by gtfaiwxm** [comment]
Hi, @glorysdj. In other words, the cluster-serving don't support simultaneous inference of multiple different models. Is it right?

**Comment by glorysdj** [comment]
Hi @gtfaiwxm  Actually, several http frontend can be deployed with different models: let's say, there is a model1 using redisinput1 and redisoutput1, and also a model2 using redisinput2 and redisoutput2, you can deploy 2 http frontends with redisinput1/redisoutput1 at host1:port1 and with redisinput2/redisoutput2 at host2:port2, with the same cluster serving, you can do simultaneous inference of multiple different models, using http://host1:port1/predict and http://host2:port2/predict

**Comment by Litchilitchy** [comment]
@glorysdj @gtfaiwxm please refer to latest doc [here](https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ClusterServingGuide/ProgrammingGuide.md#start-multiple-serving)
