### ISSUE TITLE
When I use cluster serving infer the frozen model of tensorflow, the names of pb and json must be fixed.

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3485]
When I use cluster serving infer the frozen model of tensorflow, the names of pb and json must be fixed as frozen_inference_grapg.pb and grapg_meta.json. This is not user-friendly. I hope intel can optimize it in time.

**Comment by Litchilitchy** [comment]
This is regulated in API lower than Cluster Serving. @jason-dai

**Comment by gtfaiwxm** [comment]
Hi, Does the intel optimize it in the new version of cluster-serving?

**Comment by helenlly** [comment]
@yangw1234  pls have a look

**Comment by yangw1234** [comment]
hi @gtfaiwxm, would you share more detail of the requirement? 

As far as I know, the `frozen_inference_graph.pb` does not encode any information about which tensor(s) is the input and which is the output. As a result, we need the caller to tell us the names of input and output tensor(s), so that we can find them in the `frozen_inference_graph.pb`. Currently, the way you tell us is to use a `graph_meta.json` file.

What API do you have in mind? However, I think, you need to tell us the names one way or another (written in a json file or passing in as function arguments).

**Comment by jason-dai** [comment]
> hi @gtfaiwxm, would you share more detail of the requirement?
> 
> As far as I know, the `frozen_inference_graph.pb` does not encode any information about which tensor(s) is the input and which is the output. As a result, we need the caller to tell us the names of input and output tensor(s), so that we can find them in the `frozen_inference_graph.pb`. Currently, the way you tell us is to use a `graph_meta.json` file.
> 
> What API do you have in mind? However, I think, you need to tell us the names one way or another (written in a json file or passing in as function arguments).

I think the question is about the fixed file names @yangw1234

**Comment by yangw1234** [comment]
> > hi @gtfaiwxm, would you share more detail of the requirement?
> > As far as I know, the `frozen_inference_graph.pb` does not encode any information about which tensor(s) is the input and which is the output. As a result, we need the caller to tell us the names of input and output tensor(s), so that we can find them in the `frozen_inference_graph.pb`. Currently, the way you tell us is to use a `graph_meta.json` file.
> > What API do you have in mind? However, I think, you need to tell us the names one way or another (written in a json file or passing in as function arguments).
> 
> I think the question is about the fixed file names @yangw1234

@jason-dai I see. We already have an API in scala `TFNet(path: String, inputNames: Arrray[String], outputNames: Array[String])`. I think it is easy to wrap this api from Cluster Serving side. Also @Litchilitchy

**Comment by gtfaiwxm** [comment]
hi @yangw1234 I mean I don’t want my names of .pb and .json file to be the frozen_inference_graph.pb and graph_meta.json for cluster-serving. I hope the name can be customized.

**Comment by Litchilitchy** [comment]
As we discussed in our team, as `graph_meta.json` is provided from user (and this is the additional part from native Tensorflow), the regulation of `.pb` name makes sense, and this part would not change currently.
