### ISSUE TITLE
"zoo.orca.learn.tf.estimator" must require 'ray'?

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/analytics-zoo#3499]
After executing `pip install --pre analytics-zoo` and running `from zoo.orca.learn.tf.estimator import Estimator`, it occurs `ModuleNotFoundError: No module named 'ray'`.

**Comment by yushan111** [comment]
fix in PR #3500

**Comment by yushan111** [comment]
The PR has been merged and you may try again.
