### ISSUE TITLE
jenkins: UT random failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3528]
FAILED ../test/zoo/pipeline/api/keras/test_layer.py::TestLayer::test_bert_forward_backward

a = ('xro12265', <py4j.java_gateway.GatewayClient object at 0x7f747bd2ba50>, 'o46', 'createZooKerasModel')
kw = {}
s = 'java.lang.IllegalArgumentException: requirement failed: Some module is duplicate in the current model: InternalCMulTablef8e4e752_wrapper'
stackTrace = 'scala.Predef$.require(Predef.scala:224)\n\t at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.checkDuplicate(...nd.java:79)\n\t at py4j.GatewayConnection.run(GatewayConnection.java:238)\n\t at java.lang.Thread.run(Thread.java:748)'

    def deco(*a, **kw):
        try:
            return f(*a, **kw)
        except py4j.protocol.Py4JJavaError as e:
            s = e.java_exception.toString()
            stackTrace = '\n\t at '.join(map(lambda x: x.toString(),
                                             e.java_exception.getStackTrace()))
            if s.startswith('org.apache.spark.sql.AnalysisException: '):
                raise AnalysisException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.catalyst.analysis'):
                raise AnalysisException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.catalyst.parser.ParseException: '):
                raise ParseException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.streaming.StreamingQueryException: '):
                raise StreamingQueryException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.execution.QueryExecutionException: '):
                raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('java.lang.IllegalArgumentException: '):
>               raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
E               pyspark.sql.utils.IllegalArgumentException: 'requirement failed: Some module is duplicate in the current model: InternalCMulTablef8e4e752_wrapper'

/opt/work/spark-2.4.3/python/lib/pyspark.zip/pyspark/sql/utils.py:79: IllegalArgumentException

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/941/console

a = ('xro16043', <py4j.java_gateway.GatewayClient object at 0x7f7a2196ba10>, 'o46', 'createZooKerasModel')
kw = {}
s = 'java.lang.IllegalArgumentException: requirement failed: Some module is duplicate in the current model: Square56ff93bd'
stackTrace = 'scala.Predef$.require(Predef.scala:224)\n\t at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.checkDuplicate(...nd.java:79)\n\t at py4j.GatewayConnection.run(GatewayConnection.java:238)\n\t at java.lang.Thread.run(Thread.java:748)'

    def deco(*a, **kw):
        try:
            return f(*a, **kw)
        except py4j.protocol.Py4JJavaError as e:
            s = e.java_exception.toString()
            stackTrace = '\n\t at '.join(map(lambda x: x.toString(),
                                             e.java_exception.getStackTrace()))
            if s.startswith('org.apache.spark.sql.AnalysisException: '):
                raise AnalysisException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.catalyst.analysis'):
                raise AnalysisException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.catalyst.parser.ParseException: '):
                raise ParseException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.streaming.StreamingQueryException: '):
                raise StreamingQueryException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('org.apache.spark.sql.execution.QueryExecutionException: '):
                raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
            if s.startswith('java.lang.IllegalArgumentException: '):
>               raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
E               pyspark.sql.utils.IllegalArgumentException: 'requirement failed: Some module is duplicate in the current model: Square56ff93bd'

/opt/work/spark-2.4.3/python/lib/pyspark.zip/pyspark/sql/utils.py:79: IllegalArgumentException

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/930/console

**Comment by hkvision** [comment]
@dding3 This issue seems occur from time to time. Take a look.

**Comment by pinggao187** [comment]
pass
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.3-PYTHON/
