### ISSUE TITLE
Spark DataFrame Support in Orca

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#3571]
- [x] openvino estimator predict
- [x] bigdl estimator evalute (fit is implemented using nnestimator and nnmodel, but nnestimator and nnmodel does not have evaluate)

**Comment by yangw1234** [comment]
@GZHoffie would you mind working on the "openvino predict" problem.

**Comment by GZHoffie** [comment]
> @GZHoffie would you mind working on the "openvino predict" problem.

OK, I will take a look.
