### ISSUE TITLE
Jenkins: deploy hyperzoo failed 

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3573]
[0m[91m2021-03-10 21:38:29 (7.33 MB/s) - 'analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-20210310.201912-55-cluster-serving-all.zip' saved [678567688/678567688]

[0mArchive:  analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-20210310.201912-55-cluster-serving-all.zip
   creating: cluster-serving/
  inflating: cluster-serving/cluster-serving-py-setup.py  
  inflating: cluster-serving/cluster-serving-init  
  inflating: cluster-serving/download-serving-jar.sh  
  inflating: cluster-serving/cluster-serving-stop  
  inflating: cluster-serving/config.yaml  
  inflating: cluster-serving/cluster-serving-shutdown  
  inflating: cluster-serving/cluster-serving-start  
  inflating: cluster-serving/cluster-with-numactl.sh  
  inflating: cluster-serving/cluster-serving-restart  
  inflating: cluster-serving/cluster-serving-cli  
   creating: test_image/
  inflating: test_image/fish1.jpeg   
  inflating: test_image/dog1.jpeg    
  inflating: test_image/cat1.jpeg    
 extracting: cluster-serving/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-http.jar  
 extracting: cluster-serving/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-cluster-serving-python.zip  
 extracting: cluster-serving/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-serving.jar  
 ---> 5a64c05b1e17
Removing intermediate container 62ffeb518439
Step 52 : RUN cd cluster-serving &&     ./cluster-serving-setup.sh
 ---> Running in 688a5e0e7f51
[91m/bin/sh: ./cluster-serving-setup.sh: No such file or directory
[0mThe command '/bin/sh -c cd cluster-serving &&     ./cluster-serving-setup.sh' returned a non-zero code: 127

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Deploy-Docker/747/console

**Comment by glorysdj** [comment]
the file is removed by https://github.com/intel-analytics/analytics-zoo/pull/3542

**Comment by pinggao187** [comment]
pass
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Deploy-Docker/750/
