### ISSUE TITLE
jenkins: scala exampletest timeout 12h 

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3671]
(2/2) Start the Yarn Test Suite
spark_2.x
start to build jar
make-dist.sh -P spark_2.x -Dbigdl.version=0.12.1...
build jar finished
begin session recommender

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Scala-ExampleTests/1273/console

**Comment by glorysdj** [comment]
After investigation, it's caused by yarn unhealthy nodes, please clear disk space by removing finished applications. @pinggao187

**Comment by pinggao187** [comment]
pass 
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Scala-ExampleTests/1274/console
