### ISSUE TITLE
jenkins： UT test  PEP8 checks failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3706]
/opt/work/jenkins/workspace/ZOO-NB-UnitTests-2.3-PYTHON/pyzoo/dev/..
PEP8_SCRIPT_PATH /opt/work/jenkins/workspace/ZOO-NB-UnitTests-2.3-PYTHON/pyzoo/dev/../dev/pep8-1.7.0.py
PEP8 checks failed.
./zoo/serving/client.py:26:1: E302 expected 2 blank lines, found 1
./zoo/serving/client.py:37:1: E302 expected 2 blank lines, found 1

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.3-PYTHON/1126/console

**Comment by pinggao187** [comment]
@Litchilitchy [#3541](https://github.com/intel-analytics/analytics-zoo/pull/3541/files)

**Comment by Litchilitchy** [comment]
@pinggao187 fixed.

**Comment by pinggao187** [comment]
pass 
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-3.0-PYTHON/144/
