### ISSUE TITLE
XGBoost fit_eval use mean validation result instead of final validation result

### ISSUE THREAD

**Issue by PeterQiu0516** [intel-analytics/analytics-zoo#3720]
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/automl/xgboost/XGBoost.py#L134

The `fit_eval` function here return the mean validation result across all iterations instead of the validation result for the final iteration.

**Comment by jason-dai** [comment]
> https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/automl/xgboost/XGBoost.py#L134
> 
> The `fit_eval` function here return the mean validation result across all iterations instead of the validation result for the final iteration.

Maybe you can submit a PR
