### ISSUE TITLE
Extract class names and accuracy for object detection problems (Messi)

### ISSUE THREAD

**Issue by beta21s** [intel-analytics/analytics-zoo#3724]
Hi everybody,

For object detection problem, can I get the exact class and team names?

With the example articles (Messi), I can only get the image with the accuracy and class name on the photo

Anyone who has done it can help me?

Thank you very much!
Have a nice day

```
preprocess = ChainedPreprocessing([ImageResize(300, 300), ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor(), ImageSetToSample()])
postprocess = ScaleDetection()

label_map = {
    0: '__background__', 
    1: 'SDH',
    2: 'EDH',
    3: 'SAH',
    4: 'ICH'
}
config = ImageConfigure(preprocess, postprocess, 2, label_map)

image_set = ImageSet.read('/home/at/Desktop/xhn/images/4-I160_4.png', sc)
output = model.predict_image_set(image_set, config)

visualizer = Visualizer(config.label_map(), encoding="png")
visualized = visualizer(output).get_image(to_chw=False).collect()
#
# only get_image I don't know how to get the class name and accuracy
#
for img_id in range(len(visualized)):
    cv2.imwrite('zzzz.png', visualized[img_id])
```

**Comment by yangw1234** [comment]
Hi @dding3 , would you mind helping answer this question?

**Comment by dding3** [comment]
For object detection, I think get the image with the possibility and class name on the photo is expected behavior. For messi example article, the model is used to detect messi in the image. 

Could you please clarify your problem, are you trying to use object detection model to detect team names? But got image without class name and possibility.

**Comment by beta21s** [comment]
Hi @dding3 For example the resulting messi will be an image file and layer name, accuracy and identifier drawn right on the image.
I need to get the class name, independent accuracy and zone coordinates.

```
# For example the results I want
result = [
'class': messi
'accuracy': 0.97,
'coordinates': [x, y, xx, yy]
]
```
People give me idea

Thank you very much!
Have a nice day

**Comment by dding3** [comment]
Thank you for the clarification. If you don't need the visualization, from above attached code, the prediction results can be extracted from `output = model.predict_image_set(image_set, config)`  by `output.get_predict().collect()', it will return as below:
['img_file', [array['class', 'accuracy', 'x', 'y', 'xx', 'yy']]. eg.
_[('file:000025.jpg', [array([[1.0000000e+01, 8.2894814e-01, 1.4834814e+00, 8.0920006e+01,
        6.9058594e+01, 2.5336589e+02]_. If there are multiple objects, the value will be a list of array.

**Comment by beta21s** [comment]
@dding3 Thank you for your help.
I have run it but I don't understand the numbers taken from the function ```output.get_predict().collect()```
Can you help me explain them?
Can I have a question with the network model retraining problem (Messi - VGGSSD), can I export the network model architecture? (like model.summar () for example) ?
```
[
  ('file:/home/at/Desktop/luanvan/LuanVan/static/dicom/png/14-I250_4.png',
    [array([
      [3.0000000e+00, 1.7633401e-01, 2.5972568e+02, 2.0007755e+02, 3.2536588e+02, 3.0794904e+02],
      [4.0000000e+00, 9.9748468e-01, 2.6209155e+02, 2.0240680e+02, 3.2670062e+02, 3.0747583e+02
      ]
    ], dtype = float32)])
]
```

Thank you very much!
Have a nice day

**Comment by dding3** [comment]
The numbers of `output.get_predict().collect()` will be the numbers of images that are predicted. For how to export the model architecutre, could you share us how did you create the model?

**Comment by beta21s** [comment]
> The numbers of `output.get_predict().collect()` will be the numbers of images that are predicted. For how to export the model architecutre, could you share us how did you create the model?

**Comment by beta21s** [comment]
> The numbers of `output.get_predict().collect()` will be the numbers of images that are predicted. For how to export the model architecutre, could you share us how did you create the model?

@dding3 Hello,
I do not actively build the model but reuse the model from the example (```SSD 300x300 MobileNet```). Can you suggest to me how to export the model architecture? 
[https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ProgrammingGuide/object-detection.md](https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ProgrammingGuide/object-detection.md)

**Comment by dding3** [comment]
You may want to refer https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/ssd/SSDGraph.scala#L56 and https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/ssd/SSD.scala#L78 to see the model architecture.

**Comment by beta21s** [comment]
@dding3 Thank you very much!
Have a nice day
