### ISSUE TITLE
Files in the root directory

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#3733]
- pom.xml
- make-dist.sh
- pyproject.toml

Why are they in the root directory?

**Comment by Le-Zheng** [comment]
Initially, it might be intended to manage several modules. Actually, only `/zoo`  programs require maven. Shall we move "pom.xml" and "make-dist.sh" under `/zoo`? The released artifacts will also be changed.

**Comment by jason-dai** [comment]
> Initially, it might be intended to manage several modules. Actually, only `/zoo` programs require maven. Shall we move "pom.xml" and "make-dist.sh" under `/zoo`? The released artifacts will also be changed.

Yes, let's move these under `/zoo`

**Comment by helenlly** [comment]
tested and confirmed , pyproject.toml is required to be in root when building readthedocs.   
checked other projects using readthedocs, e.g.  pytorch-lightning ...  pyproject.toml is in their root too.

**Comment by Le-Zheng** [comment]
Fixed in https://github.com/intel-analytics/analytics-zoo/pull/3736
