### ISSUE TITLE
Occlum Trusted Cluster Serving Check Status

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#3746]
Pls add Status Check scripts for occlum @ColossusChang

**Comment by ColossusChang** [comment]
Addressed in [PR#3753 ](https://github.com/intel-analytics/analytics-zoo/pull/3753) for local-cluster-serving.

**Comment by qiyuangong** [comment]
Fixed by @ColossusChang :)
Issue closed
