### ISSUE TITLE
AutoEstimator

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#3757]
- [x] `orca.automl.AutoEstimator`
- [x] Zouwu/AutoTS using `AutoEstimator`
- [x] AutoXGBoost using `AutoEstimator`
- [x] Examples for 3rd-party model tuning

**Comment by yushan111** [comment]
`orca.automl.AutoEstimator` is in PR #3731

**Comment by yushan111** [comment]
`AutoXGBoost`using `AutoEstimator` is added in PR #3877

**Comment by yushan111** [comment]
A pytorch example for 3rd-party model tuning is added in PR #3834
