### ISSUE TITLE
[PPML] Spark & Flink example, scripts & Doc Update

### ISSUE THREAD

**Issue by ColossusChang** [intel-analytics/analytics-zoo#3762]
Need to separate Spark and Flink from existing scripts, and verify with examples. The docs should be updated accordingly.

**Comment by qiyuangong** [comment]
Pls add sub-tasks for this issue, e.g.,

- [ ] Flink start/stop script for Graphene
- [ ] Flink example for Graphene

...

**Comment by ColossusChang** [comment]
- [ ] Spark start/stop script for Graphene
- [ ] Spark example for Graphene
- [ ] Flink start/stop script for Graphene
- [ ] Flink example for Graphene
- [ ] Flink start/stop script for Occlum
- [ ] Flink example for Occlum
- [ ] Document fix

**Comment by ColossusChang** [comment]
Addressed in PR#3814, PR#3806, and PR#3778.
