### ISSUE TITLE
Use cluster-serving Multiple Serving get error,InputQueue, OutputQueue API have no 'name' arguments

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3770]
Use cluster-serving Multiple-Serving get error,InputQueue, OutputQueue API have no 'name' arguments
analytics-zoo-serving version :

> analytics_zoo_serving-0.10.0.dev0-20210408-py2.py3-none-any.whl
> analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-20210407.201607-75-serving.jar

**Comment by qiyuangong** [comment]
@glorysdj Pls take a look.

**Comment by Litchilitchy** [comment]
fixed at #3775 , please try again
