### ISSUE TITLE
Use cluster-serving-start ,when set redis port not 6379,the cluster-serving-start shell "${REDIS_HOME}/src/redis-cli " can not execute successfully

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3771]

**Comment by mamba-8-24** [comment]
analytics-zoo-serving version :

> analytics_zoo_serving-0.10.0.dev0-20210408-py2.py3-none-any.whl
> analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-20210407.201607-75-serving.ja

set redis.conf port not 6379 ,when use cluster-serving-start get error:

> Could not connect to Redis at 127.0.0.1:6379: Connection refused
> setting redis stop-writes-on-bgsave-error no:
> Could not connect to Redis at 127.0.0.1:6379: Connection refused
> setting redis save "":
> Could not connect to Redis at 127.0.0.1:6379: Connection refused
> setting redis maxmemory 4g:
> Could not connect to Redis at 127.0.0.1:6379: Connection refused
> setting redis protected-mode no:
> Could not connect to Redis at 127.0.0.1:6379: Connection refused
> setting redis maxclients 10000:

and the reason is in cluster-serving-start shell ，the code bellow can not execute successfully：

> else
>     echo "Trying to start Redis server with default parameter"
>     ${REDIS_HOME}/src/redis-server ${REDIS_HOME}/redis.conf &
>     sleep 1
> 
>     # sleep for 1 sec to ensure server is ready and client could connect
>     echo "setting redis stop-writes-on-bgsave-error no: "`${REDIS_HOME}/src/redis-cli config set stop-writes-on-bgsave-error no`
>     echo "setting redis save \"\": "`${REDIS_HOME}/src/redis-cli config set save ""`
>     echo "setting redis maxmemory 4g: "`${REDIS_HOME}/src/redis-cli config set maxmemory 4g`
>     # bind can not be set after redis starts
>     # /opt/work/redis-5.0.5/src/redis-cli config set bind "0.0.0.0"
>     echo "setting redis protected-mode no: "`${REDIS_HOME}/src/redis-cli config set protected-mode no`
>     echo "setting redis maxclients 10000: "`${REDIS_HOME}/src/redis-cli config set maxclients 10000`
>     echo "To set specific parameter, use \"\$REDIS_HOME/src/redis-cli config set key value\" later."
> fi

**Comment by qiyuangong** [comment]
Nice issue and troubleshooting! :)

So, it is related to Graphene based cluster serving?

**Comment by glorysdj** [comment]
do you mean redis is not started on 6379, but you call redis-cli to try to connect to 6379?

**Comment by Litchilitchy** [comment]
fixed in #3795 , we would not overwrite config for user and will add recommended settings in doc
