### ISSUE TITLE
when use cluster-serving，the flink taskManager logs have no throughput information

### ISSUE THREAD

**Issue by mamba-8-24** [intel-analytics/analytics-zoo#3773]
analytics-zoo-serving version :

> analytics_zoo_serving-0.10.0.dev0-20210408-py2.py3-none-any.whl
> analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-20210407.201607-75-serving.jar

when use cluster-serving，the flink taskManager logs have no throughput information，where can I view details？

**Comment by qinkaixin365** [comment]
吞吐量查看就是通过flink UI 查看的，flink UI 上 taskManager – > logs 里面没有吞吐量信息

不知道新版本为啥取消了，最新版本还是要在flink UI 上 taskManager – > logs 里面显示吞吐量信息，这样才更加直观，图标上显示都是0，没有参考价值

**Comment by Litchilitchy** [comment]
will add in info, and set more important log to WARNING

**Comment by Litchilitchy** [comment]
fixed in #3795
