### ISSUE TITLE
Running spark standalone mode in AZ with random master node yields "/bin/sh: 1: ray: not found"

### ISSUE THREAD

**Issue by Yifanzhou-0713** [intel-analytics/analytics-zoo#3813]
Start to launch ray on cluster
Traceback (most recent call last):                                              
  File "fashion_mnist.py", line 175, in <module>
    main()
  File "fashion_mnist.py", line 161, in main
    backend="torch_distributed")
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/estimator.py", line 92, in from_torch
    backend=backend)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/estimator.py", line 137, in __init__
    workers_per_node=workers_per_node)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 107, in __init__
    ray_ctx = RayContext.get()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 390, in get
    ray_ctx.init()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 473, in init
    redis_address = self._start_cluster()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 502, in _start_cluster
    verbose=self.verbose)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/ray/process.py", line 113, in __init__
    self.print_ray_remote_err_out()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/ray/process.py", line 117, in print_ray_remote_err_out
    raise Exception(str(self.master))
Exception: node_ip: 192.168.65.130 tag: ray-master, pgid: 3180, pids: [], returncode: 127,                 master_addr: 192.168.65.130:32350,  
  /bin/sh: 1: ray: not found
Stopping orca context
stopping org.apache.spark.deploy.worker.Worker
stopping org.apache.spark.deploy.master.Master

**Comment by hkvision** [comment]
Hi @Yifanzhou-0713 

Seems that there's error initializing Ray.
Have you installed ray on every node in your cluster? You can do this by `pip install analytics-zoo[ray]`.
You can type `ray --help` in your command line for verification.
Feel free to tell us if you encounter further problems.

**Comment by Yifanzhou-0713** [comment]
> Hi @Yifanzhou-0713
> 
> Seems that there's error initializing Ray.
> Have you installed ray on every node in your cluster? You can do this by `pip install analytics-zoo[ray]`.
> You can type `ray --help` in your command line for verification.
> Feel free to tell us if you encounter further problems.



> Hi @Yifanzhou-0713
> 
> Seems that there's error initializing Ray.
> Have you installed ray on every node in your cluster? You can do this by `pip install analytics-zoo[ray]`.
> You can type `ray --help` in your command line for verification.
> Feel free to tell us if you encounter further problems.

Thanks for your answer! Here I didn't set the master address of my Spark standalone cluster in AZ. As the source code(zoo/util/spark.py) shows, if do not set the master address, it'll start a master node at a random port and all the master and the worker nodes are in the same ip.  The environment under this ip is already OK and I can run spark "local" with AZ successfully. I'm just confused about this situation: I think the ray is ok in my cluster created by AZ's function named "init_spark_standalone()", but it goes wrong.

**Comment by hkvision** [comment]
If you don't specify the master address, then we would create a standalone cluster for you on the single node.
So you can run your application using spark local, but you get the error after changing to init_spark_standalone right?
Are you running this example: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py?
If so, could you paste your updated code for init_spark_standalone so that we can try to reproduce it.

**Comment by Yifanzhou-0713** [comment]
> If you don't specify the master address, then we would create a standalone cluster for you on the single node.
> So you can run your application using spark local, but you get the error after changing to init_spark_standalone right?
> Are you running this example: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py?
> If so, could you paste your updated code for init_spark_standalone so that we can try to reproduce it.

Yep！
I just add a statement in line 114 in fashion_mnist.py:
        elif args.cluster_mode == "standalone":
    	init_orca_context(cluster_mode=args.cluster_mode, cores=1,memory='1g', num_nodes=2, driver_cores=2, driver_memory="1g")

The version of some packages:
analytics-zoo             0.10.0.dev0
pyspark                      2.4.3
python                       3.7.10
ray                              0.8.4
redis                           3.5.3
torch                          1.8.0
torchvision                 0.9.0
py4j                            0.10.7

Thanks very much!

**Comment by hkvision** [comment]
OK.
Want to further make sure:
- Your analytics-zoo version is 0.10.0.dev0, how did you install this version? https://pypi.org/project/analytics-zoo/#history Seems this version is only a test version and not available now.
- Since we have recently updated this example: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py, want to make sure are you using the code of the latest master or an older version.
Thanks. Hopefully we would reproduce the error very soon with the above information and reach back to you.

**Comment by Yifanzhou-0713** [comment]
> OK.
> Want to further make sure:
> 
> * Your analytics-zoo version is 0.10.0.dev0, how did you install this version? https://pypi.org/project/analytics-zoo/#history Seems this version is only a test version and not available now.
> * Since we have recently updated this example: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py, want to make sure are you using the code of the latest master or an older version.
>   Thanks. Hopefully we would reproduce the error very soon with the above information and reach back to you.

Maybe the version matters.
* I installed 0.10.0.dev0 version about a month(or less than) ago  from https://sourceforge.net/projects/analytics-zoo/files/zoo-py/  Because I tried to run fashion_mnist.py after `pip install analytics-zoo[ray]`(this version is 0.9.0 at that time) but error came out. Then I upgraded it through https://analytics-zoo.github.io/master/#PythonUserGuide/install/#install-from-pip-for-local-usage, to download the wheel. Then I can successfully run local. May I upgrade the version to the lastest one? 
* I'm so sorry that I used the code of an older version. I git the files before April.

**Comment by hkvision** [comment]
So to make everything align, could you upgrade analytics-zoo to the latest version: https://pypi.org/project/analytics-zoo/0.10.0b20210419/
and use the latest code in the master: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py, specify --backend torch_distributed when running the example.

We would use the latest version to reproduce for you. We will reach back to you very soon. Thanks for your patience.

**Comment by Yifanzhou-0713** [comment]
> So to make everything align, could you upgrade analytics-zoo to the latest version: https://pypi.org/project/analytics-zoo/0.10.0b20210419/
> and use the latest code in the master: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py, specify --backend torch_distributed when running the example.
> 
> We would use the latest version to reproduce for you. We will reach back to you very soon. Thanks for your patience.

What a pity that the same error came out after I run the latest fashion_mnist.py with the` 0.10.0b20210419  analytics-zoo` and `1.2.0 ray` by `python fashion_mnist.py --cluster_mode standalone --backend torch_distributed`. Meanwhile the local mode is ok.
Thanks for your patience！

**Comment by hkvision** [comment]
Hi @Yifanzhou-0713 

Thank you for your patience. I run this example on my local machine and it works. Doubt if there's anything wrong with your installation of ray. For Spark local, we just use `ray.init()` to launch a local ray cluster while for Spark standalone, we use ray commands to launch a ray cluster (even on a single node).

Several approaches for you to verify:
1. Check your python:
```
from zoo.util.utils import detect_python_location
detect_python_location()
```
2. Check your ray installation. Run the following command in the command line:
```
/home/kai/anaconda2/envs/py37/bin/python /home/kai/anaconda2/envs/py37/bin/ray start --head --include-dashboard true --dashboard-host 0.0.0.0 --port 35413 --redis-password 123456 --num-cpus 1
/home/kai/anaconda2/envs/py37/bin/python /home/kai/anaconda2/envs/py37/bin/ray start --address ip:35413 --redis-password 123456 --num-cpus 1
```
Note that you need to replace the above python and ray path to your own, and change the ip in address accordingly.

Or try to activate your conda environment and simply run:
```
ray start --head --include-dashboard true --dashboard-host 0.0.0.0 --port 35413 --redis-password 123456 --num-cpus 1
```

Tell us your results and we can further look into it.
Thanks so much!

**Comment by Yifanzhou-0713** [comment]
Hi @hkvision 
Sorry for taking so long to reply.
I try the command with my own address:
```
/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start --head --include-dashboard true --dashboard-host 192.168.65.130 --port 35413 --redis-password 0 --num-cpus 1

```
The ray works and then I try the following command:
```
/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start --address ip:35413 --redis-password 0 --num-cpus 1
```
Some error came out :
Traceback (most recent call last):
  File "/home/yifan/anaconda3/envs/zoo/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/scripts/scripts.py", line 457, in start
    redis_address_port) = services.validate_redis_address(address)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/_private/services.py", line 337, in validate_redis_address
    redis_address = address_to_ip(address)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/_private/services.py", line 369, in address_to_ip
    ip_address = socket.gethostbyname(address_parts[0])
socket.gaierror: [Errno -3] Temporary failure in name resolution

I check the file `/etc/hosts` my ip is correct, and I'm still doubt whether we should run this command:
```
ray start --address='192.168.65.130:35413' --redis-password='0'
```

However, run the last command in my conda environment:
```
ray start --head --include-dashboard true --dashboard-host 192.168.65.130 --port 35413 --redis-password 0 --num-cpus 1
``` 
The ray works well.
These are all I obtained, looking forward to your reply!

**Comment by hkvision** [comment]
`ray start --head` creates a head node for ray and the other `ray start` can create raylet(s) to form a ray cluster.
So after running `/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start --head --include-dashboard true --dashboard-host 192.168.65.130 --port 35413 --redis-password 0 --num-cpus 1`
in the console, ray should print out the ip and port that you can connect to, do you see it and does it equal to your actual ip?

**Comment by Yifanzhou-0713** [comment]
> `ray start --head` creates a head node for ray and the other `ray start` can create raylet(s) to form a ray cluster.
> So after running `/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start --head --include-dashboard true --dashboard-host 192.168.65.130 --port 35413 --redis-password 0 --num-cpus 1`
> in the console, ray should print out the ip and port that you can connect to, do you see it and does it equal to your actual ip?

Sorry that I didn't check my email last night!
After starting the head of ray, in the console, ray did print out the ip and port , and the information is equal to my own ip just as followings:
```
Local node IP: 192.168.65.130
2021-04-22 09:53:51,703	INFO services.py:1174 -- View the Ray dashboard at http://192.168.65.130:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.65.130:35413' --redis-password='0'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='0')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```

**Comment by hkvision** [comment]
So as instructed by ray in the console, you run `ray start --address='192.168.65.130:35413' --redis-password='0'` and would get the error?

**Comment by Yifanzhou-0713** [comment]
> So as instructed by ray in the console, you run `ray start --address='192.168.65.130:35413' --redis-password='0'` and would get the error?

No, I run `ray start --address='192.168.65.130:35413' --redis-password='0'` there is no error. But if I run `ray start --address ip:35413 --redis-password 0 --num-cpus 1` there will be error as below:
```
Traceback (most recent call last):
  File "/home/yifan/anaconda3/envs/zoo/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/scripts/scripts.py", line 457, in start
    redis_address_port) = services.validate_redis_address(address)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/_private/services.py", line 337, in validate_redis_address
    redis_address = address_to_ip(address)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/_private/services.py", line 369, in address_to_ip
    ip_address = socket.gethostbyname(address_parts[0])
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by hkvision** [comment]
have you changed the `ip` in the command to your actual ip?

**Comment by hkvision** [comment]
So I suppose you can start ray as expected... Then "/bin/sh: 1: ray: not found" is strange...

**Comment by Yifanzhou-0713** [comment]
> So I suppose you can start ray as expected... Then "/bin/sh: 1: ray: not found" is strange...

I'm sure the `ip` is correct, I check  `ray start --help` and can not find the argument `address ip` as the command contains. Anyway, I'm afraid I can start ray... :-(
Thanks for your patience!

**Comment by hkvision** [comment]
I mean in `ray start --address ip:35413 --redis-password 0 --num-cpus 1` you need to change ip to your actual ip, the argument is address not address ip...

So ray should be ok in your environment, not sure why you get `/bin/sh: 1: ray: not found` when launching the ray cluster.
We use Python processes to launch the ray cluster: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L186

**Comment by Yifanzhou-0713** [comment]
> I mean in `ray start --address ip:35413 --redis-password 0 --num-cpus 1` you need to change ip to your actual ip, the argument is address not address ip...
> 
> So ray should be ok in your environment, not sure why you get `/bin/sh: 1: ray: not found` when launching the ray cluster.
> We use Python processes to launch the ray cluster: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L186

Well, I follow the logs of the error , I'm afraid it even didn't call the function `_get_raylet_command()`, and the location for error seems to show that `self.master.errorcode == 1` in flie:  https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/process.py#L117 but I don't know the exact reason.  And I still doubt  whether `1: ray:`  is regarded as the command instead of the correct `ray`, it's a quite strange error.
Sorry for disturbing so long.

**Comment by hkvision** [comment]
No worries. The issue is strange, we would try our best to help you fix this.

Exception: node_ip: 192.168.65.130 tag: ray-master, pgid: 3180, pids: [], returncode: 127, master_addr: 192.168.65.130:32350,
/bin/sh: 1: ray: not found
From your error stack, this is the info of the process to launch the ray master, command is here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L165.

Can you find the print message here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L196 from the spark executor log (should be in stderr, you can find this in the webui, should be your ip:8080). We can check if the command to launch the ray master is expected.

**Comment by Yifanzhou-0713** [comment]
> No worries. The issue is strange, we would try our best to help you fix this.
> 
> Exception: node_ip: 192.168.65.130 tag: ray-master, pgid: 3180, pids: [], returncode: 127, master_addr: 192.168.65.130:32350,
> /bin/sh: 1: ray: not found
> From your error stack, this is the info of the process to launch the ray master, command is here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L165.
> 
> Can you find the print message here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L196 from the spark executor log (should be in stderr, you can find this in the webui, should be your ip:8080). We can check if the command to launch the ray master is expected.

Sorry for taking so long to reply! I'm busy with something else before ┭┮﹏┭┮
I check the stderr in my master webui, the message generated by  https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L196 is printed as following:
`Starting raylet by running: ray start --address 192.168.65.130:37657 --redis-password 123456 --num-cpus 1 --resources '{"_mxnet_worker": 1, "_mxnet_server": 1, "_reserved": 2}'`
Does it mean the master is launched as expected ? However, then the error `/bin/sh: 1: ray: not found` comes out.
Thanks for your patience!

**Comment by Yifanzhou-0713** [comment]
Well, maybe I check the wrong stderr ┭┮﹏┭┮,
I will check again!

**Comment by Yifanzhou-0713** [comment]
emmm, I find the message as below, seems correct?
`Starting ray-master by running: ray start --head --include-dashboard true --dashboard-host 0.0.0.0 --port 41994 --redis-password 123456 --num-cpus 1 --resources '{"_mxnet_worker": 1, "_mxnet_server": 1, "_reserved": 2}'`

**Comment by hkvision** [comment]
Hi @Yifanzhou-0713 

Sorry for the late reply... I just saw this...

The command is correct, it seems somehow when launching this process, `ray` is not found... May need some debug to find out what is exactly going wrong...
Here to generate the ray start command:
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L203
Since you are using a conda environment, it should go to the if branch and use the absolute path to start ray, i.e. `/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start`, but actually it goes into the else branch to use `ray` directly.
Can you print out `self.python_loc` to take a look? It should be `sys.executable` and should be your conda environment.
Thanks. Tell me your result and I can further look into it.

**Comment by Yifanzhou-0713** [comment]
> Hi @Yifanzhou-0713
> 
> Sorry for the late reply... I just saw this...
> 
> The command is correct, it seems somehow when launching this process, `ray` is not found... May need some debug to find out what is exactly going wrong...
> Here to generate the ray start command:
> https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L203
> Since you are using a conda environment, it should go to the if branch and use the absolute path to start ray, i.e. `/home/yifan/anaconda3/envs/zoo/bin/python /home/yifan/anaconda3/envs/zoo/bin/ray start`, but actually it goes into the else branch to use `ray` directly.
> Can you print out `self.python_loc` to take a look? It should be `sys.executable` and should be your conda environment.
> Thanks. Tell me your result and I can further look into it.

Thanks for your reply！
I add `print("self.python_loc")` before the if branch and the message shows it doesn't go to the right env, it prints ` /home/yifan/anaconda3/bin/python
`  and doesn't go to the if branch, however, the code is running in zoo environment.  So I think we find the problem! And how can I solve it?

**Comment by hkvision** [comment]
It is strange that the actual python detected is not the conda environment you are using, but the default conda environment...

As a workaround, you can specify `python_location="/home/yifan/anaconda3/envs/zoo/bin/python"` when `init_orca_context` to have a try.

**Comment by Yifanzhou-0713** [comment]
> It is strange that the actual python detected is not the actual conda environment you are using, but the default conda environment...
> 
> As a workaround, you can specify `python_location="/home/yifan/anaconda3/envs/zoo/bin/python"` when `init_orca_context` to have a try.

It's strange that the `python_location` in `init_orca_context` is correct, I specify but there is no use, the python location in raycontext is still the default anaconda environment. I can only specify the env python location directly in `raycontext.py` , then the error disappear. 
Thanks for your patience and long time answering!
btw, I download the fashion_mnist dataset before in the correct path, but it shows `RuntimeError: Dataset not found. You can use download=True to download it
` when running standalone, but I run local it can run well.  I'm puzzled again 😂

**Comment by hkvision** [comment]
This should be the error reported by torchvision: https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L89
See here: https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L89
the folder structure should be `root/FashionMNIST/processed/training.pt&test.pt`. You need to check your input path with torchvision's requirement. Actually this is a usage issue of torchvision.

**Comment by Yifanzhou-0713** [comment]
> This should be the error reported by torchvision: https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L89
> See here: https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L89
> the folder structure should be `root/FashionMNIST/processed/training.pt&test.pt`. You need to check your input path with torchvision's requirement. Actually this is a usage issue of torchvision.

Thanks!
emmm, I mean the path is correct, when I run local it can run well. 
Now I delete the dataset and choose to set the download=True for standalone, it comes the error after the dataset is downloaded. (a little bit long)
```
(pid=4089) Extracting ./data/FashionMNIST/raw/train-images-idx3-ubyte.gz to ./data/FashionMNIST/raw
Traceback (most recent call last):
  File "fashion_mnist_new.py", line 192, in <module>
    main()
  File "fashion_mnist_new.py", line 176, in main
    stats = orca_estimator.fit(train_data_creator, epochs=epochs, batch_size=batch_size)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/estimator.py", line 177, in fit
    label_cols=label_cols)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 229, in train
    info=info)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 261, in _train_epochs
    success = check_for_failure(remote_worker_stats)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 49, in check_for_failure
    finished = ray.get(finished)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ConnectionError): ray::TorchRunner.train_epochs() (pid=4126, ip=192.168.65.130)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

ray::TorchRunner.train_epochs() (pid=4126, ip=192.168.65.130)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7effcdf9a510>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

ray::TorchRunner.train_epochs() (pid=4126, ip=192.168.65.130)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='fashion-mnist.s3-website.eu-central-1.amazonaws.com', port=80): Max retries exceeded with url: /train-labels-idx1-ubyte.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effcdf9a510>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

ray::TorchRunner.train_epochs() (pid=4126, ip=192.168.65.130)
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/zoo/orca/learn/pytorch/torch_runner.py", line 259, in train_epochs
    loader = data_creator(config, batch_size)
  File "fashion_mnist_new.py", line 49, in train_data_creator
    transform=transform)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 146, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 314, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 122, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 74, in _get_redirect_url
    response = requests.get(url)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yifan/anaconda3/envs/zoo/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='fashion-mnist.s3-website.eu-central-1.amazonaws.com', port=80): Max retries exceeded with url: /train-labels-idx1-ubyte.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effcdf9a510>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Seems  connection refused between urls, but the dataset is already downloaded... and local mode runs successfully........
Thanks for your patience! I'll try to  check it

**Comment by hkvision** [comment]
The connection error should be due to the network for downloading the dataset?

**Comment by hkvision** [comment]
For the python_location issue, it is strange, could you please take a further check to see if any bug exists in our code?
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L371 Here is the python_loc the zoo conda environment? 
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L204 Is the python_loc here correct?
Theatrically, they should be all the same... It is really strange that they are different in your case...
Thanks so much!
