### ISSUE TITLE
when the cluster-serving inference the saved-model, the value of throughput is very small.

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3843]
when the cluster-serving inference the saved-model, the value of throughput is very small. 
4 records backend time 173.343174514 s. Throughput 0.023075612934946806. The saved model is my segmentation model.

**Comment by Litchilitchy** [comment]
1. what is the inference time?
2. is this the first batch?

**Comment by gtfaiwxm** [comment]
Hi @Litchilitchy I will post the log here. This isn't the first batch.

**Comment by gtfaiwxm** [comment]
Hi @Litchilitchy ,The throughput normal now using the cluster-serving of new version. Thanks
