### ISSUE TITLE
jenkins: UT on mac sometimes aborts

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3846]
Running zouwu tests
../test/zoo/zouwu/regression/test_time_sequence_predictor.py::TestTimeSequencePredictor::test_fit_BayesRecipe PASSED [ 97%]
../test/zoo/zouwu/regression/test_time_sequence_predictor.py::TestTimeSequencePredictor::test_fit_LSTMGridRandomRecipe pyzoo/dev/run-pytests-ray: line 52: 90260 Abort trap: 6           python -m pytest -v ../test/zoo/zouwu -k "not test_forecast_tcmf_distributed"

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/317/
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/315/
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/297/

**Comment by glorysdj** [comment]
@qiyuangong mentioned this may be caused by mac resource limitation. please check the related log on mac.

**Comment by pinggao187** [comment]
fixed
