### ISSUE TITLE
Reading parquet dataset as tf.data.Dataset

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#3911]
## API:
```python
orca.data.image.read_parquet(format='tf_dataset', input_path=..., *args, **kwargs)
```

## Example Usage in TF2 Estimator:
```python
def data_creator(config, batch_size):
    dataset = orca.data.image.read_parquet(format='tf_dataset', input_path=config["input_path"], *args, **kwargs)
    dataset = dataset.shuffle(config["shuffle_buffer_size"])
    dataset = dataset.map(lambda data_dict: (data_dict["image"], data_dict["label"]))
    dataset = dataset.map(classification_preprocessing_func)
    dataset = dataset.batch(batch_size)
    return dataset

estimator.fit(data_creator)
```
## Possible Implemetation

1. iterator through each parquet file and read it using pyarrow as pa.Table
2. pa.Table.to_pandas() to convert the data to pandas.Dataframe
3. dataframe.to_dict("records") to split the dataframe into each record as a dict
4. yield each record
5. pass the generator to tf.data.Dataset.from_generator

## Potential Issues
Currently in TF2 Estimator we will automatically shard the dataset based on each node's rank. If a tf.data.Dataset is constructed from a generator, the sharding is based on records not the underling files. This may have a performance issue.

**Comment by yangw1234** [comment]
fixed by #3956

**Comment by jason-dai** [comment]
Add `config` to the API: `orca.data.image.read_parquet(format='tf_dataset', input_path=..., config={}, *args, **kwargs)`?

**Comment by yangw1234** [comment]
@jason-dai I'll open anther issue.
