### ISSUE TITLE
jenkins : UT failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3924]
Running other tests

______ ERROR collecting test/zoo/orca/automl/xgboost/test_xgbregressor.py ______
../test/zoo/orca/automl/xgboost/test_xgbregressor.py:24: in <module>
    from zoo.orca.automl.xgboost.XGBoost import XGBoost
../zoo/orca/automl/xgboost/XGBoost.py:18: in <module>
    from xgboost.sklearn import XGBRegressor
/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/xgboost/__init__.py:11: in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/xgboost/core.py:175: in <module>
    _LIB = _load_lib()
/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/xgboost/core.py:166: in _load_lib
    'Error message(s): {}\n'.format(os_error_list))
E   xgboost.core.XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
E   Likely causes:
E     * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
E     * You are running 32-bit Python on a 64-bit OS
E   Error message(s): ['dlopen(/Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/arda/anaconda3/envs/py36/lib/python3.6/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']

Jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.1-PYTHON-MAC/286/console

**Comment by yushan111** [comment]
According to the hint, we may need to install OpenMP runtime on mac
```bash
brew install libomp

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.1-PYTHON-MAC/288/console
