### ISSUE TITLE
jenkins: random failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3933]
Running zouwu tests

________________ TestZouwuModelAnomaly.test_threshold_gaussian _________________

self = <test_model_anomaly.TestZouwuModelAnomaly testMethod=test_threshold_gaussian>

    def test_threshold_gaussian(self):
        sample_num = 500
        # actual value
        y_test = np.full(sample_num, 2)
        mu, sigma, ratio = 3, 0.1, 0.01
        s = np.random.normal(mu, sigma, sample_num)
        y = y_test + s
    
        threshold = ThresholdEstimator().fit(y, y_test, mode="gaussian", ratio=ratio)
        from scipy.stats import norm
>       assert abs(threshold-(norm.ppf(1-ratio)*sigma+mu)) < 0.02
E       AssertionError: assert 0.025225962559095816 < 0.02
E        +  where 0.025225962559095816 = abs((3.2074088248449883 - ((2.3263478740408408 * 0.1) + 3)))
E        +    where 2.3263478740408408 = <bound method rv_continuous.ppf of <scipy.stats._continuous_distns.norm_gen object at 0x7f8c2205e518>>((1 - 0.01))
E        +      where <bound method rv_continuous.ppf of <scipy.stats._continuous_distns.norm_gen object at 0x7f8c2205e518>> = <scipy.stats._continuous_distns.norm_gen object at 0x7f8c2205e518>.ppf

../test/zoo/zouwu/model/anomaly/test_model_anomaly.py:131: AssertionError

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/336/console

**Comment by TheaperDeng** [comment]
I will check this ut. It might be caused by an unnecessarily strict threshold. Please re-run for now.

**Comment by pinggao187** [comment]
rerun
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/337/
