### ISSUE TITLE
submit-examples-on-k8s: python examples missing python file

### ISSUE THREAD

**Issue by zzti-bsj** [intel-analytics/analytics-zoo#3958]
## python examples missing python file
[https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/submit-examples-on-k8s.md](https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/submit-examples-on-k8s.md)

The following two examples are missing python files:
* attention
```python
no such file or directory: /opt/analytics-zoo-examples/python/attention/transformer.py
```
* pytorch
```python
no such file or directory: /opt/analytics-zoo-examples/python/pytorch/inference/predict.py
```

**Comment by zzti-bsj** [comment]
@glorysdj 
* **attention/transformer.py** was deleted in commit `f477bb`
* **inference/predict.py** was deleted in commit `e92070`

**Comment by glorysdj** [comment]
then we can ignore these two tests
