### ISSUE TITLE
jenkins: UT build failure

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3974]
[ERROR] /private/var/jenkins_home/workspace/ZOO-NB-UnitTests-2.4-SCALA-MAC/zoo/src/main/scala/com/intel/analytics/zoo/serving/http/domains.scala:112: not found: value StreamSerializer
[ERROR]     val bytes = StreamSerializer.objToBytes(instances)

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-SCALA-MAC/405/console

**Comment by pinggao187** [comment]
@Litchilitchy  [#3816](https://github.com/intel-analytics/analytics-zoo/pull/3816)

**Comment by Litchilitchy** [comment]
fixed in #3980

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/job/ZOO-NB-Pip-AppTests-part1/618/console
