### ISSUE TITLE
jenkins: docker image build failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3987]
+ cd ../../docker/hyperzoo
+ sed -i 'N;44a\RUN rm -rf /var/lib/apt/lists/*' Dockerfile
+ docker build --no-cache --build-arg http_proxy=http://proxy-chain.intel.com:911 --build-arg https_proxy=http://proxy-chain.intel.com:912 --build-arg SPARK_VERSION=2.4.3 --build-arg BIGDL_VERSION=0.12.2 --build-arg JDK_VERSION=8u192 --build-arg JDK_URL=http://10.239.45.10:8081/repository/raw/jdk/jdk-8u192-linux-x64.tar.gz --build-arg no_proxy=10.239.45.10 --rm -t intelanalytics/hyper-zoo:latest .
Sending build context to Docker daemon   172 kB

Step 1 : ARG SPARK_VERSION=2.4.3
Please provide a source image with `from` prior to commit

jenkins link:
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Deploy-Docker/800/console

**Comment by pinggao187** [comment]
@zzti-bsj  [#3916](https://github.com/intel-analytics/analytics-zoo/pull/3916)

**Comment by glorysdj** [comment]
please also remove command sed -i 'N;44a\RUN rm -rf /var/lib/apt/lists/*' Dockerfile
please assign this jenkins job to label "publish" which support multi-stage job.

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Deploy-Docker/803/
