### ISSUE TITLE
Some link in Chronos readthedoc user guide is broken

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4007]
https://analytics-zoo.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html

It seems that some links use relative path in source code.

**Comment by shane-huang** [comment]
broken links are fixed except for visualization tool link in https://analytics-zoo.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html#train-autots-pipeline. Will fix in another issue.
