### ISSUE TITLE
Analytics  zoo 0.8.1,how to load a model saved by  torchnet.savePytorch('./alexnet_modelnet40_0.8.1_epoch2.pth')

### ISSUE THREAD

**Issue by anyuecq25** [intel-analytics/analytics-zoo#4015]
My Cluster is based on Spark2.1.1, the newest version of analytics zoo that can be successfully run on my Cluster is 0.8.1. 
Now, I am using Pytorch to train Alexnet on my images. When I finished training, I use torchnet.savePytorch('./alexnet_modelnet40_0.8.1_epoch2.pth') to save the model.
The problem is that, I cannot load the model when I begin another training.
I tried Model.load() and other methods, all fails. 

I wonder which function is right to load the saved python script module by torchnet.savePytorch()?

The code is from /analytics-zoo-0.8.1/pyzoo/zoo/examples/pytorch/train/resnet_finetune/resnet_finetune.py

**Comment by qiuxin2012** [comment]
Could you update your analytics-zoo to 0.10.0, torchnet is deprecated. Please use TorchModel. See https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-quickstart.html for help. And the resnet_finetune.py is updated in 0.10.0.

**Comment by jason-dai** [comment]
pip installs Analytic Zoo for Spark 2.4.3; is there a way to install Analytics Zoo 0.10.0 for Spark 2.1.1 (or other Spark versions)? Does the guide at https://analytics-zoo.github.io/master/#PythonUserGuide/install/#install-without-pip still work? @glorysdj @hkvision

**Comment by anyuecq25** [comment]
> Could you update your analytics-zoo to 0.10.0, torchnet is deprecated. Please use TorchModel. See https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-quickstart.html for help. And the resnet_finetune.py is updated in 0.10.0.

Ok, thank you ,I found the solution from the scala source code. It can be loaded like this.

torchnet=TorchNet('./alexnet_modelnet40_0.8.1_epoch2.pth')

I am also trying analytics-zoo to 0.10.0, it works on local mode. But it is encoutering some problems when running resnet_finetune.py on yarn of my cluster. I am working on it.


cd /home/ubuntu/zoo_py/analytics-zoo-branch-0.10/pyzoo/zoo/examples/pytorch/train/resnet_finetune
export SPARK_MAJOR_VERSION=2
export SPARK_HOME=/usr/hdp/2.6.1.0-129/spark2
export ANALYTICS_ZOO_HOME=/home/ubuntu/zoo_py
export VENV_HOME=/home/ubuntu/zoo_py
export PYSPARK_DRIVER_PYTHON=/home/ubuntu/.conda/envs/zoo3.7/bin/python
export PYSPARK_PYTHON=./environment/bin/python

imagePath=dogs_cats/samples   #hdfs 


${ANALYTICS_ZOO_HOME}/bin/spark-submit-python-with-zoo.sh \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=./environment/bin/python \
    --master yarn \
    --deploy-mode client \
    --driver-memory 16g \
    --executor-memory 32g \
    --executor-cores 16 \
    --num-executors 8 \
    --archives ${VENV_HOME}/zoo3.7.tar.gz#environment \
    --conf spark.files.maxPartitionBytes=1048576 \
    resnet_finetune.py $imagePath



Traceback (most recent call last):
  File "/home/ubuntu/zoo_py/analytics-zoo-branch-0.10/pyzoo/zoo/examples/pytorch/train/resnet_finetune/resnet_finetune.py", line 88, in <module>
    .withColumn("label", getLabel(col('name'))).cache()
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 463, in cache
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o97.cache.
: org.spark_project.guava.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.<init>(Ljava/lang/String;SS)V   3:10 PM 5/29/2021

**Comment by qiuxin2012** [comment]
It seems spark version is conflicted.
You can follow this [README](https://github.com/intel-analytics/analytics-zoo/tree/branch-0.10/pyzoo/zoo/examples/pytorch/train/resnet_finetune) to run resnet_finetune.py
This job is using the pyspark 2.4.3 in conda enviroment, so you should delete all the SPARK related environment variables, like SPARK_HOME.

**Comment by hkvision** [comment]
> pip installs Analytic Zoo for Spark 2.4.3; is there a way to install Analytics Zoo 0.10.0 for Spark 2.1.1 (or other Spark versions)? Does the guide at https://analytics-zoo.github.io/master/#PythonUserGuide/install/#install-without-pip still work? @glorysdj @hkvision

Spark 2.1 may not be a good idea for pip as pyspark becomes stable after 2.2?

**Comment by anyuecq25** [comment]
Thanks for all the reply.
