### ISSUE TITLE
Hyperzoo docker image has numpy with not compatible version

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4086]
As stated in doc, we need numpy to be 1.18.1 https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/python.html#compatibility

The latest numpy might cause issue in automl app notebook.

NotImplementedError: Cannot convert a symbolic Tensor (attention_rnn_wrapper/strided_slice:0) to a numpy array.

**Comment by glorysdj** [comment]
please update dockerfiles in docker/zoo and zoo/hyperzoo with
pip install --no-cache-dir numpy==1.18.1

BTW docker/zoo and update all the pip commands with --no-cache-dir to save space

**Comment by glorysdj** [comment]
assigned to @zzti-bsj

**Comment by zzti-bsj** [comment]
this [pr](https://github.com/intel-analytics/analytics-zoo/pull/4098)  solves the issues of #4086 and #4083
