### ISSUE TITLE
Hyperzoo docker image does not respect users' input NotebookToken/NotebookPort

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4087]
https://github.com/intel-analytics/analytics-zoo/blob/651d025638b6f25a6dd5433b93be115f2fbb7332/docker/hyperzoo/start-notebook-spark.sh#L31

**Comment by TheaperDeng** [comment]
after discussion, we prefer to fix the doc typo in https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/k8s.html

**Comment by glorysdj** [comment]
the user can set NOTEBOOK_PORT and NOTEBOOK_TOKEN  to specify the port and token.
and the doc is wrong, not NotebookPort and NotebookToken
https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/README.md
https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ProgrammingGuide/k8s.md
https://github.com/intel-analytics/analytics-zoo/blob/master/docs/readthedocs/source/doc/UserGuide/k8s.md

and also noticed that these parameters are not unified in docker/zoo and docker/hyperzoo
please also unify them as NOTEBOOK_PORT and NotebookToken in docker/zoo

**Comment by glorysdj** [comment]
assigned to @zzti-bsj

**Comment by zzti-bsj** [comment]
here is pr [link](https://github.com/intel-analytics/analytics-zoo/pull/4097)
