### ISSUE TITLE
jenkins: AIOps_anomaly_detect.ipynb': No such file or directory

### ISSUE THREAD

**Issue by pinggao18** [intel-analytics/analytics-zoo#4106]
#20 start app test for chronos-anomaly-detect
cp: cannot stat '/opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/AIOps/AIOps_anomaly_detect.ipynb': No such file or directory
sed: can't read /opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/AIOps/AIOps_anomaly_detect.tmp.ipynb: No such file or directory
sed: can't read /opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/AIOps/AIOps_anomaly_detect.tmp.ipynb: No such file or directory

Jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-Pip-AppTests-part4/453/console

**Comment by pinggao18** [comment]
@cabuliwallah  pls have a look

**Comment by pinggao18** [comment]
[jupyter notebook demo for anomaly detector #4081](https://github.com/intel-analytics/analytics-zoo/pull/4081)

**Comment by cabuliwallah** [comment]
Fixing. Need to change file names in scripts.

**Comment by pinggao18** [comment]
pass 
http://10.239.176.111:18888/job/ZOO-NB-Pip-AppTests-part4/455/
