### ISSUE TITLE
jenkins: chronos tests timeout 5h

### ISSUE THREAD

**Issue by pinggao18** [intel-analytics/analytics-zoo#4107]
Running chronos tests

../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_global_feature PASSED [ 15%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_imputation PASSED [ 16%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_initialization PASSED [ 17%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_resample PASSED [ 18%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_roll_multi_id PASSED [ 19%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_roll_single_id PASSED [ 19%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_rolling_feature PASSED [ 20%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_scale_unscale PASSED [ 21%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_split PASSED [ 22%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_tsdataset_unscale_numpy Build was aborted

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-3.0-PYTHON-MAC/183/console
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/376/console

**Comment by pinggao187** [comment]
@TheaperDeng  pls have a look

**Comment by TheaperDeng** [comment]
test_tsdataset_unscale_numpy is the largest ut in chronos.data. If mem is enough, it will pass in 20s. If mem runs out, it might take forever. 

If needed, I will shrink the ut to a smaller one. @pinggao187

**Comment by pinggao187** [comment]
yes, need to shrink.

**Comment by TheaperDeng** [comment]
> yes, need to shrink.

sure, I will fix it soon.

**Comment by pinggao18** [comment]
pass
http://10.239.176.111:18888/view/ZOO-NB-Overview/job/ZOO-NB-UnitTests-MAC/368/
