### ISSUE TITLE
Colan notebook failure when running evaluate

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#4123]
`AttributeError: module 'aioredis' has no attribute 'create_redis_pool'` when running `est.evaluate` for

- https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html
- https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-distributed-quickstart.html
- https://analytics-zoo.readthedocs.io/en/latest/doc/UseCase/spark-dataframe.html

**Comment by Le-Zheng** [comment]
fix in https://github.com/intel-analytics/analytics-zoo/pull/4124
Colab installs `aioredis==2.0.0a1` which may not compatible with ray 1.2.0. Downgrade `aioredis` will solve that.

**Comment by Le-Zheng** [comment]
The newly released pre-built Analytics Zoo has fixed this issue.
