### ISSUE TITLE
Chronos: TSPipeline returned by AutoTSTrainer

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4151]
### Why we need a pipeline?

A typical workflow for users who want to use our new AutoTS can be described as following.

1. Deal with their "dirty" data and make it meets TSDataset's minimal requirement (a datetime col and a target col).
2. Use TSDataset to preprocess and generate features / Write their own data creator.
3. Use AutoTSTrainer to find the best built-in model / 3rd party model.

What will they do next? Basically, they have two further development path.

1. Further development on the prototype.

   Users may want to evaluate the prototype, use the prototype to predict or incremental training on the prototype.

2. Deploy the model to their scenario.

   The prototype might be developed on a server which will not be used in production environment. Users may want to export the whole E2E pipeline (data preprocessing, model inference, data postprocessing) to a file and migrate to production environment with a Chronos Docker. Users need offline/batch prediction may use the pipeline itself. Users need online/low latency prediction may want to export onnx model to imbed in their own applications. 

#### basic methods

Users can use the best model without worrying about the preprocessing/postprocessing/feature generation.

All of the methods support tsdata / data creator.

- **evaluate**: evaluate with native/intel opt pytorch/keras. (with/without preprocessing/postprocessing/feature generation)
- **evaluate_with_onnx**: evaluate with onnx. (with/without preprocessing/postprocessing/feature generation)
- **predict**: predict with native/intel opt pytorch/keras. (with/without preprocessing/postprocessing/feature generation)
- **predict_with_onnx**: predict with onnx. (with/without preprocessing/postprocessing/feature generation)
- **fit**: incremental training. (with preprocessing/postprocessing/feature generation)
- **save**: save the whole pipeline.
- **load (static method)**: load the whole pipeline.

#### export methods

Users can export native file for onnx runtime/pytorch/keras to deploy in their applications.

- **export_onnx_file**: export onnx file.
- **export_pytorch_model**: export pytorch model.
- **export_keras_model**: export keras model.

#### information methods

Users can refer to the information to rebuild the preprocessing code/model in their applications.

- **get_processing_information**: return dictionary which states the operations on tsdataset.
- **get_model_information**: return dictionary with best config and model name.

#### chronos.data.TSDataset

- get_operation_history(): return a dictionary represents the ordered operations and parameters that has been carried on it

e.g.  {0: {"impute": {"mode": "last", "const_num": 0}}, 1: {"resample": {"interval": ...}}

- replay_operation(history): replay the ordered operations dictionary. The method should be "smart" and throw error if nothing can be done to replay the orderred operations.

e.g. We have a history with 5 op. If the a tsdataset has carried out op1 and op2, then this method will only carry out op3, op4, op5 continually.

#### chronos.autots.TSPipeline / Just return a revised version of chronos.model.forecast.Forecaster

- I prefer a TSPipeline for parallel development (need discussion)

### Schedule

- [ ] add `chronos.autots.TSPipeline` with no data preprocessing (which means user need to preprocess the data before put it to the pipeline)
- [ ] add api doc
- [ ] [EARLY JULY RELEASE]
- [ ] add `get_operation_history` and `replay_operation` methods for TSDataset
- [ ] add data preprocessing/postprocessing to the pipeline

**Comment by shane-huang** [comment]
Generally LGTM. 

We could support a simple TSPipeline first and then add more functionalities.
