### ISSUE TITLE
Problem with import Estimator from zoo.orca.learn.tf.estimator

### ISSUE THREAD

**Issue by cs201503** [intel-analytics/analytics-zoo#4190]
Hi, 
I am trying out orca, and encountered some problems during the first step:
![image](https://user-images.githubusercontent.com/78426877/124010547-39778280-d9df-11eb-8d04-f48cc2350d24.png)

I am using Python 3.6.13.
Anyone know how I can solve the problem? Please help!
Thank you very much in advance!

**Comment by yangw1234** [comment]
hi @cs201503 thank you for reporting this issue but I was not able to reproduce it on our side. Would you mind sharing more details about your environment,
e.g.
1. what's the version of analytics zoo?
2. what's the version of tensorflow?

**Comment by yushan111** [comment]
@cs201503 
Thanks for your issue.

Your tensorflow version might be 2.x and you could try tensorflow==1.15.0 to use orca tf estimator. And we have orca tf2 estimator for tensorflow2.x. You can import with `from zoo.orca.learn.tf2 import Estimator` and find more details in [tf2 estimator API guide](https://analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/Orca/orca.html#module-zoo.orca.learn.tf2.estimator) and [tf2 estimator quick start](https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html)

**Comment by cs201503** [comment]
> @cs201503
> Thanks for your issue.
> 
> Your tensorflow version might be 2.x and you could try tensorflow==1.15.0 to use orca tf estimator. And we have orca tf2 estimator for tensorflow2.x. You can import with `from zoo.orca.learn.tf2 import Estimator` and find more details in [tf2 estimator API guide](https://analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/Orca/orca.html#module-zoo.orca.learn.tf2.estimator) and [tf2 estimator quick start](https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html)

Hi @yushan111 , thank you very much for your help!
I have created a new environment and installed analytics zoo again according to TF2 instructions (https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html).
I have Python 3.7.0, Tensorflow 2.3.0.
When I am running the 2nd step: init_orca_context(cluster_mode="local", cores=4, memory="2g")
The following error appeared:

`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-c32b2d2e2f54> in <module>
----> 1 init_orca_context(cluster_mode="local", cores=4, memory="2g")

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/zoo/orca/common.py in init_orca_context(cluster_mode, cores, memory, num_nodes, init_ray_on_spark, **kwargs)
    192             spark_args["python_location"] = kwargs["python_location"]
    193         from zoo import init_spark_on_local
--> 194         sc = init_spark_on_local(cores, **spark_args)
    195     elif cluster_mode.startswith("yarn"):  # yarn or yarn-client
    196         if cluster_mode == "yarn-cluster":

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/zoo/common/nncontext.py in init_spark_on_local(cores, conf, python_location, spark_log_level, redirect_spark_log)
     51     set_python_home()
     52     return runner.init_spark_on_local(cores=cores, conf=conf,
---> 53                                       python_location=python_location)
     54 
     55 

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/zoo/util/spark.py in init_spark_on_local(self, cores, conf, python_location)
     55         zoo_conf = init_spark_conf(conf).setMaster(master)
     56         sc = init_nncontext(conf=zoo_conf, spark_log_level=self.spark_log_level,
---> 57                             redirect_spark_log=self.redirect_spark_log)
     58         print("Successfully got a SparkContext")
     59         return sc

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/zoo/common/nncontext.py in init_nncontext(conf, spark_log_level, redirect_spark_log)
    367         sc = getOrCreateSparkContext(conf=None, appName=conf)
    368     else:
--> 369         sc = getOrCreateSparkContext(conf=conf)
    370     sc.setLogLevel(spark_log_level)
    371 

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/zoo/common/nncontext.py in getOrCreateSparkContext(conf, appName)
    408             if appName:
    409                 spark_conf.setAppName(appName)
--> 410             return SparkContext.getOrCreate(spark_conf)
    411         else:
    412             return SparkContext.getOrCreate()

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/pyspark/context.py in getOrCreate(cls, conf)
    365         with SparkContext._lock:
    366             if SparkContext._active_spark_context is None:
--> 367                 SparkContext(conf=conf or SparkConf())
    368             return SparkContext._active_spark_context
    369 

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    131                     " note this option will be removed in Spark 3.0")
    132 
--> 133         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    134         try:
    135             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    314         with SparkContext._lock:
    315             if not SparkContext._gateway:
--> 316                 SparkContext._gateway = gateway or launch_gateway(conf)
    317                 SparkContext._jvm = SparkContext._gateway.jvm
    318 

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/pyspark/java_gateway.py in launch_gateway(conf)
     44     :return: a JVM gateway
     45     """
---> 46     return _launch_gateway(conf)
     47 
     48 

~/anaconda3/envs/zoo2/lib/python3.7/site-packages/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise Exception("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number

`

It has not appeared before. Do you know why that happened?
Thank you!

**Comment by cs201503** [comment]
> hi @cs201503 thank you for reporting this issue but I was not able to reproduce it on our side. Would you mind sharing more details about your environment,
> e.g.
> 
> 1. how did you installed analytics zoo
> 2. what's the version of analytics zoo?
> 3. what's the version of tensorflow?

Hi @yangw1234 ,
@yushan111 the problem has been solved by

**Comment by yangw1234** [comment]
@cs201503 looks like this is a different problem. Would you mind open another issue?

**Comment by yangw1234** [comment]
@cs201503 it seems you did not define the `cluster_mode` variable in your notebook.

**Comment by cs201503** [comment]
> @cs201503 looks like this is a different problem. Would you mind open another issue?

Yes, I opened an other issue and will close this one!
Thank you a lot for your help :)
