### ISSUE TITLE
define cluster_mode in orca

### ISSUE THREAD

**Issue by cs201503** [intel-analytics/analytics-zoo#4200]
Hi @yangw1234 ,

can you please tell me how to define cluster_mode ?
Sorry to bother you, but I am still in the learning stage to different frameworks and coding.
![image](https://user-images.githubusercontent.com/78426877/124168894-f6ccad80-daa5-11eb-8ba9-ac189b4cb294.png)

Thank you a lot!

**Comment by glorysdj** [comment]
please try to type cluster_mode = "local" before the if codde

**Comment by cs201503** [comment]
> please try to type cluster_mode = "local" before the if code

@glorysdj Thank you very much!
Wish you a nice weekend!
