### ISSUE TITLE
jenkins: app test for chronos-network-traffic-autots-forecasting failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4201]
#17 start app test for chronos-network-traffic-autots-forecasting

2021-07-02 07:01:15,326	INFO services.py:1174 -- View the Ray dashboard at [1m[32mhttp://10.239.33.1:8265[39m[22m
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:393] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1367] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
apps/run-app-tests-pip.sh: line 948: 69905 Abort trap: 6           python ${ANALYTICS_ZOO_HOME}/../pyzoo/zoo/chronos/use-case/network_traffic/network_traffic_autots_forecasting.py

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-Pip-AppTests-MAC-py36/426/

**Comment by pinggao187** [comment]
@TheaperDeng pls have a look

**Comment by TheaperDeng** [comment]
the issue may related to #4074 , please refer to the solution in #4074. Still, we need to fix the mess on protobuf version with others help :(

**Comment by pinggao187** [comment]
[protobuf version issue #4074](https://github.com/intel-analytics/analytics-zoo/issues/4074)
