### ISSUE TITLE
Colab test not pass 

### ISSUE THREAD

**Issue by sgwhat** [intel-analytics/analytics-zoo#4263]
1. In orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb, I met an AttributeError: 'XGBRegressor' object has no attribute 'model' at Step4, best_model = auto_xgb_reg.get_best_model().model
 
2. In orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb, I met a ModuleNotFoundError: No module named 'tensorboardX' at Step 5, first block.

**Comment by TheaperDeng** [comment]
1. I believe it is related to #4216
2. I believe we can use `pip install analytics-zoo[automl]` in this notebook.

Since the notebook is created by @yushan111 , maybe we can wait for her to fix.

**Comment by pinggao187** [comment]
#4 start example for autoestimator_pytorch_lenet_mnist
~~~
 File "/opt/work/jenkins/workspace/ZOO-NB-Colab-Pytorch/docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.py", line 290, in <module>
    best_model.eval()
AttributeError: 'PytorchBaseModel' object has no attribute 'eval'
~~~
jenkins link:
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/162/

**Comment by TheaperDeng** [comment]
> #4 start example for autoestimator_pytorch_lenet_mnist
> 
> ```
>  File "/opt/work/jenkins/workspace/ZOO-NB-Colab-Pytorch/docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.py", line 290, in <module>
>     best_model.eval()
> AttributeError: 'PytorchBaseModel' object has no attribute 'eval'
> ```
> 
> jenkins link:
> http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/162/

This seems to be caused by old analytics-zoo version, I can not reproduce this.

**Comment by sgwhat** [comment]
> 1. I believe it is related to [Change return value of get_best_model to raw pytorch/tf model #4216](https://github.com/intel-analytics/analytics-zoo/pull/4216)
> 2. I believe we can use `pip install analytics-zoo[automl]` in this notebook.
> 
> I will fix it today
> 
> quick update issue 1 does not exist, since @sgwhat might use the open in colab button, that link points to a private repo's old version.

sorry, I put the error in the wrong sequence... issue1 is in orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb and issue 2 should in orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb.

**Comment by sgwhat** [comment]
> 1. I believe it is related to [Change return value of get_best_model to raw pytorch/tf model #4216](https://github.com/intel-analytics/analytics-zoo/pull/4216)
> 2. I believe we can use `pip install analytics-zoo[automl]` in this notebook.
> 
> I will fix it today
> 
> quick update issue 1 does not exist, since @sgwhat might use the open in colab button, that link points to a private repo's old version.

yes, I notice the colab example is an old version, the example could pass the test after I modify the code to the new version.

**Comment by TheaperDeng** [comment]
seems that this issue has been resolved, pls reopen it if needed
