### ISSUE TITLE
[Fatal] pip install analytics-zoo[automl] does not work on conda env

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4312]
#### How to reproduce this error?
Use `pip install --pre --upgrade analytics-zoo[automl]` or `pip install analytics-zoo[automl]==0.11.0` in an conda env.
pip will download **all** versions of some dependencies and make the installation never ends/VERY slow.

I have tried these env and they have the same issue:
1. (my laptop) Windows + WSL 2 + Python 3.6 + Conda 4.9.2 env + pip 21.1.2
2. (my laptop) Windows + WSL 2 + Python 3.7 + Conda 4.9.2 env + pip 21.1.2
3. Google Colab + Conda env
4. (Our server) Ubuntu + Conda env + ali source

I have tried these env and they **don't** have any issue:
1. Google Colab + without Conda env

#### What we may need to do?
If it is convenient, pls test the pip install command on our test env @pinggao187 , or maybe add it to some test job later?

Unfortunately I have not found which extra requirement(s) in automl causes this issue. I plan to rewrite the extra requirement(s) for automl again to fix this issue. I may need some help about how to test a new setup.py @helenlly

**Comment by pinggao187** [comment]
reproduce this issue in pip 21.1.3.

I have tried these env and they don't have any issue:

1. jenkins test py36/py37 env  (Gondolin)
pip 20.0.2 conda 4.8.3
pip 20.2.2 conda 4.8.3
2. new conda env  (Gondolin)
pip 20.0.2 conda 4.8.3
pip 20.2.2 conda 4.8.3

**Comment by TheaperDeng** [comment]
> reproduce this issue in pip 21.1.3.
> 
> I have tried these env and they don't have any issue:
> 
> 1. jenkins test py36/py37 env  (Gondolin)
>    pip 20.0.2 conda 4.8.3
>    pip 20.2.2 conda 4.8.3
> 2. new conda env  (Gondolin)
>    pip 20.0.2 conda 4.8.3
>    pip 20.2.2 conda 4.8.3

So it seems to be a pip version issue. Still, we need to make it work on pip>=21. I am trying to narrow down the conflict dependency.

**Comment by yushan111** [comment]
It might be related to [issue](https://github.com/pypa/pip/issues/9284). 

Shall we try pin the pip version?

**Comment by yushan111** [comment]
> 
> Shall we try pin the pip version? Reference [PR](https://github.com/Azure/azure-cli-dev-tools/pull/274/files) to change setup.py.

I didn't find an easy way to pin pip version in setup.py.

It is due to the extra dependency of `tsfresh`. When install `tsfresh`, pip will download the versions from the latest to the last version that meet the requirement of its dependencies. 
 
Therefore, we will try pin the `tsfresh` and some of its dependencies to a specific version to see whether the problem can be solved.

**Comment by TheaperDeng** [comment]
This issue should be fixed by #4324 , please feel free to reopen if it still happens.
