### ISSUE TITLE
Colab update python to 3.7.11 

### ISSUE THREAD

**Issue by sgwhat** [intel-analytics/analytics-zoo#4346]
This is an error caused by conda, Google has updated python vision to 3.7.11 in colab, which doesn't contain in conda and could not install the package. Colab examples with torch_distributed backend (include those passed testing by interns before code freeze) may not run successfully as before.

**Comment by sgwhat** [comment]
To fix this problem, I'll set all python env in colab examples to previous vision instead of getting from colab.

**Comment by Le-Zheng** [comment]
@pinggao18 we need to upgrade the python version to 3.7.11 in Jenkins colab notebook test.

**Comment by pinggao187** [comment]
can't upgrade python to 3.7.11.
~~~
PackagesNotFoundError: The following packages are not available from current channels:

  - python==3.7.11
~~~

**Comment by sgwhat** [comment]
> can't upgrade python to 3.7.11.
> 
> ```
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - python==3.7.11
> ```

There is no 3.7.11 package in conda, so maybe we could install 3.7.10 in jenkins? I am also converting colab python vision to 3.7.10  . @Le-Zheng

**Comment by Le-Zheng** [comment]
> > can't upgrade python to 3.7.11.
> > ```
> > PackagesNotFoundError: The following packages are not available from current channels:
> > 
> >   - python==3.7.11
> > ```
> 
> There is no 3.7.11 package in conda, so maybe we could install 3.7.10 in jenkins? I am also converting colab python vision to 3.7.10 .
> Or if we only wanna run script test in jenkins, could we install python 3.7.11 through other ways? @Le-Zheng @pinggao187

Ok. Keep the same python version for pytorch notebook testing on both colab and Jenkins.

**Comment by pinggao187** [comment]
upgrade python to 3.7.10.
test : http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/175/
