### ISSUE TITLE
analytics-zoo is larger than 200 MB

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4366]
HTTPError: 400 Client Error: File too large. Limit for project 'analytics-zoo' is 200 MB. See https://pypi.org/help/#file-size-limit for more information. for url: https://upload.pypi.org/legacy/

jenkins link:
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-WEEKLY-Publish-PyPI/68/console

**Comment by jason-dai** [comment]
Need to figure out which commit increase the size beyond 200MB @helenlly

**Comment by Le-Zheng** [comment]
It seems that after adding grpc in pom.xml, it increased from 198M to 207M.

**Comment by helenlly** [comment]
introduced by PR https://github.com/intel-analytics/analytics-zoo/pull/4273

**Comment by Le-Zheng** [comment]
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-WEEKLY-Publish-PyPI/70/ weekly-publish build scuccessfully.
