### ISSUE TITLE
jenkins: scala style check failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4395]
~~~
/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/java/com/intel/analytics/zoo/grpc/generated/azinference/Prediction.java:242: error: not found: type BuilderParent
      BuilderParent parent) {
      ^
/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/java/com/intel/analytics/zoo/grpc/generated/azinference/Prediction.java:68: error: not found: type FieldAccessorTable
  protected FieldAccessorTable
            ^
/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/java/com/intel/analytics/zoo/grpc/generated/azinference/Content.java:242: error: not found: type BuilderParent
      BuilderParent parent) {
      ^
/opt/work/jenkins/workspace/ZOO-NB-SCALA-StyleCheck/zoo/src/main/java/com/intel/analytics/zoo/grpc/generated/azinference/Content.java:68: error: not found: type FieldAccessorTable
  protected FieldAccessorTable
            ^
model contains 1088 documentable templates
~~~

jenkins link:
http://10.112.231.51:18888/job/ZOO-NB-SCALA-StyleCheck/1558/console

**Comment by pinggao187** [comment]
@Litchilitchy  pls have a look.
[Zoo Grpc inference Service #4367](https://github.com/intel-analytics/analytics-zoo/pull/4367)

**Comment by pinggao187** [comment]
spark 2.1 success
http://10.112.231.51:18888/job/ZOO-NB-SCALA-StyleCheck/1560/console
spark 2.4 failure
http://10.112.231.51:18888/job/ZOO-NB-SCALA-StyleCheck/1559/console

**Comment by Litchilitchy** [comment]
Trying to solve this issue

**Comment by glorysdj** [comment]
it's a compile error, nor specifically related to style check
please check if class BuilderParent FieldAccessorTable are in classpath

**Comment by Litchilitchy** [comment]
Other tests on 2.x, 2.4+, 3.0 all passed. Seems only happens on style check 2.4+ (style check also pass on 3.0)? But in pom there's nothing different with 2.4+ and 3.0

**Comment by glorysdj** [comment]
please refer to https://github.com/scala/bug/issues/9111
seems to be a scala 2.11 compile bug
not fixed in 2.11, need 2.12

**Comment by Litchilitchy** [comment]
fixed, please check @pinggao18

**Comment by pinggao187** [comment]
pass 
http://10.112.231.51:18888/job/ZOO-NB-SCALA-StyleCheck/1566/
