### ISSUE TITLE
jenkins: METH_OLDARGS is no longer supported

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4399]
~~~
Running chronos tests
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "pyarrow/types.pxi", line 2638, in pyarrow.lib._unregister_py_extension_types
SystemError: Bad call flags in _PyMethodDef_RawFastCallDict. METH_OLDARGS is no longer supported!
pyzoo/dev/run-pytests-ray: line 62: 88511 Segmentation fault: 11  python -m pytest -v ../test/zoo/chronos -k "not test_forecast_tcmf_distributed"
~~~
jenkins link:
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/238/console

**Comment by pinggao187** [comment]
spark 3.0.0 success
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/242/
spark 3.1.2 failure
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/238/console

**Comment by glorysdj** [comment]
please refer to https://github.com/PierreRaybaut/PythonQwt/issues/25
```it should be fixed with PyQt4 >= 4.11.4 and PyQt5 >= 5.4.```

**Comment by pinggao187** [comment]
upgrade pyarrow to 5.0.0,rerun
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/246/

**Comment by pinggao187** [comment]
pass 
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/249/console
