### ISSUE TITLE
jenkins: chronos tests timeout 8h

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4405]
~~~
Running chronos tests
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_BayesRecipe PASSED [ 12%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_GridRandomRecipe PASSED [ 13%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_LSTMGridRandomRecipe PASSED [ 14%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_MTNetGridRandomRecipe PASSED [ 14%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_MTNetSmokeRecipe PASSED [ 15%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_RandomRecipe PASSED [ 16%]
../test/zoo/chronos/config/test_recipe.py::TestTimeSequencePredictor::test_SmokeRecipe PASSED [ 16%]
../test/zoo/chronos/data/test_tsdataset.py::TestTSDataset::test_check_scale_sequence Build was aborted
~~~

jenkins link:
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON/262/
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/243/

**Comment by pinggao187** [comment]
@TheaperDeng pls have a look.

**Comment by TheaperDeng** [comment]
no idea why this would abort. Does it abort every time or randomly?

**Comment by pinggao187** [comment]
still timeout
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/250/

**Comment by TheaperDeng** [comment]
> still timeout
> http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/250/

So I may remove all the ut related to tsfresh since our MAC ut is extremely unfriendly to any code related to tsfresh. Is that OK @shane-huang ?

**Comment by TheaperDeng** [comment]
I will shrink the ut to theoretically smallest and rerun the ut again. If it is still the case, I decide to use -k command to skip these tsfresh related tests for MAC.

**Comment by pinggao187** [comment]
timeout on linux
~~~
../test/zoo/chronos/data/utils/test_deduplicate.py::TestDeduplicateTimeSeries::test_deduplicate_timeseries_dataframe PASSED [ 31%]
../test/zoo/chronos/data/utils/test_feature.py::TestFeature::test_gen_global_feature_multi_id Build was aborted
~~~
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/1088/console

**Comment by pinggao187** [comment]
success
http://10.112.231.51:18888/job/ZOO-NB-UnitTests-3.1-PYTHON-MAC/259/
