### ISSUE TITLE
TF2 estimator failed on MAC for failure to get CPU info

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/analytics-zoo#4422]
environment: spark2.4.3
python code
  
  estimator = Estimator.from_keras(model_creator=model_creator,
                                     verbose=False,
                                     config=config)

error information:
    cpuset = get_cgroup_cpuset()
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/cpu_info.py", line 23, in get_cgroup_cpuset
    with open("/sys/fs/cgroup/cpuset/cpuset.cpus", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpuset/cpuset.cpus'

**Comment by helenlly** [comment]
no such file in mac '/sys/fs/cgroup/cpuset/cpuset.cpus', ask wy to help

**Comment by yangw1234** [comment]
hi @songhappy would you mind trying this pr #4432

**Comment by songhappy** [comment]
two more things 
1. PR4432 forgot import sys 
2. if I disable cpu_bing when creating estimator like
estimator = Estimator.from_keras(model_creator=model_creator,
                                     verbose=False,
                                     cpu_binding=False,
                                     config=config)

it reports a different error message 
Traceback (most recent call last):
  File "train_2tower_tf2.py", line 293, in <module>
    model_dir=args.model_dir)
  File "train_2tower_tf2.py", line 61, in train
    config=config)
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/tf2/estimator.py", line 68, in from_keras
    cpu_binding=cpu_binding)
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/tf2/estimator.py", line 131, in __init__
    cpu_binding=cpu_binding
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/dl_cluster.py", line 103, in __init__
    for worker in self.remote_workers])
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/dl_cluster.py", line 103, in <listcomp>
    for worker in self.remote_workers])
  File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/ray/actor.py", line 104, in __call__
    raise TypeError("Actor methods cannot be called directly. Instead "
TypeError: Actor methods cannot be called directly. Instead of running 'object.disable_cpu_affinity()', try 'object.disable_cpu_affinity.remote()'.

**Comment by yangw1234** [comment]
> two more things
> 
> 1. PR4432 forgot import sys
> 2. if I disable cpu_bing when creating estimator like
>    estimator = Estimator.from_keras(model_creator=model_creator,
>    verbose=False,
>    cpu_binding=False,
>    config=config)
> 
> it reports a different error message
> Traceback (most recent call last):
> File "train_2tower_tf2.py", line 293, in
> model_dir=args.model_dir)
> File "train_2tower_tf2.py", line 61, in train
> config=config)
> File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/tf2/estimator.py", line 68, in from_keras
> cpu_binding=cpu_binding)
> File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/tf2/estimator.py", line 131, in **init**
> cpu_binding=cpu_binding
> File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/dl_cluster.py", line 103, in **init**
> for worker in self.remote_workers])
> File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/zoo/orca/learn/dl_cluster.py", line 103, in
> for worker in self.remote_workers])
> File "/Users/guoqiong/opt/anaconda3/envs/py37tf2/lib/python3.7/site-packages/ray/actor.py", line 104, in **call**
> raise TypeError("Actor methods cannot be called directly. Instead "
> TypeError: Actor methods cannot be called directly. Instead of running 'object.disable_cpu_affinity()', try 'object.disable_cpu_affinity.remote()'.

@songhappy how about now

**Comment by helenlly** [comment]
@pinggao187 pls help to test in MAC

**Comment by pinggao187** [comment]
> @pinggao187 pls help to test in MAC

UT successful
http://10.112.231.51:18888/view/ZOO-PR/job/ZOO-PR-UnitTests-2.4-PYTHON-MAC/9/
