### ISSUE TITLE
transform_min_max handle if value is >max or <min

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#4457]
Do we need to handle the new dataset values > max or < min in min_max_dict?
For values larger than max, we transform it to 1? smaller than min, transform it to 0?
Otherwise the resulting range is not [0, 1]

**Comment by jason-dai** [comment]
What's the behavior of Pandas?

**Comment by hkvision** [comment]
@jenniew Take a check with pandas and see if this issue needs to be resolved.

**Comment by jenniew** [comment]
In scikit learn, it just calculate as (x - min) / (max - min), even if out of range [0,1].  But if we train data within [0,1], when predict/evaluate, if the value out of the range[0,1], I'm not sure whether the result is reasonable.

**Comment by hkvision** [comment]
Yes, but I think forcing the range to be in [0, 1] is more reasonable?
If the model is trained on [0, 1], can it well recognize the values out of this range?

**Comment by jenniew** [comment]
Spark MinMaxScaler also just calculate as it is. I think it may be also acceptable. For train, If the the original values are in range [0, 2], after scale the range is [0,1]. For prediction/evaluate, if the original value is -5,  if we rescaled to 0, then original value of 0 and -5 have same result, maybe it is still not very explainable either. I think we may keep the same action with scikit learning and spark if no user complains.
