### ISSUE TITLE
BigDL2.0-PR-scalatest-others-spark2.4 failed with 7 test cases

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#4471]
However if update the jekins configuration to run the failed 7 test cases only. They can pass. For more detail, please refer https://github.com/intel-analytics/analytics-zoo/pull/4461 disscussion.

We may need figure out and fix the test issue.

**Comment by Le-Zheng** [comment]
Fixed. The UTs are testing in http://10.112.231.51:18080/job/BigDL-NB-scalatest-others-Spark-2.4/ and http://10.112.231.51:18080/job/BigDL-NB-utils-others/
