### ISSUE TITLE
CDH set up guide is missing

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#4481]
https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/hadoop.html#setup-for-cdh

CDH Version: CDH 5.X, CDH 6.X is not supported

Also this only sentence may cause misunderstanding. Better change to `We have tested on CDH 5.X. CDH 6.x is not supported.`

**Comment by qiyuangong** [comment]
Fixed by #4618

**Comment by hkvision** [comment]
Not only the typo, but also need to add the setup guide. Currently only one sentence in this section is not enough.

**Comment by hkvision** [comment]
Since there is no difference using CDH, we just need to remove this subsection. Close this issue and open a new one
