### ISSUE TITLE
Chronos: ProphetForecaster and AutoProphet bugs and enhancements

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/analytics-zoo#4486]
- [x] ProphetForecaster should add a param called `freq` to method predict, since the internal implement defaults the freq to 'D' while it is not always the case.
  - :param freq: freq: the freqency of the predicted dataframe, defaulted to day("D"), the frequency can be anything from the pandas list of frequency strings here: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases
- [x] AutoProphet should set a hp sample function as the default value for each tunable params.
- [x] AutoProphet takes a dataframe as input, rather than "1-D numpy array" stated in https://analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/Chronos/autotsestimator.html#chronos-autots-model-auto-prophet
- [x] We should automatically do train/valid split or cross validation (to be discussed) in autoprophet's fit rather than ask user to input a validation dataframe.
- [x] We should add predict, evaluate, save, load in autoprophet's methods.

**Comment by TheaperDeng** [comment]
@PeterQiu0516 might need your help to confirm if the first three items are bug or just my misusage. I will fix them after your confirmation.

**Comment by PeterQiu0516** [comment]
- [x] No, we should not add param `freq` to the method `predict`, Prophet `predict` method does not support `freq`, see here: https://github.com/facebook/prophet/blob/cd8a24eddd6bebb9888f2e0ae2388f209047b02d/python/prophet/forecaster.py#L1184.
    Instead, in order to specify the `freq`, we need to specify the `ds` column of the dataframe, see example in our test:
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/chronos/model/test_prophet.py#L39
    We could specify `self.data = pd.DataFrame(pd.date_range('20130101', periods=self.seq_len, freq='D'), columns=['ds'])`.
- [x] Yes, and this is already made clear in the comments:  https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/chronos/autots/model/auto_lstm.py#L32
    I am passing in a value instead of a hp sample function as default only to keep consistent with our other autots API (e.g, `auto_lstm`: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/chronos/autots/model/auto_lstm.py#L32)
- [x] Yes, as specified in https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/chronos/model/prophet.py#L57-L59. Thank you for catching up that mistake in comment :)
