### ISSUE TITLE
ppml python docker pulling message from unreachable network address 10.239.45.10

### ISSUE THREAD

**Issue by yzz127** [intel-analytics/analytics-zoo#4542]
Issue Description:
Following command found in deploy-local-spark-sgx.sh under python docker path
```
sudo docker pull 10.239.45.10/arda/intelanalytics/analytics-zoo-ppml-trusted-big-data-ml-python-graphene:0.11-SNAPSHOT
```

Error message:
Error response from daemon: Get "https://10.239.45.10/v2/": dial tcp 10.239.45.10:443: connect: network is unreachable
WARNING: Disabling the OOM killer on containers without setting a '-m/--memory' limit may be dangerous.
Unable to find image '10.239.45.10/arda/intelanalytics/analytics-zoo-ppml-trusted-big-data-ml-python-graphene:0.11-SNAPSHOT' locally
docker: Error response from daemon: Get "https://10.239.45.10/v2/": dial tcp 10.239.45.10:443: connect: network is unreachable.

Suggested fix:
It seems simply removing the "10.239.45.10/arda/" prefix will get the docker images pulled successfully. Please double check and verify. Thanks!

**Comment by glorysdj** [comment]
It's a wrong docker registry. We will fix this.

**Comment by glorysdj** [comment]
fixed
