### ISSUE TITLE
No module named 'zoo.orca'

### ISSUE THREAD

**Issue by lixiepeng** [intel-analytics/analytics-zoo#4588]
```
from zoo.orca import init_orca_context
ModuleNotFoundError: No module named 'zoo.orca'
```

**Comment by hkvision** [comment]
Hi, how do you install analytics-zoo and which version do you use? You may refer to here for installation and run: https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/python.html

**Comment by lixiepeng** [comment]
> Hi, how do you install analytics-zoo and which version do you use? You may refer to here for installation and run: https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/python.html

```
ERROR: Could not find a version that satisfies the requirement pyspark==2.4.6
ERROR: No matching distribution found for pyspark==2.4.6
```

**Comment by hkvision** [comment]
pyspark 2.4.6 is released here: https://pypi.org/project/pyspark/2.4.6/ Seems there's something wrong with your pip install.
You should check your pip install configurations (probably set a mirror in `~/.pip/pip.conf` or add `-i https://pypi.python.org/simple` when pip install?)

**Comment by hkvision** [comment]
If you encounter the following error when pip install
```
ERROR: Could not find a version that satisfies the requirement pypandoc (from versions: none)
    ERROR: No matching distribution found for pypandoc
    Could not import pypandoc - required to package PySpark
```
You need to `pip install pypandoc` first and then analytics-zoo.

**Comment by lixiepeng** [comment]
> If you encounter the following error when pip install
> 
> ```
> ERROR: Could not find a version that satisfies the requirement pypandoc (from versions: none)
>     ERROR: No matching distribution found for pypandoc
>     Could not import pypandoc - required to package PySpark
> ```
> 
> You need to `pip install pypandoc` first and then analytics-zoo.

it works

**Comment by hkvision** [comment]
> If you encounter the following error when pip install
> 
> ```
> ERROR: Could not find a version that satisfies the requirement pypandoc (from versions: none)
>     ERROR: No matching distribution found for pypandoc
>     Could not import pypandoc - required to package PySpark
> ```
> 
> You need to `pip install pypandoc` first and then analytics-zoo.

@jason-dai Shall we add this to FAQ? Seems this error happens from time to time when installing pyspark. Users may treat this error is raised when installing analytics-zoo.

**Comment by jason-dai** [comment]
> > If you encounter the following error when pip install
> > ```
> > ERROR: Could not find a version that satisfies the requirement pypandoc (from versions: none)
> >     ERROR: No matching distribution found for pypandoc
> >     Could not import pypandoc - required to package PySpark
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You need to `pip install pypandoc` first and then analytics-zoo.
> 
> @jason-dai Shall we add this to FAQ? Seems this error happens from time to time when installing pyspark. Users may treat this error is raised when installing analytics-zoo.

Let add this as known issue in the Python user guide.
