### ISSUE TITLE
Deprecate AutoTSTrainer and use AutoTSEstimator instead

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/analytics-zoo#4675]
Documents

- [x] Remove [quick start](https://analytics-zoo.readthedocs.io/en/latest/doc/Chronos/QuickStart/chronos-autots-quickstart.html) #4705
- [x] Replace ` AutoTSTrainer` with `AutoTSEstimator` in [user guide](https://analytics-zoo.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html#use-autots-pipeline-with-automl) #4705
- [ ] Deprecate in API index

Code

- [ ] add deprecated warning for `AutoTSTrainer` and `TSPipeline` and move to `autots.deprecated`
- [ ] move corresponding UT/use-case/examples to deprecated
- [ ] move `AutoTSEstimator` and `TSPipeline` out of `experimental`

**Comment by TheaperDeng** [comment]
We may also need to remove the `AutoTSTrainer`'s notebook and example scripts.
