### ISSUE TITLE
jenkins: analytics-zoo upload failed (> 200M)

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4679]
~~~
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File too large. Limit for project 'analytics-zoo' is 200 MB. See https://pypi.org/help/#file-size-limit for more information. for url: https://upload.pypi.org/legacy/
~~~
jenkins link: 
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-WEEKLY-Publish-PyPI/86/console

**Comment by sgwhat** [comment]
After releaseing zoo-core with intel-tensorflow1.15.0up3, the size of zoo will incease 10MB, that's caused by libtensorflow_jni.so.

**Comment by pinggao187** [comment]
fixed 
[update pom.xml to reduce whl size #4717](https://github.com/intel-analytics/analytics-zoo/pull/4717)

pass
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-WEEKLY-Publish-PyPI/94/
