### ISSUE TITLE
Corrupt record when reading Json file for DIEN meta_Books.json

### ISSUE THREAD

**Issue by yizerozhuang** [intel-analytics/analytics-zoo#4694]
When reading a json file call meta_book.json, some of the lines corrupt during reading the json file by read_json() in friesian.
It returns null for all the columns, so there are rows remove after drop na opration which effect the final result.
Ai-matrix and recdp groups convert json file to csv file first, it doesn't remove any rows and work fine in spark.
The 14th record in the following figure is one of the records that corrupt during reading.
![image](https://user-images.githubusercontent.com/48541207/132650284-db3e8f44-c427-4a3c-8164-5c7bfe834334.png)

One workaround is to convert to csv first (like what ai-matrix does), though the conversion may take extra time.

**Comment by hkvision** [comment]
Fixed.
Changed to csv or using read_text and use a udf to parse each row.
