### ISSUE TITLE
Failed to build after add bigdl2.0 as dependency to a new project

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#4996]
add below lines to a brand new project pom.xml:
        <dependency>
            <groupId>com.intel.analytics.bigdl</groupId>
            <artifactId>bigdl-dllib-spark_2.4.6</artifactId>
            <version>0.14.0-SNAPSHOT</version>
        </dependency>

and when using "mvn clean package", there is error:

_Downloading from sonatype: https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/bigdl-dllib-spark_2.4.6/0.14.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype: https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/bigdl-dllib-spark_2.4.6/0.14.0-SNAPSHOT/maven-metadata.xml (1.7 kB at 1.8 kB/s)
Downloading from sonatype: https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/bigdl-parent-spark_$%7Bspark.version%7D/0.14.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype: https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/**bigdl-parent-spark_$%7Bspark.version%7D**/0.14.0-SNAPSHOT/**bigdl-parent-spark_$%7Bspark.version%7D**-0.14.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.272 s
[INFO] Finished at: 2021-10-15T01:39:33-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project groupByTest: Could not resolve dependencies for project org.apache.spark:groupByTest:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.intel.analytics.bigdl:bigdl-dllib-spark_2.4.6:jar:0.14.0-SNAPSHOT: Failed to read artifact descriptor for com.intel.analytics.bigdl:bigdl-dllib-spark_2.4.6:jar:0.14.0-SNAPSHOT: Could not find artifact com.intel.analytics.bigdl:bigdl-parent-spark_${spark.version}:pom:0.14.0-SNAPSHOT in sonatype (https://oss.sonatype.org/content/groups/public/) -> [Help 1]_

Seems like ${spark.version} in artifact id is not parsed in parent.pom

**Comment by Le-Zheng** [comment]
We have published new dependencies. Please pull newly artifact `mvn package -U` .
