### ISSUE TITLE
pypi: Project size too large. Limit for project 'analytics-zoo' total size is 10 GB

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#5070]
http://10.112.231.51:18888/view/ZOO-NB-Overview/job/ZOO-Daily-Publish-PyPI/174/
http://10.112.231.51:18888/view/ZOO-NB-Overview/job/ZOO-Daily-Publish-PyPI/175/

HTTPError: 400 Client Error: Project size too large. Limit for project 'analytics-zoo' total size is 10 GB. See https://pypi.org/help/#project-size-limit for url: https://upload.pypi.org/legacy/

**Comment by glorysdj** [comment]
too many dev versions are uploaded. need to clear old dev versions.

**Comment by jason-dai** [comment]
I think the plan is to delete old dev packages on weekly basis (for zoo, bigdl, etc.)

**Comment by glorysdj** [comment]
The pypi dev versions for analytics-zoo clean job will be resumed.
