### ISSUE TITLE
The tfnet example doens't process all the image in the image path

### ISSUE THREAD

**Issue by nwang2** [intel-analytics/analytics-zoo#600]
https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/tfnet
Follow the guide to run this example, we noticed that it didn't process all the images.

**Comment by helenlly** [comment]
@yangw1234 pls have a look.

**Comment by yangw1234** [comment]
this is demo only and this is what should be expected. Change rdd.first() to other actions like rdd.collect() will trigger all compution.

Close it now.
