### ISSUE TITLE
请问: 这里one-hot之后索引对应的值为什么是索引值+1？

### ISSUE THREAD

**Issue by squirren** [intel-analytics/analytics-zoo#658]
https://github.com/intel-analytics/analytics-zoo/blob/82aa26680e1830f60a4757aa1befe7ff04a2d9b2/zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala#L111

**Comment by songhappy** [comment]
In the categoricalFromVocabList, it saves o for unseen ones, so indices include 0, but BigDL expects 1-based indexing in the model.
