### ISSUE TITLE
Readme/notebooks of examples need updates about  "install from pip" / "download prebuilt package"

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#718]
1.  For Python Notebooks/Examples README, we need to change building the project from source to install from pip and download prebuilt package and update the running commands (either by python or with scripts) accordingly.
For Python Examples, you can refer to the following:

- [ 1 ]  Download instructions:
 https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/textclassification#install-or-download-analytics-zoo 
- [ 2 ] Run after pip command:
 https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/textclassification#run-after-pip-install 
- [ 3 ] Run with prebuilt package command:
 https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/textclassification#run-with-prebuilt-package 

For Python Apps, you can do something similar.

2. For Scala Examples README, we need to change building the project from source to download prebuilt package and update the running commands with scripts:

- [ 1 ] Download instructions:
https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification#download-analytics-zoo 

- [ 2 ] Run command:
https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification#run-this-example

3.  Also, to make safe, after modifying the running command, better manually or update Jenkins scripts to make sure the command can work successfully.

4.  original issue refer to https://github.com/intel-analytics/zoo/issues/366 

5. Feel free to raise suggestions if you have a better way to elaborate the README. (edited by Kai)

**Comment by jason-dai** [comment]
Please create issues for each owner

**Comment by hkvision** [comment]
Also need to update the jenkins test scripts here:
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/run-example-tests.sh

**Comment by hkvision** [comment]
Also @songhappy https://github.com/intel-analytics/analytics-zoo/blob/master/apps/run-app-tests.sh
Here the memory usage for anomaly detection is out of date (should be 2g), better to update this :)
