### ISSUE TITLE
Need to update run-example scripts

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#721]
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/run-example-tests.sh

Change ANALYTICS_ZOO_HOME to ANALYTICS_ZOO_ROOT
ANALYTICS_ZOO_HOME_DIST to ANALYTICS_ZOO_HOME

To make things consistent and not confusing

**Comment by glorysdj** [comment]
I think the later names are more confusing. Home is the root directory of zoo, and dist is is the dirstribution of zoo. like jdk, we set JAVA_HOME, and bin is the sub directory in it, we don't set bin as JAVA_HOME.

**Comment by hkvision** [comment]
No, we use the latter convention everywhere in our project as we don't expect users to build from source but download the dist package. Then in this case what is `ANALYTICS_ZOO_HOME`? Seems Spark does in this way as well. This has been discussed with @jason-dai
