### ISSUE TITLE
Zoo keras layers has to be put into sequential to successfully run?

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#740]
I found there is exception with code:
`    val layer = TimeDistributed[Float](Dense(8, activation = "relu"), inputShape = Shape(10, 12))
    val input = Tensor[Float](2, 10, 12)
    layer.forward(input)`
and the exception is "This Layer hasn't been built"

After I put the layer in sequential, it can successfully run.
`    val seq = Sequential[Float]()
    val layer = TimeDistributed[Float](Dense(8, activation = "relu"), inputShape = Shape(10, 12))
    val input = Tensor[Float](2, 10, 12)    
    seq.add(layer)    
    seq.forward(input)`

I am not sure if this is by design and if we need improve it.

**Comment by hkvision** [comment]
Yes, the design aligns with Keras, where a layer should be built before doing forward. Here you can build a layer by adding it to a Sequential or connecting it with a node.

**Comment by dding3** [comment]
Ok. I see. Thanks for your clarification.
